### ISSUE TITLE
Unable to use Nginx Proxy Manager when forcing SSL for HA

### ISSUE THREAD

**Issue by escoand** [hassio-addons/addon-nginx-proxy-manager#10]
# Problem/Motivation
I've switched to this really nice addon - no more plumbing by hand, thanks. But currently it's not possible to use it on port 81 when HA is accessed through the domain name with activated "Force SSL". It always tries to switch to HTTPS which does not exist on this port.

## Expected behavior
Don't know exactly how to avoid this. Maybe this could be done with HA Ingress, but I don't know the technical part of it.

## Actual behavior
see Problem/Motivation

## Steps to reproduce
1. create a proxy host for http://homeassistant:8123
2. activate "Force SSL" and "HSTS Enabled"
3. open the proxy host
4. try to open the Nginx Proxy Manager through the proxy host

## Proposed changes
Not sure.

**Comment by escoand** [comment]
Ingress seems to be a solution for this. According to the description it should be as simple as connect the internal 81 to an external 8099. The IP restriction should be also no problem.

So just the "treated as authenticated" could be a higher hurdle.

**Comment by sinclairpaul** [comment]
Unfortunately its a little more challenging that a port forward to implement ingress due to issues with redirects and paths within the application itself.  Isn't this a bit chicken and egg scenario though, as if your cert expires, how will you fall back?, assuming that you can access the app via the original URL?

**Comment by escoand** [comment]
Good point, didn't think about it. But you should still have the option to use the local IP address with HTTP to log into HA.
Or we have both ports, 81 and 8099.

**Comment by frenck** [comment]
This is how HTST works... I cannot change the internet.
