### ISSUE TITLE
Feature request: Ability to use cert stored in HA

### ISSUE THREAD

**Issue by Marko298** [hassio-addons/addon-nginx-proxy-manager#100]
# Problem/Motivation

> I have a domain pointing to HA but not exposed to internet. I use Let's Encrypt addon to issue and renew cert thought DNS challenge via Cloudflare. Is there a way I can use cert that is placed inside Home Assistant's SSL share?

**Comment by frenck** [comment]
Unfortunately, that is not something that can be added to the add-on.
Alternatively, one can upload certs into the NGINX proxy manager.
