### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by r-dub** [hassio-addons/addon-nginx-proxy-manager#102]
# Problem/Motivation

Error when installing addon

## Actual behavior

20-07-30 22:42:09 INFO (SyncWorker_1) [supervisor.docker.interface] Pull image hassioaddons/nginxproxymanager-amd64 tag 0.6.0.
20-07-30 22:42:17 ERROR (SyncWorker_1) [supervisor.docker.interface] Can't install hassioaddons/nginxproxymanager-amd64:0.6.0 -> 404 Client Error: Not Found ("no such image: hassioaddons/nginxproxymanager-amd64:0.6.0: No such image: hassioaddons/nginxproxymanager-amd64:0.6.0").

## Proposed changes

Create image?

**Comment by sinclairpaul** [comment]
404's are generally name resolution or disk space issues.

**Comment by r-dub** [comment]
Yep, disk was full.  Thanks!
