### ISSUE TITLE
Can't add my own certificate

### ISSUE THREAD

**Issue by whasf** [hassio-addons/addon-nginx-proxy-manager#103]
# Problem/Motivation

> I have my own wildcard certificate that I use, I'd like to import it

## Expected behavior

> I should be allowed to upload my own certificate

## Actual behavior

> It seems I can only request a LetsEncrypt certificate when I click on "Add SSL Certificate" button

## Steps to reproduce

> Click on SSL Certificates tab, then click on "Add SSL Certificate"

## Proposed changes

> Provide a way to upload my own certificate and key

**Comment by sinclairpaul** [comment]
Add SSL Certificate, Custom.

**Comment by whasf** [comment]
Oops! If I click the "Add SSL Certificate" in the upper right, i see the ability to add custom! Still waking up :)
