### ISSUE TITLE
Forward only the port 443 to RD gateway server

### ISSUE THREAD

**Issue by terslowe** [hassio-addons/addon-nginx-proxy-manager#106]
# Problem/Motivation

I need to forward the 443 port to the RD gateway server. RD gateway server have own SSL certification from 3th party. Just letsencrypt is not needed.

Is that possible?

I am forwarding just 443 to 443 from such domain xxx.yyy.com but the RD gateway is not recognizing that. What i am dooing wrong here?

**Comment by frenck** [comment]
This is not a TCP forwarder, but a reverse proxy. Which means it is in the middle. This is probably not the solution you are looking for.
