### ISSUE TITLE
Proxy Manager won't start

### ISSUE THREAD

**Issue by tomlynn** [hassio-addons/addon-nginx-proxy-manager#107]
# Problem/Motivation

I'm filing this issue because I believe I've followed the instructions faithfully by first loading and starting the mariadb add on prior to the proxy manager add on.  NGINX reverse proxy was loaded before either of them.  I do not see how mariadb supports this add on without a database configurationo for the proxy manager add on.

## Expected behavior

Nginx Proxy Manager starts and provides a link to the web GUI.

## Actual behavior

After clicking start, the start button flashes reverse video red and the add on does not start, leaving the view of the start button.  No log entries are ever made even after changing the logging level to debug.

## Steps to reproduce

Click start.

## Proposed changes

I do not have a fix, but am happy to participate in log collection.  Currently running under Ubuntu Linux 18.04 on an intel i3 system with 8gb ram

**Comment by sinclairpaul** [comment]
The database setup is handled by the addon, however you are not reaching that stage.

Please check and post the supervisor log, at a guess it will state you have something else running on 80/443.

**Comment by tomlynn** [comment]
NGINX itself is configured with port 443.  CLI command lsof -i tcp:443 returns an empty result.

**Comment by sinclairpaul** [comment]
> NGINX itself is configured with port 443

Which nginx is this?, if you are already running the core nginx addon, it will be using the port.

**Comment by tomlynn** [comment]
NGINX Home Assistant SSL proxy
Current version: 3.0.1 (changelog)

**Comment by tomlynn** [comment]
Well, don't I feel foolish.  I had thought the proxy manager was a bolt on management portal for the other NGINX SSL Proxy add on.  It's both, isn't it?

**Comment by frenck** [comment]
No it isn't related to that core addon, it is a full replacement and they don't play well together.

**Comment by tomlynn** [comment]
If I'm the only one that's been fooled, then clarification is likely unnecessary.  Thank you Paul and Frenck, I'm up and running now.
