### ISSUE TITLE
Unable to use Hass.io panel when use access list for HA

### ISSUE THREAD

**Issue by escoand** [hassio-addons/addon-nginx-proxy-manager#11]
# Problem/Motivation
When setting a access list for the HA proxy host the Hass.io panel is not working.

## Expected behavior
Use the Hass.io panel like all the other HA panels as well.

## Actual behavior
The connection to `http://myproxyhost/api/hassio/...` is closed with `401 Unauthorized`.

## Steps to reproduce
1. create a proxy host for http://homeassistant:8123
2. set an Access List
3. open the proxy host
4. try to open the Hass.io panel through the proxy host

## Proposed changes

**Comment by escoand** [comment]
No, not a duplicate, just similar.

**Comment by frenck** [comment]
@escoand "Potential"  ;)

Nevertheless, that is expected, both authentication methods rely on the Authorization headers. So they will conflict. This is how HTTP works, there is not much I can do about it.
