### ISSUE TITLE
ERROR 2002 (HY000): Can't connect to MySQL server on 'core-mariadb' (115)

### ISSUE THREAD

**Issue by ReenigneArcher** [hassio-addons/addon-nginx-proxy-manager#110]
# Problem/Motivation

Add-on won't start due to "ERROR 2002 (HY000): Can't connect to MySQL server on 'core-mariadb' (115)"

## Expected behavior

Connect to server, or better documentation for configuration. Is anything required to change in MariaDB configuration?

## Actual behavior

```[13:42:42] DEBUG: Requested API resource: http://supervisor/services/mysql
[13:42:42] DEBUG: Request method: GET
[13:42:42] DEBUG: Request data: {}
[13:42:42] DEBUG: API HTTP Response code: 200
[13:42:42] DEBUG: API Response: {"result": "ok", "data": {"host": "core-mariadb", "port": 3306, "username": "service", "password": "removed", "addon": "core_mariadb"}}
ERROR 2002 (HY000): Can't connect to MySQL server on 'core-mariadb' (115)
[cont-init.d] mysql.sh: exited 1.
```

## Steps to reproduce

> Not sure. This is a fresh install of the add-on. Maria-db is installed and setup as a recorder for HomeAssistant.

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Please provide details on your installation methods used.
This data is provided by the Supervisor, it is a bit weird one cannot connect to it.

**Comment by ReenigneArcher** [comment]
The issue is fixed. I think the issue was because I recently migrated my HA setup from Rasp Pi to a VM and didn't properly restore MariaDB (I read somewhere that's not included with snapshots). I uninstalled MariaDB and re-installed and it's working now.
