### ISSUE TITLE
[FEATURE] Support for the custom files from HA filesystem to be able to use Authenticated Origin Pulls

### ISSUE THREAD

**Issue by MyKEcz** [hassio-addons/addon-nginx-proxy-manager#111]
# Problem/Motivation

To enable Authenticated Origin Pulls provided by CloudFlare we need to upload certificate provided [here](https://support.cloudflare.com/hc/en-us/articles/204899617#section6).

Once certificate uploaded we need to place custom configuration to [verify client certificate](https://support.cloudflare.com/hc/en-us/articles/204899617#section5).

## Expected behavior

Provide in the Hass.io plugin the path to File system when during startup of the plugin will be placed into pre-defined folder mentioned file.

For example:

```
upload_file:
  - /config/www/origin-pull-ca.pem
```

Will be placed during startup of the plugin into the:

`/usr/share/origin-pull-ca.pem`

Where we can include nginx custom configuration:

```
    ssl_client_certificate /usr/share/origin-pull-ca.pem;
    ssl_verify_client on;
```

## Actual behavior

Uploading of a files into the nginx proxy manager container from the HA filesystem is not supported.

## Steps to reproduce

N/A

## Proposed changes

> Mentioned in the Expected behavior.

**Comment by frenck** [comment]
This add-on wraps an existing application, the NGINX Proxy Manager. I'm not planning on adding additional custom stuff to this add-on.

Furthermore, please note, Hass.io doesn't exist anymore, you should not use that term.
