### ISSUE TITLE
Unable to connect to Home Assistant.

### ISSUE THREAD

**Issue by bobsiboo** [hassio-addons/addon-nginx-proxy-manager#112]
# Problem/Motivation

when connecting to HA via nginx  the HA logo is shown with the message
"Unable to connect to Home Assistant."  and a retry button

HA is reachable on port 812. internal connection works fine
> (Why the issue was filed)

## Expected behavior
access to home assistant
> (What you expected to happen)

## Actual behavior
HA logo is shown with the message
"Unable to connect to Home Assistant."  and a retry button
> (What actually happened)

## Steps to reproduce
 
> (How can someone else make/see it happen)

## Proposed changes
 
> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

==========================
additional info: This has worked for 5 months without problem, problem started after reuploading a snapshot from the day because HA had become unresponsive after a unexpected reboot.
HA is running in a VM on proxmox.
router is a pfsense running in a VM
Portforwarding used to work so assuming it is ok.

**Comment by frenck** [comment]
This sounds like WebSockets are not enabled on the virtual host?

**Comment by bobsiboo** [comment]
I m not sure what i ve set up wrong then. Up untill last week this was working without issue.

**Comment by bobsiboo** [comment]
Update: i think i fixed it.
For some reason my homeassistant kept updating duckdns with a wrong ip causing my browser to try and open a cached version of Home assistant. so the interface loaded but the backend was not connected of course causing the error.

Manualy updating the dns record to my pfsense WAN ip fixed the issue.

I did notice that for some reason when i try to check what my public ip is i get the wrong adress  on multiple websites. 
Any idea what can cause this? i noticed it causes certificate updates to fail
