### ISSUE TITLE
Unable to do a clean install after the 1st install

### ISSUE THREAD

**Issue by richard-scott** [hassio-addons/addon-nginx-proxy-manager#113]
# Problem/Motivation

> After getting lots of SSL certificate "Internal error" I thought it best to start from scratch.

## Expected behavior

> When I delete the Addon, and re-install the Addon I'd expect my old data to be erased.

## Actual behavior

> After re-installing the addon I still have my old login details and hosts setup.

## Steps to reproduce

> 1. Install the Addon.
> 2. change your password and login details.
> 3. Delete Addon.
> 4. Install the Addon again.
> 5. Try and login with admin@example account.

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by sinclairpaul** [comment]
The addon uses MariaDB to store the data, which unfortunately isn't removed on an uninstall.  The easiest way to remove this data is to use the phpMyAdmin addon to drop the nginxproxymanager database, with the addon stopped.  On startup it should then recreate a new database.

**Comment by sinclairpaul** [comment]
The latest release includes a config option to allow re-creation of the database, please see the documentation for details.
