### ISSUE TITLE
Cant connect to MariaDB

### ISSUE THREAD

**Issue by albznw** [hassio-addons/addon-nginx-proxy-manager#114]
# Problem

Recently I completely reinstalled my Home Assistant setup and now I can't get the Nginx proxy manager to work again. I have installed MariaDB as required and the proxy manager. However, upon trying to start the proxy manager it crashes with the error "Something went wrong contacting the API". Seems like the proxy manager cant talk to MariaDB.

Probably because there's some setting that I've missed. However, I've followed the installation guide and it does not mention any special settings for MariaDB. But perhaps this problem has something to do with the fact that MariaDB has to be added to the HomeAssistant configuration file? Maybe an nginx user has to be created?

## Actual behavior

Log from the proxy manager plugin:

```sh
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] permissions: applying... 
[fix-attrs.d] permissions: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
Error relocating /usr/bin/curl: unsupported relocation type 1588453037
[00:36:27] ERROR: Something went wrong contacting the API
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] mysql.sh: executing... 
[00:36:29] ERROR: This add-on now requires the MariaDB core add-on 2.0 or newer!
[00:36:29] FATAL: Make sure the MariaDB add-on is installed and running
[cont-init.d] mysql.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

## Steps to reproduce

* Fresh install of Home Assistant
* Install official MariaDB addon
* Install Nginx proxy manager
* Start MariaDB addon
* Start Nginx proxy manager

## Proposed changes

Add the solution for this kind of connectivity problem to the documentation.

**Comment by sinclairpaul** [comment]
Please post the start of the log:

`[cont-init.d] 00-banner.sh: executing... 
Error relocating /usr/bin/curl: unsupported relocation type 1588453037`

Appears to be an issue contacting the supervisor

**Comment by sinclairpaul** [comment]
Looking at this again, please confirm you OS and Docker version.

**Comment by albznw** [comment]
Hi!

So, between posting this issue and now. Some updates to Home Assistant have been released. More specifically, I upgraded Home Assistant Core from `0.116.2` to `0.116.4`. In addition, I upgraded the OS (I'm running the HassOS image on my Raspberry Pi 3 B+) from `4.13` to `4.14`. However, the problem remains.

I can't give you more of the log. I've copied as much as I can. See the picture below for a screenshot. If there's another way to get the full log let me know and I'll do that! Regarding the firewalls, I have no idea if there are any. Shouldn't this just work out of the box if you are using the Hassio OS?

![Screenshot of log](https://i.gyazo.com/7d139be46a2ad1c3626a65bb0224ce83.png)

I'm not seeing this error on any of the other addons I'm afraid. The ones I have installed at the time are:
* ESPHome
* MariaDB
* Mosquitto broker
* Samba share

and they are all working fine

These are the system specifications:
```
Supervisor version: 247
Operating system: HassOS 4.14
```

**Comment by sinclairpaul** [comment]
The errors suggest to me you have some form of arch mismatch (what image did you install?), I can't see this as an addon issue.

In answer to your questions, it doesn't matter as curl is failing to access the supervisor api.

At this point I would probably test installing any other Community addon, and then logging an issue with the Supervisor repo.

**Comment by albznw** [comment]
Just installed InfluxDB, which is a community addon, and that worked like a charm.

![InfluxDB output](https://i.gyazo.com/7368ae52cc5c37c4091694183ba8e0bd.png)

**Comment by sinclairpaul** [comment]
So in all honesty, I'm out of ideas.

It could be some sort of disk issues, if you uninstall/reinstall does it start?  It is not an issue with contacting the MariaDB addon.

Maybe try a `ha supervisor repair`

**Comment by albznw** [comment]
Reinstalled the whole operating system and now it works again! Thank you Paul for your help though! :D
I'm closing the issue now
