### ISSUE TITLE
Can't add custom SSL certificate

### ISSUE THREAD

**Issue by ilyavolodin** [hassio-addons/addon-nginx-proxy-manager#116]
# Problem/Motivation

> Whenever I try to add a custom certificate, nothing happens when you hit save button.

## Expected behavior

> Should properly add custom certificate

## Actual behavior

> Console error:
```
Uncaught TypeError: Cannot read property 'cloudflare_use' of undefined
    at i.click @ui.save (17.bundle.17.js:1)
    at HTMLDivElement.dispatch (main.bundle.js?v=0.0.0:27)
    at HTMLDivElement.p.handle (main.bundle.js?v=0.0.0:27)
```

## Steps to reproduce

> Navigate to "SSL Certificates" tab, press "Add SSL Certificate" and select "Custom". Fill out name, select a file for private key and certificate and hit "Save" button.

**Comment by THATDONFC** [comment]
I'm having the same issue and seeing the same error in the Brave Browser console. I also tried Safari and got the same results.
```
17.bundle.17.js:1 Uncaught TypeError: Cannot read property 'cloudflare_use' of undefined
    at i.click @ui.save (17.bundle.17.js:1)
    at HTMLDivElement.dispatch (main.bundle.js?v=0.0.0:27)
    at HTMLDivElement.p.handle (main.bundle.js?v=0.0.0:27)
click @ui.save @ 17.bundle.17.js:1
dispatch @ main.bundle.js?v=0.0.0:27
p.handle @ main.bundle.js?v=0.0.0:27

**Comment by sinclairpaul** [comment]
Looks to be fixed upstream, but will need a new addon release to resolve.

**Comment by scsi050** [comment]
Same issue for me in Chrome browser 87.0.4280.20, Hassio Nginx Proxy Manager add-on version 0.7.0

**Comment by frenck** [comment]
Solved in:

⬆️ NGINX Proxy Manager v0.8.0

https://github.com/hassio-addons/addon-nginx-proxy-manager/releases/tag/v0.8.0
