### ISSUE TITLE
Ingress support

### ISSUE THREAD

**Issue by reharmsen** [hassio-addons/addon-nginx-proxy-manager#12]
# Problem/Motivation
> (Why the issue was filed)
This not really an issue but more a feature request.
Would be nice to have Ingress support, this would make it possible to use the nginx-proxy-manager while being outside of my network by just logging in to home assistant (with 2 factor authentication)

## Expected behavior
> (What you expected to happen)
Being able to access nginx-proxy-manager through ingress

## Actual behavior
> (What actually happened)
It's not supported

## Steps to reproduce
> (How can someone else make/see it happen)
It's not possible to reproduce as this is not supported

## Proposed changes
> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)
Build in Ingress support

**Comment by reharmsen** [comment]
This seems to explain how to add ingress support
https://developers.home-assistant.io/docs/en/next/hassio_addon_presentation.html#ingress

It seems the addon wil need to accept connetions on 8099 instead of port 81.
I am not sure whether nginx-proxy-manager is able to support authenticated connections

**Comment by sinclairpaul** [comment]
Thanks, many of the addons here have ingress, there are additional challenges that need to be resolved with this one.  Trust me if was easy to implement it would have been done on the first release :)  Adding ingress to all addons is on the list.

**Comment by sinclairpaul** [comment]
Will leave it open for now, unless @frenck wants to close it off.

**Comment by frenck** [comment]
@reharmsen Thank you for your request.
I know how to do Ingress 😉 

This add-on cannot support it, therefore closing the issue.
