### ISSUE TITLE
Failed to start addon

### ISSUE THREAD

**Issue by hyunnym** [hassio-addons/addon-nginx-proxy-manager#122]
hi.
when i start the app, the message "Failed to start addon, Port '80' is already in use by something else on the host" pop up.
how to solve this?

**Comment by frenck** [comment]
Ports can only be used once. Port 80 is already in use by something else you use (I have no crystal ball, so cannot tell you what you have running on it already).

If you find out what it is that is already using your port 80, it becomes up to you to pick either one of those.

**Comment by hyunnym** [comment]
thanks.
i also understood literal meaning of that message.
but i don't know how to find out..
i'm using raspberrypi 4B and Docker now.
Could you recommend where i should check?

**Comment by frenck** [comment]
As said, I'm not familiar with your setup and don't own a crystal ball. You build that, so you know best.

This is not an issue with this add-on.
