### ISSUE TITLE
External database support

### ISSUE THREAD

**Issue by Salvora** [hassio-addons/addon-nginx-proxy-manager#124]
# Problem/Motivation

This was previously mentioned here:
 https://github.com/hassio-addons/addon-nginx-proxy-manager/issues/93?_pjax=%23js-repo-pjax-container

I would also like to suggest this feature as an optional configuration. I have a dedicated MariaDB running on TCP and I was planning to use it for this addon. Running two db instances on separate systems is not resource efficient.
## Expected behavior

> (What you expected to happen)

## Actual behavior

Not supported

## Proposed changes

Expose config.json to home assisstant supervisor configuration at least only for database and remove dependency on the compose file.
Sample:
```
{
    "database": {
      "engine": "mysql",
      "host": "127.0.0.1",
      "name": "nginx",
      "user": "nginx",
      "password": "pass",
      "port": 3307
    }
  }
```

**Comment by frenck** [comment]
See #93 for the answer as well.
