### ISSUE TITLE
Error when making a HA snapshot or HA update :  "504 Gateway Time-out"

### ISSUE THREAD

**Issue by schmurtzm** [hassio-addons/addon-nginx-proxy-manager#127]
# Problem/Motivation

Whenever I update a Generic Hassio installation, I always see this error. The update continues and is a success, so I have learn’t to ignore it, but it seems to be due to Nginx (I run" Nginx Proxy Manager" but many users has the same problem with "NGINX Home Assistant SSL proxy"). The issue has been reported [by many users here](https://community.home-assistant.io/t/504-gateway-time-out-during-update/171010).

## Expected behavior

No error message during update or snapshot.

## Actual behavior

![image](https://user-images.githubusercontent.com/7110113/99074027-53cb3000-25b7-11eb-96ce-675727fe747a.png)

## Steps to reproduce

use nginx with SSL and start a full (big) snapshot

## Proposed changes

Not sure that is really an issue, may be a configuration on home assistant or on nginx can resolve that. But sure that many users can observe this ;)

**Comment by schmurtzm** [comment]
Similar to : 
https://github.com/home-assistant/hassio-addons/issues/1371

**Comment by sinclairpaul** [comment]
The addon allows custom configuration for Nginx, if timeouts need to be adjusted, it can be done there (I believe the default is 60 seconds).

**Comment by lebherz** [comment]
Hi @sinclairpaul!

Could you specify your assumption?

I tried (with no effect):  
```
proxy_connect_timeout: 600  
proxy_send_timeout: 600
proxy_read_timeout: 600
send_timeout: 600
```

in the Proxy Manager Configuration
