### ISSUE TITLE
No log_level - huge logs

### ISSUE THREAD

**Issue by andriej** [hassio-addons/addon-nginx-proxy-manager#135]
# Problem/Motivation

Logs of totally fine working HA instance behind this proxy (or any other program) spam the log file.

## Expected behavior

Ability to set log_level

## Actual behavior

log_level option is absent and so is ignored - proper work of addon is logged and so frequent use of proxy is spamming the syslog

## Steps to reproduce

Just enter any site working behind nginx-proxy-manager and go into "Logs" in addon - a lot of data served.

## Proposed changes

Add log_level with ability to keep it more silent (i.e. info, warn, error etc.)

**Comment by frenck** [comment]
The log level option is for the add-on. Not Nginx proxy manager.

If you like additional configuration options or features for the NGinx proxy manager itself, please report your request upstream, as add-ons wrap existing software.
