### ISSUE TITLE
Can't update default site setting

### ISSUE THREAD

**Issue by Sholofly** [hassio-addons/addon-nginx-proxy-manager#14]
# Problem/Motivation

> I'm not able to update my default site setting

## Expected behavior

> When I change the default site setting and hit the submit button, I expect the change is submitted and a confirmation message in the GUI is shown

## Actual behavior

> An error dialog appears with the message: "SyntaxError: Unexpected end of JSON input"

## Steps to reproduce

> 

1. Click settings in the menu
2. Click the three dots next to the default setting line and click edit
3. Change the setting
4. Click save
(see: https://www.screencast.com/t/EbXt73ISWU0)

## Proposed changes

> None

<blockquote><img src="https://content.screencast.com/users/Sholofly548/folders/Jing/media/19ba941b-1b70-48d1-9ade-a49b312cda1a/FirstFrame.jpg" width="48" align="right"><div><img src="/favicon.ico" height="14"> Screencast.com</div><div><strong><a href="https://www.screencast.com/t/EbXt73ISWU0">2019-05-11_2312</a></strong></div><div>Shared from Screencast.com</div></blockquote>

**Comment by frenck** [comment]
Fixed in next release.

**Comment by Sholofly** [comment]
Thx for the quick action Homie!
