### ISSUE TITLE
Request: Add SSL passthrough

### ISSUE THREAD

**Issue by DrewViles** [hassio-addons/addon-nginx-proxy-manager#157]
# Motivation

Some sites may have SSL enabled directly on them, Gitlab for example, to provide a cleaner usage of the system and to prevent SSL offloading before the nodes hosting the site.

## Expected behaviour

Enable ssl passthrough

## Actual behaviour

Cannot enable SSL passthrough

## Steps to reproduce

N/A

## Proposed changes

This is more of a feature request than anything else. I've not looked through the code yet to be able to suggest a solution of any kind to this but with nginx it's a case of following this pattern: 

```
stream {
  server {
    listen     443;
    proxy_pass backend.example.com:443;
  }
}
```

thanks :-)

**Comment by frenck** [comment]
Add-ons wrap existing software, in this case, the NGinx Proxy Manager project. We don't develop the internals of that project, so please request a new feature upstream. Thanks 👍
