### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Cannot find module 'config'

### ISSUE THREAD

**Issue by jpcaldwell30** [hassio-addons/addon-nginx-proxy-manager#165]
# Problem/Motivation

App is not functioning, throws error and quits.  Unable to access admin panel with correct login info if auto start on docker container is enabled.

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

Fully functioning app, and no errors in the logs

## Actual behavior

> (What actually happened)

Unable to access admin panel with correct login info if auto start on docker container is enabled. My proxy definitions are not working (unable to access endpoints) from outside network. 

Was working fine up until recently (Not sure of exact time, but I suspect within the last week or so). I have not made any changes to config. I believe some sort of update caused the issue. One of my certificates also expired around the same time. I'm not sure if that has any significance in triggering the issue.

I receive the following error repeatedly when I try to run the addon.

[11:39:42] INFO: Starting the Manager...
(node:10669) UnhandledPromiseRejectionWarning: Error: Cannot find module 'config'
Require stack:
- /opt/nginx-proxy-manager/db.js
- /opt/nginx-proxy-manager/migrate.js
- /opt/nginx-proxy-manager/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/opt/nginx-proxy-manager/db.js:1:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:10669) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:10669) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

## Steps to reproduce

> (How can someone else make/see it happen)

Add-on version: 0.10.0, Maria DB add-on Version: 2.2.2 with default suggested config, Hassio core-2021.2.3, supervisor-2021.02.11, Docker version 20.10.1, OS: Raspbian GNU/Linux 10 (buster) running on RPI3

Run add-on.

**Comment by jpcaldwell30** [comment]
Update, I was able to semi fix it by re-installing the add-on. Now I can get to the login page and there are no errors, however I am not unable to login with my info and there doesn't seem to be any way to reset the user account.

**Comment by jpcaldwell30** [comment]
Ok, I tried a bunch of passwords, and it turns out that I did actually forget my password. I was able to get in with one of my passwords. It does bring up the suggestion that there be a way to reset the front end user/password. To recap, the solution was simply to re-install the add-on. The login issue was my own, although I think there should be a way to reset login info for the front end.

**Comment by sinclairpaul** [comment]
If you have reinstalled the addon, I would suggest resetting the Database, as you may have issues with the data (this will mean reconfiguring everything.

The reset password option would need to be logged upstream.

**Comment by jpcaldwell30** [comment]
I was able to find this link https://github.com/jlesage/docker-nginx-proxy-manager#password-reset which seems to indicate that it is at least partly possible upstream however I couldn't seem to find the script within the add-on.
