### ISSUE TITLE
Nginx doesn't resolve other Docker containers in the same network

### ISSUE THREAD

**Issue by olaxe** [hassio-addons/addon-nginx-proxy-manager#177]
# Problem/Motivation
Cannot resolve internal containers with Nginx but I can resolve them inside addon-nginx-proxy-manager

> (Why the issue was filed)
To redirect external requests directly inside docker without the need to publish ports at the host level

## Expected behavior
The Forward Hostname / IP can be an internal docker container name

> (What you expected to happen)
The resolution will done properly and the network flow will be redirected to the container

## Actual behavior
I have a 502 error from nginx. If I provide the internal IP 172.30.x.x it works fine.

> (What actually happened)
The resolution has not be done

## Steps to reproduce
Use Portainer / Docker to create a simple nginx container
In Nginx Proxy Manager, publish a new proxy host using the name of the container
Check the connection

## Proposed changes
In /etc/nginx/conf.d/include/resolvers.conf
Use 127.0.0.11 as the only DNS for IP v4. It is the default Docker DNS for the network.
This is a proposed result:
# Docker DNS
resolver 127.0.0.11 ipv6=off;

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)
With this change, all containers in the same network can be published using the Nginx Proxy Manager which is its purpose IMO

**Comment by frenck** [comment]
> Use 127.0.0.11 as the only DNS for IP v4. It is the default Docker DNS for the network.

☝️  that doesn't exist on all platforms and thus not an option.
