### ISSUE TITLE
No posibility to disable TLS1.0/TLS1.1

### ISSUE THREAD

**Issue by degraafm76** [hassio-addons/addon-nginx-proxy-manager#18]
TLS1.0 is not secure anymore. It seems there is no way to disable specific TLS versions

**Comment by sinclairpaul** [comment]
TLS1.0 hasn't been secure for a long time:) however this should have been resolved with the 0.2.0 release, where the upstream updated the template for SSL settings.  You may have to recreate the sites due to the design of the application.
