### ISSUE TITLE
Unable to log in

### ISSUE THREAD

**Issue by mstuart3** [hassio-addons/addon-nginx-proxy-manager#180]
# Problem/Motivation

Cannot login to web UI

## Expected behavior
User and password accepted

## Actual behavior

Login dialog reports "No relevant user found."
Software version is showing v0.0.0

**Comment by sinclairpaul** [comment]
Assuming you are using the default credentials listed in the documentation, have you previously setup then removed the addon?

If so you may need to reset the database (assuming you do not need the data), which is documented at:

https://github.com/hassio-addons/addon-nginx-proxy-manager/blob/main/proxy-manager/DOCS.md#option-reset_database

**Comment by mstuart3** [comment]
Oddly, I can log in using the default, but none of the configuration is present. Everything is working as normal however.

**Comment by sinclairpaul** [comment]
Then it appears something has happened to the database hosted by the MariaDB addon.  Unfortunately I doubt there is anything we can do to help, unless you can restore the DB.

**Comment by john-arvid** [comment]
Same problem here, I still have the Mariadb with the database intact.
Is there a way to recover or reset the password from either the mariadb or nginxproxymanager docker console?

**Comment by john-arvid** [comment]
Never mind, found a solution here. Managed to reset the original user and get all the config back.
[https://github.com/jc21/nginx-proxy-manager/issues/230#issuecomment-550565639](https://github.com/jc21/nginx-proxy-manager/issues/230#issuecomment-550565639)

But why did this happen?

**Comment by frenck** [comment]
That is a question we cannot answer, unfortunately.

Closing this issue as resolved for now.
