### ISSUE TITLE
Issues with DuckDNS compatibility. 

### ISSUE THREAD

**Issue by jpcaldwell30** [hassio-addons/addon-nginx-proxy-manager#181]
# Problem/Motivation

I use the DuckDNS HASS.IO addon to update and manage my certificates of my domains. I need to use the certificates generated by DuckDNS because they are automatically renewed using the DNS challenge. I have port 80 closed on my router to only allow SSL traffic for security reasons so the HTTP challenge is out of the question. I can't figure out how to get NGINX Proxy Manager to recognize the existing DuckDNS certificates.

## Expected behavior

NGINX Proxy Manager would store keys in the same location as DuckDNS add-on so that certificates auto-generated by the DuckDNS addon can be used by the NGINX addon. 

## Actual behavior

NGINX Proxy manager seems to store its certificates in a location other than the default location used by most other addons (/SSL)

## Steps to reproduce

Install DuckDNS addon and let it auto create certificates for your domains. Install NGINX Proxy Manager add-on and try using the certificates generated by DuckDNS (cant seem to be done)

## Proposed changes

Change the default certificate location to /SSL like the DuckDNS addon or add a config option to specify certificate location or add a feature into NGINX Proxy Manager to allow automatic certificate renewal of DuckDNS certificates through the DNS challenge method.

**Comment by frenck** [comment]
That is not possible and not the goal of this add-on, as NPM managed its own certificates. This add-on support DNS challenges too.
