### ISSUE TITLE
TransIp DNS Challenge

### ISSUE THREAD

**Issue by marklagendijk** [hassio-addons/addon-nginx-proxy-manager#191]
# Problem/Motivation

It is unclear how to use the TransIP DNS challenge, it asks for `certbot_dns_transip:dns_transip_key_file`, but the addon doesn't provide a means to specify the contents of the key file.

## Steps to reproduce

1. Add new proxy host.
2. Choose Request new SSL certificate, Use DNS challenge, Transip
3. The field Credentials file Content is prefilled with:
    ```
    certbot_dns_transip:dns_transip_username = my_username
    certbot_dns_transip:dns_transip_key_file = /etc/letsencrypt/transip-rsa.key
   ```

## Proposed changes

Add a addon setting to specify the contents of the key file. On container startup, the text is written to the file.

This way the issue can be fixed without having to modify the Proxy Manager itself.

**Comment by frenck** [comment]
The add-on has access to the `/ssl` folder, you can store any related key in that folder (e.g., using samba, ssh, or whatever your choice of remote file management is) and use it.
