### ISSUE TITLE
Filter out / silent nginx logs in Supervisor log

### ISSUE THREAD

**Issue by andriej** [hassio-addons/addon-nginx-proxy-manager#195]
# Problem/Motivation

"Spam" in logs with non-error paths from nginx makes it almost impossible to debug i.e. problems with recreating certificates.

## Expected behavior

Such [change ](https://github.com/hassio-addons/addon-bitwarden/commit/51e16316bbc392b383c1455676f56cf028aec9c0)as in Bitwarden RS add-on. :-)

**Comment by frenck** [comment]
The goal of this add-on is to proxy...
