### ISSUE TITLE
Issue creating SSL certificates a

### ISSUE THREAD

**Issue by riddledaxis** [hassio-addons/addon-nginx-proxy-manager#20]
# Problem/Motivation
Receive an error when creating the SSL certificate and unable to connect to proxy host via HTTPS 

## Expected behavior
Procedure should create the certificate and allow me to connect to the proxy host through SSL

> (What you expected to happen)
Certificate should be created and I could then connect to the proxy host through SSL

## Actual behavior
Receive an internal error although certificate appears to be created and the proxy host goes to offline when I enable force ssl and use the certificate

## Steps to reproduce
Same thing happens every time I try to enable HTTPS in the proxy host and ask it to create a certificate

I am forwarding port 80 & 443 to my Ubuntu server running docker.

<img width="387" alt="server info" src="https://user-images.githubusercontent.com/47009467/59161984-6a777880-8ae1-11e9-94d6-e8f2e14391bd.PNG">

I have attached screen shots of the error, the proxy manager and the add-on logs in home assistant

Any help you can offer will be greatly appreciated

Thanks

Paul

<img width="736" alt="Addon logs" src="https://user-images.githubusercontent.com/47009467/59161934-c988bd80-8ae0-11e9-888d-39c13c8d442b.PNG">
<img width="734" alt="proxy hosts" src="https://user-images.githubusercontent.com/47009467/59161935-c988bd80-8ae0-11e9-9023-be4ff26263de.PNG">
<img width="380" alt="SSL cert error from addon" src="https://user-images.githubusercontent.com/47009467/59161936-c988bd80-8ae0-11e9-9e2a-543e6ed75335.PNG">
<img width="738" alt="SSL certificates" src="https://user-images.githubusercontent.com/47009467/59161937-c988bd80-8ae0-11e9-9422-eb19ebcd119f.PNG">

**Comment by sinclairpaul** [comment]
Your destination should be http, which is likely why it shows offline.

**Comment by riddledaxis** [comment]
I have double checked the port forwarding from work today and I can access my server on port 80, so I believe the port forwarding is working.

I tried recreating the SSL certificate again, following the steps in the animation that @frenck created,  and I always get the internal error come up.

Do I need to manually create and permission this directory (/etc/letsencrypt/live/npm-7/) as the letsencrypt/live/npm-7 folders do not exist and the logs keep repeating this error? 

[6/10/2019] [6:59:02 PM] [SSL      ] › ✖  error     Certificate is not valid (Command failed: openssl x509 -in /etc/letsencrypt/live/npm-7/fullchain.pem -subject -noout
Can't open /etc/letsencrypt/live/npm-7/fullchain.pem for reading, No such file or directory
140346278599528:error:02001002:system library:fopen:No such file or directory:crypto/bio/bss_file.c:72:fopen('/etc/letsencrypt/live/npm-7/fullchain.pem','r')

**Comment by sinclairpaul** [comment]
Is the url you linked earlier in the thread the one you are using?  If so it looks like you are forwarding 80 to 8123 (as Home Assistant responds).  You need to forward 80 to 80 and 443 to 443 so the Proxy Manager receives the data.

**Comment by riddledaxis** [comment]
I am only forwarding 2 ports from my router to my server, 80 & 443.

When I created my proxy host in the nginx proxy manager, I followed @frenck’s example and I input my domain, my ip and forward port 8123 which is what he did. This is the only place I have forwarded port 8123

**Comment by sinclairpaul** [comment]
Apologies, its probably the Proxy Manager forwarding then as it is responding and forwarding on http (you may want to disable it until you can get the certificate fixed).  It looks like the server thinks it has requested a cert, did you delete and try again.  You may want to jump onto Discord to help to troubleshoot.

**Comment by riddledaxis** [comment]
No problem. I have fixed the issue. 

I'm not sure if it should have been automatically created but as soon as I created the directory /etc/letsencrypt/live/npm-7 and used chmod to permission it to 700 I was able to create the certificate and can now access my HA instance through SSL &#128512;

**Comment by sinclairpaul** [comment]
Glad its resolved, that shouldn't have been necessary though, will close for now.
