### ISSUE TITLE
Can't add Proxy Host

### ISSUE THREAD

**Issue by tms320** [hassio-addons/addon-nginx-proxy-manager#204]
Hello!
I have installed Nginx Proxy Manager addon (v.0.10.1) to my Home Assistant Supervised (version 2021.4.6).
Trying to create new Proxy Host:
![image](https://user-images.githubusercontent.com/24802646/116187181-b95a4580-a72d-11eb-956c-07b6105868fa.png)
But when the 'Domain Names' field loses input focus (for example when I press 'Save' button) it's content is cleared and I get error 'Fill this field':
![image](https://user-images.githubusercontent.com/24802646/116187306-f7f00000-a72d-11eb-93bf-650301e8d1c5.png)
What am I doing wrong?
PS: MariaDB addon installed and running. By the way: when I installed MariaDB I set password in it's configuration. Should I enter this password somewhere for 'Nginx Proxy Manager' (I didn't find any password option)?
Thanks.

**Comment by frenck** [comment]
![image](https://user-images.githubusercontent.com/195327/116278284-a4f66700-a786-11eb-8f5c-9db901596365.png)
