### ISSUE TITLE
Proxy host and Adguard home not resolving

### ISSUE THREAD

**Issue by ThumNet** [hassio-addons/addon-nginx-proxy-manager#209]
# Problem/Motivation

Hi, I' trying to use Nginx Proxy Manager to configure a Proxy host. 

My goal is to have a nice domain name (http://mysite.local) for a container that is running in Portainer and is exposed on port 8080.

I'm able to view the site when using http://homeassistant.local:8080.

Within Nginx Proxy Manager I configured a new proxy, like shown below.
<img width="501" alt="Screenshot 2021-05-06 at 14 28 04" src="https://user-images.githubusercontent.com/692308/117298128-4bbdc000-ae77-11eb-8331-b43f961e20d4.png">
I also tried using the Hassio IP address instead of the hostname.

Next to Nginx Proxy Manager, I'm also running the AdGuard Home addon. Which serves as my DNS server.

Do I need to let AdGuard Home know of Nginx somehow? If so, how?
Is this the correct approach?
What am I missing, any help is welcome.

## Expected behavior

http://mysite.local shows the site hosted in the docker container

## Actual behavior

When requesting http://mysite.local nothing is resolved in my browser :(

**Comment by frenck** [comment]
Use `homeassistant` as the host when connecting to Home Assistant.

**Comment by ThumNet** [comment]
Thank you for the quick response, but using `homeassistant` as the host doesn't help, any other tips?

**Comment by frenck** [comment]
`homeassistant` works, see the animation on the documentation page as well.

**Comment by ThumNet** [comment]
I figured it out, the domain I'm requesting needs to be in Adguard Custom filtering list

[homeassistantip] mysite.local

Now it works

**Comment by frenck** [comment]
That sounds incorrect, this doesn't rely on AdGuard. If it does, you have some serious network configuration issues in general.

**Comment by ThumNet** [comment]
Learned something new again, didn't know about .local and mDNS

The mysite.local was only working on a Windows PC, not on my MacBook.

Now using mysite.home as the domain name, which works on both devices.
