### ISSUE TITLE
Cannot add more than 4 IPs in access list

### ISSUE THREAD

**Issue by avee87** [hassio-addons/addon-nginx-proxy-manager#214]
Currently, as in NPM 2.8.1, Access List UI is limited to 4 addresses. This is not enough, for example, to use the [list of Cloudflare IPs](https://www.cloudflare.com/ips/).
This issue was fixed in https://github.com/jc21/nginx-proxy-manager/pull/975 and in latest version of NPM but addon still uses 2.8.1
Would it be possible to update NPM version in the addon to include that fix?

**Comment by frenck** [comment]
This upgrade require a larger refactor, as upstream moves from Alpine to Debian Linux. Thus it takes longer than usual. Sorry.
