### ISSUE TITLE
DuckDNS + NGINX not working

### ISSUE THREAD

**Issue by GiulioFattoretto** [hassio-addons/addon-nginx-proxy-manager#219]
# Problem

I'm using DuckDNS and NGNINX to access from away.
I configure Duck DNS as follow:

lets_encrypt:
  accept_terms: true
  certfile: fullchain.pem
  keyfile: privkey.pem
token: xxxxxxxx-xxxx-xxxx-xxxx-e5477482e3bd //my token 
domains:
  - myhome.duckdns.org //my duckDNS domain
aliases: []
seconds: 300

and NGINX as follow:

domain: myhome.duckdns.org //my duckDNS domain
certfile: fullchain.pem
keyfile: privkey.pem
hsts: max-age=31536000; includeSubDomains
cloudflare: false
customize:
  active: false
  default: nginx_proxy_default*.conf
  servers: nginx_proxy/*.conf

on file configuration.yaml the settings are:

http:
  base_url: https://myhome.duckdns.org 
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  
duckdns:
  domain: myhome.duckdns.org //my duckDNS domain
  access_token: xxxxxxxx-xxxx-xxxx-xxxx-e5477482e3bd //my token 

and on Settings > General:
External URL: myhome.duckdns.org:8123
Internal URL: http://192.168.X.XXX:8123

Furthermore in the Vodafone Station I insert the forwarding rule:

192.168.X.XXX
External Port: 443
Internal Port: 8123

Where is the error? I can't access from external
<img width="623" alt="Schermata 2021-05-23 alle 19 23 55" src="https://user-images.githubusercontent.com/78276738/119270383-bd7a6580-bbfc-11eb-9106-98a9360bf6a9.png">
![Schermata 2021-05-23 alle 19 21 14](https://user-images.githubusercontent.com/78276738/119270388-beab9280-bbfc-11eb-8c66-c0e330ec0a5b.png)
<img width="1020" alt="Schermata 2021-05-23 alle 19 22 25" src="https://user-images.githubusercontent.com/78276738/119270390-bf442900-bbfc-11eb-940b-95db9a1d72ec.png">
<img width="595" alt="Schermata 2021-05-23 alle 19 25 31" src="https://user-images.githubusercontent.com/78276738/119270391-bfdcbf80-bbfc-11eb-9993-b4c820626464.png">
<img width="1051" alt="Schermata 2021-05-23 alle 19 23 10" src="https://user-images.githubusercontent.com/78276738/119270396-c2d7b000-bbfc-11eb-9f60-7afd8e6d6760.png">

**Comment by sinclairpaul** [comment]
This is the repo for the Nginx Proxy Manager, not the core Nginx/Duckdns addons.

I would suggest you look for help on the HA discord/forums.

You could also use this addon if you want a GUI to manage it for you.
