### ISSUE TITLE
TypeError on LetsEncrypt certificate generation for Netcup

### ISSUE THREAD

**Issue by tbhsm** [hassio-addons/addon-nginx-proxy-manager#221]
# Problem/Motivation
My certificate autorenewal was not working and so I tried to do it manually. However, I am now getting a TypeError. I have tried:

- Reinstalling Nginx Proxy Manager and MariaDB. 
- Resetting the database. 
- Resetting my API credentials.
- Using a different URL.
- Removed any remnants of previous certificates in /ssl/nginxproxymanager/.

All result in the same error below.

## Expected behavior
A LetsEncrypt certificate to be generated.

## Actual behavior

After a minute or so, I get the following error:

```
Error: Command failed: /usr/bin/certbot certonly --non-interactive --cert-name "npm-5" --agree-tos --email "......@......." --domains "................." --authenticator certbot-dns-netcup:dns-netcup --certbot-dns-netcup:dns-netcup-credentials "/etc/letsencrypt/credentials/credentials-5" --certbot-dns-netcup:dns-netcup-propagation-seconds 500
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugin legacy name certbot-dns-netcup:dns-netcup may be removed in a future version. Please use dns-netcup instead.
Plugins selected: Authenticator certbot-dns-netcup:dns-netcup, Installer None
Performing the following challenges:
dns-01 challenge for .................
Cleaning up challenges
Encountered exception during recovery: TypeError: delete_record() got an unexpected keyword argument 'type'
An unexpected error occurred:
TypeError: create_record() got an unexpected keyword argument 'type'
Please see the logfiles in /var/log/letsencrypt for more details.

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
```

I tried to find the log it is referring to but I could not find it.

## Steps to reproduce

Every time I attempt to create a LetsEncrypt certificate via DNS Challenge, I get this error. I format the credential file content as follows:
certbot_dns_netcup:dns_netcup_customer_id  = <customerid>
certbot_dns_netcup:dns_netcup_api_key = <apikey>
certbot_dns_netcup:dns_netcup_api_password = <apipassword>

## Proposed changes
No working solution as of yet.

**Comment by tbhsm** [comment]
Was unable to solve this by means of this add-on. Switched to the Let's Encrypt add-on + NGINX Home Assistant SSL proxy add-on. It misses some functionality but it's more light-weight. Win some, lose some :)

**Comment by MrSleeps** [comment]
> Was unable to solve this by means of this add-on. Switched to the Let's Encrypt add-on + NGINX Home Assistant SSL proxy add-on. It misses some functionality but it's more light-weight. Win some, lose some :)

Check out: https://github.com/jc21/nginx-proxy-manager/issues/1119#issuecomment-850954344

That fixed the issue for me.
