### ISSUE TITLE
Fix Documentation ? :  Trustet Proxy in configuration.yaml when this addon is used in HA 2021.7

### ISSUE THREAD

**Issue by Delta1977** [hassio-addons/addon-nginx-proxy-manager#228]
WARNING (MainThread) [homeassistant.components.http.forwarded] A request from a reverse proxy was received from 172.30.33.3, but your HTTP integration is not set-up for reverse proxies; This request will be blocked in Home Assistant 2021.7 unless you configure your HTTP integration to allow this header

To resolve the Warning this Parameter must be added to Configuration.yaml:
 http:
  use_x_forwarded_for: true
  trusted_proxies:

The Addon should set this Parameter in 2021.7 or the Documentation must be adjusted

**Comment by frenck** [comment]
Neither of those.
This add-on provides a reverse proxy. The application you use it with, might need additional configuration.

This is not new in 2021.7, if you get this warning, it means you have been using it wrongly all the time already.

**Comment by tboyce021** [comment]
Were you able to resolve this? I'm running into the same issue as well.

**Comment by doosterkamp** [comment]
> This is not new in 2021.7, if you get this warning, it means you have been using it wrongly all the time already.

Then please add some suggestions on how to fix this to thew setup steps.
I've installed this addon 1-on-1 as described, resulting in the warning(s) mentioned above

**Comment by scottyphillips** [comment]
Ive got the exact same issue with a clean slate HA install 2021.6.3 running 'official' NGNIX and DuckDNS add ons...
Since the http: yaml configuration is supposed to get removed soon it would be nice to know what the proper solution is supposed to be...

**Comment by PrplHaz4** [comment]
Here's the config that seems to have fixed it for my docker/traefik setup.  You'll need to make sure the 172 subnet maps to the docker network your hass container is running on.  Not sure if the loopback needs to be on there, but figured it couldn't hurt, and didn't have to time to figure out what (if anything) breaks without it.

```
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - 172.18.0.0/16
```
