### ISSUE TITLE
Support for LetsEncrypt DNS-Chellenge for DuckDNS in v2.9.3

### ISSUE THREAD

**Issue by stefangries** [hassio-addons/addon-nginx-proxy-manager#230]
# Problem/Motivation

The newest version of the [Nginx Proxy Manager](https://github.com/jc21/nginx-proxy-manager/releases/tag/v2.9.3) supports the LetsEncrypt DNS challenge for DuckDNS. Ich would like to use it.

# Proposed changes

The addon needs to be updated. However, I noticed that someone has already tried this (https://github.com/hassio-addons/addon-nginx-proxy-manager/pull/216).

Since NGINX Proxy Manager is no longer based on Alpine, but on Debian, and the developers also state that it can no longer run on Alpine (https://github.com/jc21/nginx-proxy-manager/releases/tag/v2.9.0), I don't know how to proceed, since the Home Assistant addon base image (https://github.com/hassio-addons/addon-base/blob/main/base/Dockerfile) is based on Alpine.

If someone has an idea how to implement an update for this case, I would be very grateful.

**Comment by frenck** [comment]
We know, this is not an issue but a request, hence closing the issue.

**Comment by stefangries** [comment]
My intention wasn't requesting to update it, but on dicussing, how an update could be implemented. And of course I would contribute to that, not just ask others to do it. I just don't know how the mentioned problem is solvable.
