### ISSUE TITLE
Reverse Proxy error in Home Assistant

### ISSUE THREAD

**Issue by Icexist** [hassio-addons/addon-nginx-proxy-manager#232]
# Problem/Motivation

> Error appearing in Home Assistant due to reverse proxy:

> A request from a reverse proxy was received from 172.30.33.4, but your HTTP integration is not set-up for reverse proxies; This request will be blocked in Home Assistant 2021.7 unless you configure your HTTP integration to allow this header

## Steps to reproduce

> Don't configure the `use_x_trusted_header` in the `http:` integration in Home Assistant.

## Proposed changes

PR #231

**Comment by Icexist** [comment]
Closing since documentation should be in proxied application.

**Comment by gitolicious** [comment]
Well, it would have saved me from some fearsome minutes where I was unable to connect to my HA instance after upgrading to HA Core 2021.7... The general topic is documented in the "[Breaking Changes](https://www.home-assistant.io/blog/2021/07/07/release-20217/#breaking-changes)" section, but a clear documentation what values need to be set when using this addon would have helped reducing downtime on my instance.

> Home Assistant will now block HTTP requests when a misconfigured reverse proxy, or misconfigured Home Assistant instance when using a reverse proxy, has been detected.
>
> If you are using a reverse proxy, please make sure you have configured use_x_forwarded_for and trusted_proxies in your HTTP integration configuration.
