### ISSUE TITLE
Snapshot restore not working correctly

### ISSUE THREAD

**Issue by joshtbernstein** [hassio-addons/addon-nginx-proxy-manager#234]
# Problem/Motivation

I moved my Home Assistant install to a new VM and restored from a snapshot (excluding MariaDB as it was large). While all of my proxy hosts that were previously configured are working, my account and anything in the UI aren't. I had to create a new account and when I login there is nothing configured (even thought everything is working). It seems like the UI is disconnected from the configuration.

## Expected behavior

Snapshot of addin would backup and restore the complete addin.

## Actual behavior

Something didn't restore properly.

## Steps to reproduce

Backup just the addin and restore to a fresh system.

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by sinclairpaul** [comment]
The addon uses MariaDB to store parts of the configuration:

https://github.com/hassio-addons/addon-nginx-proxy-manager/blob/main/proxy-manager/DOCS.md#known-issues-and-limitations
