### ISSUE TITLE
Addings a custom SSL certificate

### ISSUE THREAD

**Issue by engrbm87** [hassio-addons/addon-nginx-proxy-manager#25]
# Problem/Motivation

> I want to use nginx but with my own domain and SSL certificates. the only option available is to use Let's Encrypt to generate the certificate.

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes
Enable the option to manually add SSL certificates.
> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
You can upload your own certificates from the SSL management part of the add-on.
