### ISSUE TITLE
Suddenly can not open WEB UI 

### ISSUE THREAD

**Issue by tompatulpan** [hassio-addons/addon-nginx-proxy-manager#250]
# Problem/Motivation
Web UI cant be opened

## Expected behavior
Worked just fine a "last time" I used it...

## Actual behavior
Get "This site can’t be reached"

## Steps to reproduce
Open from link in HA or separate address (the same in different browsers)
Also tried with different ports

Tied to go back to Maria DB 2.2.2 as this was one of my updates thta might have changed anything, but no.

Very strange, any ideas?

**Comment by frenck** [comment]
Anything in the lgos?

**Comment by tompatulpan** [comment]
Hi,
Not sure but this is what I find, please guide me if we need something else.

## System Health

version | core-2021.7.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.9.5
os_name | Linux
os_version | 5.10.17-v7l
arch | armv7l
timezone | Europe/Stockholm

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 5000
Installed Version | 1.11.3
Stage | startup
Available Repositories | 776
Installed Repositories | 2

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.1
-- | --
update_channel | stable
supervisor_version | supervisor-2021.06.8
docker_version | 20.10.6
disk_total | 28.6 GB
disk_used | 7.5 GB
healthy | true
supported | true
board | rpi4
supervisor_api | ok
version_api | ok
installed_addons | MariaDB (2.2.2), Nginx Proxy Manager (0.11.0), File editor (5.3.1), WireGuard (0.5.1), Terminal & SSH (9.1.3), TasmoAdmin (0.15.0), Mosquitto broker (6.0.1), AdGuard Home (4.1.6), ZeroTier One (0.11.1)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 0
views | 1
mode | storage

</details>

`[15:10:36] INFO: Starting NGinx...
nginx: [emerg] cannot load certificate "/etc/letsencrypt/live/npm-4/fullchain.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/npm-4/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)`

**Comment by frenck** [comment]
> [15:10:36] INFO: Starting NGinx... nginx: [emerg] cannot load certificate "/etc/letsencrypt/live/npm-4/fullchain.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/npm-4/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)

It seems to miss a file from the file system. Maybe you are dealing with file corruption? Something happened there.

**Comment by tompatulpan** [comment]
ok, so do you propose a full reinstall and reload snapshot?

**Comment by frenck** [comment]
I'm not sure why you'd need a full re-install?

Restoring a snapshot might work. Please note that requires the mariadb and this add-on to be in sync.

**Comment by tompatulpan** [comment]
solved - installed a full snapshot from June
