### ISSUE TITLE
HassIO Snapshot restore fail

### ISSUE THREAD

**Issue by DMIllsUK** [hassio-addons/addon-nginx-proxy-manager#26]
**When restoring a snapshot this addon always fails to restore.**

When it fails the error is logged as follows 
19-07-05 21:21:27 ERROR (MainThread) [hassio.addons.addon] Can't restore origin data: [('/data/tmp/tmp7srk635q/data/logs/default.log', '/data/addons/data/a0d7b954_nginxproxymanager/logs/default.log', '`/data/tmp/tmp7srk635q/data/logs/default.log` is a named pipe'), ('/data/tmp/tmp7srk635q/data/logs/letsencrypt-requests.log', '/data/addons/data/a0d7b954_nginxproxymanager/logs/letsencrypt-requests.log', '`/data/tmp/tmp7srk635q/data/logs/letsencrypt-requests.log` is a named pipe'), ('/data/tmp/tmp7srk635q/data/logs/manager.log', '/data/addons/data/a0d7b954_nginxproxymanager/logs/manager.log', '`/data/tmp/tmp7srk635q/data/logs/manager.log` is a named pipe')]
19-07-05 21:21:28 ERROR (MainThread) [hassio.snapshots.snapshot] Can't restore snapshot for a0d7b954_nginxproxymanager

**Setup addon; then restore the backup on another device.**

**Comment by sinclairpaul** [comment]
As a workaround are you able to delete the logs folder from the tar before you restore?

**Comment by rtenklooster** [comment]
Same problem here. Just did a fresh install, restored a recent backup.
the unifi controller and proxy manager won't restrore:
`19-09-04 20:59:47 ERROR (MainThread) [hassio.addons.addon] Can't restore origin data: [('/data/tmp/tmpvrm1k6gm/data/logs/default.log', '/data/addons/data/a0d7b954_nginxproxymanager/logs/default.log', '`/data/tmp/tmpvrm1k6gm/data/logs/default.log` is a named pipe'), ('/data/tmp/tmpvrm1k6gm/data/logs/letsencrypt-requests.log', '/data/addons/data/a0d7b954_nginxproxymanager/logs/letsencrypt-requests.log', '`/data/tmp/tmpvrm1k6gm/data/logs/letsencrypt-requests.log` is a named pipe'), ('/data/tmp/tmpvrm1k6gm/data/logs/manager.log', '/data/addons/data/a0d7b954_nginxproxymanager/logs/manager.log', '`/data/tmp/tmpvrm1k6gm/data/logs/manager.log` is a named pipe')]
19-09-04 20:59:47 ERROR (MainThread) [hassio.snapshots.snapshot] Can't restore snapshot for a0d7b954_nginxproxymanager
19-09-04 20:59:47 ERROR (MainThread) [hassio.addons.addon] Can't restore origin data: [('/data/tmp/tmpgpar3hkh/data/unifi/data/backup', '/data/addons/data/a0d7b954_unifi/unifi/data/backup', "[Errno 2] No such file or directory: '/data/tmp/tmpgpar3hkh/data/unifi/data/backup'")]
19-09-04 20:59:47 ERROR (MainThread) [hassio.snapshots.snapshot] Can't restore snapshot for a0d7b954_unifi`
