### ISSUE TITLE
Port 80 workaround for let's encrypt?

### ISSUE THREAD

**Issue by nardev** [hassio-addons/addon-nginx-proxy-manager#28]
Since so many providers block port 80, maybe it would be nice to have option for manual cert create or at least easy cert upload option.

My provider blocks only port 80, 443 is free to use so, this add-on would be handy if I was able to generate cert locally and just install it and use it.

Selfsigned is also ok in some situations. 

Thnx

**Comment by frenck** [comment]
You can upload a certificate manually. This is under the admin interface -> SSL certificate tab, you can upload one there.
