### ISSUE TITLE
Is this addon safe to use anymore?

### ISSUE THREAD

**Issue by hs6666** [hassio-addons/addon-nginx-proxy-manager#287]
# Problem/Motivation

> No recent updates and some of the issues open are worrying?

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

Remove from homeassistant and use a docker image like  ..... https://github.com/jlesage/docker-nginx-proxy-manager

**Comment by hs6666** [comment]
still no update, **def** remove this addon from your HA folks, I personally did and ran this guys excellent script to install alternative elsewhere...  https://shownotes.opensourceisawesome.com/install-4-apps-in-under-5-min/

**Comment by frenck** [comment]
? Are you OK @hs6666?

There have been answers a couple of time, including recent activity. This add-on is safe, I have not received other indications at this point.

The above-recommended approaches are not supported by the Home Assistant project, as running additional software manually will render your system unsupported.

Anyways, feel free to help out moving the this project forward, it is open source and PRs doing the larger migration is welcome.
