### ISSUE TITLE
SSL Certificates won't auto-renew and clicking "renew" results in timeout

### ISSUE THREAD

**Issue by CyaOnDaNet** [hassio-addons/addon-nginx-proxy-manager#30]
# Problem/Motivation

> My SSL Certificates are expiring and they won't auto-renew. Manually clicking "renew" results in timeout

## Expected behavior

> I expected the ssl certificates to renew when the button is clicked. 

## Actual behavior

> What actually happened was a timeout error

## Steps to reproduce

> Just clicking the renew button

![image](https://user-images.githubusercontent.com/22354631/62340520-dbb62500-b4ad-11e9-91a7-b66c5bcd9920.png)

**Comment by aferraz** [comment]
Hi,
 same for me

**Comment by jlallen75** [comment]
Timing out for me now as well

**Comment by Widda** [comment]
Hi!
I had the same problem but i also have Pi-Hole add-on. If i stoped Pi-Hole i could renew the SSLs.
Hope this can help you other that have the same problem and maybe help to resolve this issue.

**Comment by Klagio** [comment]
Hi, I have exactly the same situation, but stopping pi-hole did not help. Also uninstalling and reinstalling did not help

**Comment by Widda** [comment]
Regarding my fault “no IP address” was a dns problem. After solving that the renewal works
