### ISSUE TITLE
I get 3 ssdp packets, 2 with wrong network.

### ISSUE THREAD

**Issue by perseus177** [hassio-addons/addon-nginx-proxy-manager#300]
# Problem/Motivation
I am using Ngnix  Proxy manager which is maybe causing problem in Samsung TV integration.
https://github.com/home-assistant/core/issues/57310

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

>I get 3 ssdp packets, 2 with wrong network.
https://github.com/home-assistant/core/issues/57310#issuecomment-958235095

## Steps to reproduce

> Steps and logs are in linked ticket 
https://github.com/home-assistant/core/issues/57310

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

## Current version:
<html><body>

Version HA | core-2021.9.7
-- | --
Nginx Proxy Manager|0.11.0
Installation Type | Home Assistant Supervised
Development | false
Supervisor | true
Docker | true
User | root
Virtual Environment | false
Python Version | 3.9.7
Operating System Family | Linux
Operating System Version | 5.10.17-v7l+
CPU Architecture | armv7l
Timezone | Europe/Prague

</body>
</html>

**Comment by frenck** [comment]
This is not an add-on issue, but a networking issue on your end.
