### ISSUE TITLE
400 Bad Request when navigating to HA from domain

### ISSUE THREAD

**Issue by crhistianramirez** [hassio-addons/addon-nginx-proxy-manager#303]
# Problem/Motivation
If I try to load HA from the external domain I see a page that says "400 Bad Request". I am able to load HA from {MY_IP_ADDRESS}:8123 just fine so it seems to be working locally. I've also used [port checker](https://portchecker.co) to confirm that port 80 and 443 are being forwarded.

## Expected behavior
I'd expect HA UI to appear when I enter my custom domain

## Actual behavior
I see a 400 bad request on the screen

## Steps to reproduce
I followed the set up instructions to a tee. I'm running home assistant OS on a Mac. Relevant log with sensitive information redacted:
>[30/Nov/2021:23:11:39 -0600] - 400 400 - GET https **{MY_SUBDOMAIN}**.duckdns.org "/favicon.ico" [Client 174.243.80.54] [Length 16] [Gzip -] [Sent-to **{MY_HA_IP_ADDRESS}**] "Mozilla/5.0 (Linux; Android 9; SM-G950U) AppleWebKit/537.36

**Comment by sinclairpaul** [comment]
I would suggest checking the logs and documentation for the application you are proxying to, in this case https://www.home-assistant.io/integrations/http/#use_x_forwarded_for

**Comment by MTrab** [comment]
+1 for this

**Comment by sinclairpaul** [comment]
Closing, no response and most likely an HA config issue.
