### ISSUE TITLE
Cannot Configure Ports for Secure DNS

### ISSUE THREAD

**Issue by brodkin** [hassio-addons/addon-nginx-proxy-manager#307]
# Problem/Motivation

Trying to configure DNS over HTTPS/TLS/QUIC.

## Expected behavior

Configuration tab would make ports configurable.

## Actual behavior

Only ports 53 and 80 are configurable.

## Steps to reproduce

Try to configure additional ports.

## Proposed changes

Add ports 443, 853, and 784 to configuration.

**Comment by frenck** [comment]
I think this issue is in the wrong place. Port 53 = DNS, which is not related to this add-on at all?

Closing it for that reason.
