### ISSUE TITLE
Providing fullchain key and private key in /etc/ssl/

### ISSUE THREAD

**Issue by alve89** [hassio-addons/addon-nginx-proxy-manager#312]
# Problem/Motivation

Quite a lot of apps require SSL keys in the `/etc/ssl/` directory. The path is often not changable.

## Expected behavior
SSL keys of this add-on are stored in `/etc/ssl/`.

## Actual behavior
As I understand this add-on, all keys are stored in `/etc/nginxproxymanager/keys/`
![image](https://user-images.githubusercontent.com/11487054/148790654-19e723ec-a174-42d6-8208-fb564576199e.png)

Which one would be the correct ones to use for these fields?

![image](https://user-images.githubusercontent.com/11487054/148792468-0aa422dd-29d5-4013-8d54-28c161bd4d16.png)

## Proposed changes

Either: Syslinking the correct keys for `fullchain key` and `private key` to `/etc/ssl/` (if possible) or coying them after every key-refresh so `/etc/ssl/`.

**Comment by frenck** [comment]
> Quite a lot of apps require SSL keys in the /etc/ssl/ directory. The path is often not changeable.

That is not a path available in our ecosystem (in general, not related to this add-on).

The certs are stored internally in this add-on and not for use outside of the add-on. If you are in need of that, this add-on is not a solution for you.
