### ISSUE TITLE
Addon won't start if hassio_supervisor is down

### ISSUE THREAD

**Issue by CountParadox** [hassio-addons/addon-nginx-proxy-manager#32]
# Problem/Motivation

The addon will fail to start if the hassio_supervisor container is not reachable.
as a result anything proxied by the addon (such as home assistant) cannot be reached, but may still be running. 
in my case, i can access home assistant locally by https://ip:port/ but not through my domain as the addon normally handles that.

`
[s6-finish] sending all processes the TERM signal.,
[s6-finish] waiting for services.,
[cont-finish.d] 99-message.sh: exited 0.,
[cont-finish.d] done.,
 Be sure to check the log above, line by line, for hints.,
 starting or running this add-on.,
 We are so sorry, but something went terribly wrong when,
                Oops! Something went wrong.,
[cont-finish.d] 99-message.sh: executing... ,,
-----------------------------------------------------------,
 ,
[cont-init.d] npm.sh: exited 1.,
[cont-finish.d] executing container finish scripts...,
ln: /var/tmp/nginx/nginx: File exists,
[cont-init.d] npm.sh: executing... ,
[cont-init.d] mysql.sh: executing... ,
[cont-init.d] mysql.sh: exited 0.,
[fix-attrs.d] done.,
[cont-init.d] 00-banner.sh: exited 0.,
[cont-init.d] 01-log-level.sh: executing... ,
[cont-init.d] 01-log-level.sh: exited 0.,
[12:53:00] ERROR: Something went wrong contacting the API,
[cont-init.d] 00-banner.sh: executing... ,
[cont-init.d] executing container initialization scripts...,
[fix-attrs.d] permissions: exited 0.,
[fix-attrs.d] permissions: applying... ,
[fix-attrs.d] applying ownership & permissions fixes...,
[s6-init] ensuring user provided files have correct perms...exited 0.,
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.,
curl: (7) Failed to connect to hassio port 80: Host is unreachable,
curl: (7) Failed to connect to hassio port 80: Connection refused,
[12:49:41] ERROR: Something went wrong contacting the API,
[12:39:21] ERROR: Something went wrong contacting the API,[cont-finish.d] 99-message.sh: exited 0.`

## Expected behavior

I would expect this to work regardless of the hassio_supervisor container, as it doesnt NEED it to function.

## Actual behavior

An error is presented during addon startup and it shuts down the container.

## Steps to reproduce

1. manually stop your hassio_supervisor (or in my case, its just stopping on its own and i dont know why yet)
2. restart the addon

## Proposed changes

Remove the dependency for the connection to be established for the container to start, while I can see its uses, its not a necessity as far as I can tell.
Many other addons are able to run fine while hassio is down, this one is one I feel is more important to have running.

**Comment by frenck** [comment]
The Hass.io supervisor is the manager of the Hass.io system.
Without the supervisor, you can't start an add-on.

There is no point to this. Futhermore, the add-on relies on information that cannot make up from thin air, it needs information from the supervisor to work.

Closing issue.
