### ISSUE TITLE
Internal IP changed, can't connect to HA from internal network

### ISSUE THREAD

**Issue by edwardcc83** [hassio-addons/addon-nginx-proxy-manager#325]
# Problem/Motivation
So I switched to a new router provided by my Telecom service and the IP range changed from 192.168.0.x to 192.168.1.x

I took the time to update all the necessary IP values, and added the port forwarding for 443 an 80 to my HA and Nginx device. When all is said and done, I can connect to HA via internal IP on port 8123 and via externally via xyz.ddns.net. However, when I try xyz.ddns.net from my internal network, it doesn't work.

Is this a router issue?  Or something in nginx I missed to update?

(BTW, this worked fine on my old router setup)

**Comment by sinclairpaul** [comment]
It's likely as your new router doesn't support hairpin NAT and the old one did.

As this isn't an issue with the addon, I would suggest seeking configuration help on Discord or the forums.
