### ISSUE TITLE
After updating HA Core to 2022.3.8, when signing on only receive "400 Bad Request"

### ISSUE THREAD

**Issue by TurboKid** [hassio-addons/addon-nginx-proxy-manager#328]
# Problem/Motivation

> I can no longer use my duckdns domain to sign on to my Home Assistant outside of my home network.

## Expected behavior

> When I first configured my proxy I was able to sign on to my HA from anywhere inside my own network and outside

## Actual behavior

> I can only sign on with the local IP of my Raspberry Pi hosting my Home Assistant

## Steps to reproduce

> I am not sure what steps one would take to reproduce this issue, however this is the only log entry I see when attempting to connect via the proxy:

[09/Apr/2022:18:07:34 -0700] - 400 400 - GET https joesapartment.duckdns.org "/auth/authorize?response_type=code&client_id=https://home-assistant.io/iOS&redirect_uri=homeassistant://auth-callback" [Client 192.168.1.1] [Length 16] [Gzip -] [Sent-to 192.168.1.240] "Home%20Assistant/2022.358 CFNetwork/1329 Darwin/21.3.0" "-"

## Proposed changes

> No proposed changes, just would like to understand what steps to take in order to get my proxy functioning again.

**Comment by alejandrofan2** [comment]
I have the same problem, in the DNS Provider List of the DNS Challenge does not appear DuckDNS.
Installed with Supervisor.

**Comment by NeskireDK** [comment]
Yup, i've been scratching my head over this for quite a while now. My logs look the same as @TurboKid.

**Comment by alejandrofan2** [comment]
> Yup, i've been scratching my head over this for quite a while now. The fix is as follows.
> 
> _"...you need to add the trusted_proxies section (requests from reverse proxies will be blocked if these options are not set). "_ Add the following in your configuration.yaml
> 
> ```
> http:
>   use_x_forwarded_for: true
>   trusted_proxies:
>     - 172.30.33.0/24
> ```
> 
> https://github.com/home-assistant/addons/blob/master/nginx_proxy/DOCS.md https://community.home-assistant.io/t/reverse-proxy-error/312936?page=2

Yeah, that's working

**Comment by kds69** [comment]
Is this really valid for ngninx-proxy-manager add-on?? or more simple ngnix add-on...

**Comment by TurboKid** [comment]
Below is my config for http: 

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - 192.168.1.240
    - 192.168.1.0/24

I still see a 400 Bad Request error after rebooting host.

**Comment by frenck** [comment]
This is not an add-on issue. Closing it for that reason.
