### ISSUE TITLE
Streams not available

### ISSUE THREAD

**Issue by mxwi** [hassio-addons/addon-nginx-proxy-manager#340]
# Problem/Motivation

> In the current nginx-proxy-manager version "TCP/UDP Streams" should be available". Why are they not? I guess it is on purpose?

## Expected behavior

> TCP/UDP Streams are available

## Actual behavior

> TCP/UDP Streams are not available

## Steps to reproduce

> Install current version

## Proposed changes

> make Streams available

**Comment by poida97** [comment]
Latest version does not solve this issue.

**Comment by mxwi** [comment]
Still exists

**Comment by sinclairpaul** [comment]
It is documented as a limitation <https://github.com/hassio-addons/addon-nginx-proxy-manager/blob/main/proxy-manager/DOCS.md#known-issues-and-limitations>
