### ISSUE TITLE
No valid environment variables for database provided

### ISSUE THREAD

**Issue by SimonWalczak** [hassio-addons/addon-nginx-proxy-manager#348]
# Problem/Motivation

Addon uses SQLite instead of MariaDB, the configuration wasn't changed.

> s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/00-banner.sh
 Add-on: Nginx Proxy Manager
 Manage Nginx proxy hosts with a simple, powerful interface
 Add-on version: 0.12.1
 You are running the latest version of this add-on.
 System: Raspbian GNU/Linux 10 (buster)  (armv7 / raspberrypi3)
 Home Assistant Core: 2022.3.7
 Home Assistant Supervisor: 2022.08.3
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
cont-init: info: running /etc/cont-init.d/mysql.sh
cont-init: info: /etc/cont-init.d/mysql.sh exited 0
cont-init: info: running /etc/cont-init.d/nginx.sh
cont-init: info: /etc/cont-init.d/nginx.sh exited 0
cont-init: info: running /etc/cont-init.d/npm.sh
cont-init: info: /etc/cont-init.d/npm.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun manager (no readiness notification)
services-up: info: copying legacy longrun nginx (no readiness notification)
s6-rc: info: service legacy-services successfully started
[14:44:23] INFO: Starting the Manager...
[14:44:23] INFO: Starting NGinx...
[8/13/2022] [2:44:25 PM] [Global   ] › ℹ  info      No valid environment variables for database provided, using default SQLite file '/data/database.sqlite'
[8/13/2022] [2:44:25 PM] [Global   ] › ℹ  info      Generating SQLite knex configuration
[8/13/2022] [2:44:25 PM] [Global   ] › ⬤  debug     Wrote db configuration to config file: ./config/production.json
[8/13/2022] [2:44:34 PM] [Migrate  ] › ℹ  info      Current database version: none
[8/13/2022] [2:44:36 PM] [Setup    ] › ℹ  info      Logrotate Timer initialized
[8/13/2022] [2:44:36 PM] [Setup    ] › ℹ  info      Logrotate completed.`

## Expected behavior

Mappings should work as usual
UI Manager should manage the mappings as usual

## Actual behavior

Mappings work as usual
UI Manager works like after a clean installation

## Steps to reproduce

upgrade to 0.12.1 (?) Around one year since its last log in, I can't say when was the first occurrence

## Proposed changes

Fix envs?

**Comment by habuild** [comment]
FYI duplicated over there.
https://github.com/hassio-addons/addon-nginx-proxy-manager/issues/344

**Comment by SimonWalczak** [comment]
I've upgraded the add-on to 0.12.2. I still have the issue, but now I have different logs:

> s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/00-banner.sh
 Add-on: Nginx Proxy Manager
 Manage Nginx proxy hosts with a simple, powerful interface
 Add-on version: 0.12.2
 You are running the latest version of this add-on.
 System: Raspbian GNU/Linux 10 (buster)  (armv7 / raspberrypi3)
 Home Assistant Core: 2022.3.7
 Home Assistant Supervisor: 2022.08.3
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
cont-init: info: running /etc/cont-init.d/mysql.sh
[14:14:38] ERROR: This add-on now requires the MariaDB core add-on 2.0 or newer!
[14:14:38] FATAL: Make sure the MariaDB add-on is installed and running
cont-init: info: /etc/cont-init.d/mysql.sh exited 1
cont-init: info: running /etc/cont-init.d/nginx.sh
cont-init: info: /etc/cont-init.d/nginx.sh exited 0
cont-init: info: running /etc/cont-init.d/npm.sh
[14:14:40] ERROR: Got unexpected response from the API: Service not enabled
jq: error: syntax error, unexpected $end (Unix shell quoting issues?) at <top-level>, line 6:
    | .database.port =                       
jq: 1 compile error
cont-init: info: /etc/cont-init.d/npm.sh exited 0
cont-init: warning: some scripts exited nonzero
s6-rc: warning: unable to start service legacy-cont-init: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
prog: fatal: stopping the container.
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

> MariaDB 
Current version: 2.5.1
