### ISSUE TITLE
NPM seems to have lost all information despite no changes to NPM, MariaDB, or HA in general

### ISSUE THREAD

**Issue by eric10k93** [hassio-addons/addon-nginx-proxy-manager#353]
# Problem/Motivation

> (Why the issue was filed)
My remote access just stopped working, so I first checked DuckDNS and all certs were good.  I went to sign into NGINX Proxy Manager and it kept reporting my credentials were bad.  So I tried the default credentials and they worked... essentially, everything has been reset, and I have no clue why... I haven't updated anything in weeks.

## Expected behavior

> (What you expected to happen)
I expected NPM to hold my credentials and URLs.

## Actual behavior

> (What actually happened)
Everything got wiped.

## Steps to reproduce

> (How can someone else make/see it happen)
I'm going to need help on this one.  I'm happy to dig through some logs for info.  I just don't know where to begin, or if anything will even be there since everything else got reset.

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)
No proposed change, I would just like to help troubleshoot this so it doesn't happen again to me or others.

**Comment by eric10k93** [comment]
this was a weird issue, checking the logs, I still had some of my endpoints working, but HA external access was not... I needed to get this resolved, so I just wiped the whole NPM add-on and started over... closing this for now as I don't have much to help with

**Comment by tjorim** [comment]
Probably same issue as #344.
