### ISSUE TITLE
All proxies time out

### ISSUE THREAD

**Issue by KaliCZ** [hassio-addons/addon-nginx-proxy-manager#358]
# Problem/Motivation

> Hey, starting yesterday, the NGINX doesn't seem to be working for me. I use it as a proxy from public network to my internal services within my LAN.

> And lately I'm getting this for all requests. When I check the logs in HASS, the requests aren't even logged.
![image](https://user-images.githubusercontent.com/12395130/190216407-e886739b-db70-41bb-bda6-0d5c80d5f894.png)

> This is the log I get (after restart of HASS)
![image](https://user-images.githubusercontent.com/12395130/190216380-836ffc98-4c3a-4605-9e30-325eef010080.png)

The default route works with no issues though. So I'd say the logic of determining which route to apply works. It's just the execution of the proxy route that's the issue.

## Expected behavior

> Expected is for the proxies to pass requests forward as it has done up until today (or maybe a few days ago).

## Actual behavior

> 504 gateway timeout as per picture above.

## Steps to reproduce

> No idea. This is how I setup the proxy route. I tried not forcing SSL and it doesn't seem to matter.
![image](https://user-images.githubusercontent.com/12395130/190217271-d385d73c-14b6-461c-8c5b-0887c1ffedf2.png)
![image](https://user-images.githubusercontent.com/12395130/190217401-a075f7ac-1c1b-4849-9505-aa25a0f7fa57.png)

## Proposed changes

> None

**Comment by koenieee** [comment]
I have the same problem, can t get anything to work. Also connection refused

**Comment by koenieee** [comment]
Hmm nevermind, I just had to set the port 443 and 80 in the HA-configuration of this addon. Thinking it was already enabled

**Comment by InTheDaylight14** [comment]
> I have the same problem. It looks like the nginx was reinstalled with default setting. I had to login with defaults. All the proxies that I added are gone.

This has happened to me too. My login suddenly stopped working and I had to login with the default settings. Very weird, all my previously setup proxies are still working. My list is empty, I would have no way to edit them. Yet they still work? Not sure if that has been the same for you. 

I'm at a loss of what to do. It's almost like two instances are running and I cannot access my old one.
