### ISSUE TITLE
Enable Streams in NPM Addon

### ISSUE THREAD

**Issue by gitisz** [hassio-addons/addon-nginx-proxy-manager#362]
# Problem/Motivation

When I open the add-on, and select Open We UI, I receive **This site can’t provide a secure connection**.  

## Expected behavior

I would like to redirect NPM from 81 to another A record.  

## Actual behavior

 I receive **This site can’t provide a secure connection**.

## Steps to reproduce

Add Proxy host and SSL for Home Assistant, use internal DNS with A record that resolves to IP of Home Assistant. Set Home Assistant URL Internet and Internal to same A record.

## Proposed changes

This [Redit ](https://www.reddit.com/r/selfhosted/comments/smtt0k/nginx_proxy_manager_multiple_port_forwarding/) post suggests that I can use streams to redirect homeassistant.my.local on port 81 to nginx.my.local on port 443.  But in the documentation, it is mentioned that streams is disabled as there is no practical use for it.

**Comment by frenck** [comment]
> When I open the add-on, and select Open We UI, I receive This site can’t provide a secure connection.

That is no way related to your request.


> But in the documentation, it is mentioned that streams is disabled as there is no practical use for it.

Correct 👍 

Hence closing this.
