### ISSUE TITLE
Unable to start without MariaDB

### ISSUE THREAD

**Issue by rcmurphy** [hassio-addons/addon-nginx-proxy-manager#365]
# Problem/Motivation

> MariaDB is no longer working because the developers neglected to include any sort of error handling in their start process. NPM successfully creates a SQLite database as long as MariaDB is running, even if it can't be accessed. However, if MariaDB is not running, startup fails.

## Expected behavior

> Since the SQLite database clearly works, don't interrupt startup because a vestigal container isn't running.

## Actual behavior

> if MariaDB is not running, startup fails.

## Steps to reproduce

> Run NPM with MariaDB stopped

## Proposed changes

> remove mysql.sh, or make it handle errors more gracefully as to not cause startup to fail, since there is a viable fallback.

**Comment by nlhomme** [comment]
The goal os this issue is to suggest a solutution for the issue #368
