### ISSUE TITLE
Missing config in console

### ISSUE THREAD

**Issue by Keldandorin** [hassio-addons/addon-nginx-proxy-manager#366]
# Problem/Motivation

I can not see any config in console but my old config is still running. 
Also had to login with default username and password after upgrade to latest.

## Expected behavior

See my config in admin console

## Actual behavior

![image](https://user-images.githubusercontent.com/15968468/193774732-d0c5d3e3-e645-419c-9820-df8139a8f184.png)

What can I do to get my config back in admin console?

**Comment by gerriz** [comment]
I have the same problem.
The dashboard shows zero configured proxy hosts but is still running in the background.
My login was also reseted to default settings.

**Comment by TheAgentK** [comment]
I have also the same problem. 
My dashboard shows no configured proxy hosts, but my old config is still working and my login was also reseted to default.

**Comment by Sangoku** [comment]
This is due to somehow the addon reverting to using sqlLite... 
And not MariaDB  no idea how to fix this. 

This causes the addon to reset its db...

**Comment by Keldandorin** [comment]
Closing this as there already is another issue opend [https://github.com/hassio-addons/addon-nginx-proxy-manager/issues/344](#344)
