### ISSUE TITLE
problem redirecting to the home assistant address, always 400: Bad Request

### ISSUE THREAD

**Issue by schlumm** [hassio-addons/addon-nginx-proxy-manager#369]
### Discussed in https://github.com/hassio-addons/addon-nginx-proxy-manager/discussions/246

<div type='discussions-op-text'>

<sup>Originally posted by **JR-aaas** July 14, 2021</sup>
I have a newly installed home assistant, set up according to the instructions and everything worked until last week.
 page 400: Bad Request

![image](https://user-images.githubusercontent.com/62484901/125678962-2d490671-71f7-4dbb-953d-14c55aefbe2a.png)

Setup is correct 

![image](https://user-images.githubusercontent.com/62484901/125679130-59df550b-0ac6-4197-b248-c2204c405ab6.png)

HTTP website is correct  

![image](https://user-images.githubusercontent.com/62484901/125679316-c1f023b7-5349-4a79-801c-ab5612a9ce95.png)

HTTPS

![image](https://user-images.githubusercontent.com/62484901/125679397-bad83cf2-2f02-495e-9a25-670136f98283.png)

![image](https://user-images.githubusercontent.com/62484901/125680218-a45ebfad-ed64-492e-bb5c-d968f584c76f.png)

I don't know what to do, please advise why this is happening?</div>

**Comment by schlumm** [comment]
I wanted to get into the HA using duckDNS from outside of my home. After installing the nginx add-on. I cannot access to the HA main webpage. using the ip address with port 8183 or 8123, says site cannot be reached. Trying restart--> no help.
Using port 81, I get into the nginx and added multiple proxy hosts but cannot access to HA (even to an arduino server, that I can get to it directly using its IP address).
What am I missing?
How can I get to the configuration YAML and also to the nginx configuration (to verify that I've put everything OK), if I cannot get to HA?

**Comment by Doommius** [comment]
Hey @schlumm 

Try adding the following to your configuration.yaml. you can add the vscode plugin which exposes the config file. It it also mentioned here. https://community.home-assistant.io/t/home-assistant-400-bad-request-docker-proxy-solution/322163
```
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24 # You may also provide the subnet mask
```

**Comment by schlumm** [comment]
Hi,
Thanks for the data.
However, I cannot access the configuration.yaml.
As mentioned before, there is no access to the HA anymore, unless I need to use a specific port that I don’t know of.

Also, in the trusted proxies
you entered the /24 – what is this mean?
Is the HA ip (in your case) is 172.30.33.0


Regards,
Doron Schlumm

**Comment by schlumm** [comment]
Hi,
Thanks for the data.
However, I cannot access the configuration.yaml.
As mentioned before, there is no access to the HA anymore, unless I need to use a specific port that I don’t know of.

Also, in the trusted proxies 
you entered the /24 – what is this mean?
Is the HA ip (in your case) is 172.30.33.0

**Comment by Doommius** [comment]
It's the default range for docker. /24 means 172.30.33.*

Hmm. Then the best cause of action might be turning of HA and trying to edit the config on your computer?

If port 8123 doesn't work and ssh port 22 isn't enable then that's your best option imo.

**Comment by schlumm** [comment]
Thanks,
So I guess that I'll take the SD to my PC looking for the /config folder to get to the configuration yaml and add the following:
http:

  use_x_forwarded_for: true

  trusted_proxies:

    - 192.168.0.0/24 


as my HA current IP is 192.168.0.180 and the internal network has a 192.168.0.X

**Comment by Doommius** [comment]
Alright, what happens if you plug the PI into a screen and keyboard? That'll be via the command prompt but that should be a way in. I'm not sure which file system HA uses but it's probably due to it not being supported by windows.

https://www.home-assistant.io/common-tasks/os/#console-access

**Comment by schlumm** [comment]
Thanks for the info.
I did it and got to the ha folder.
the HA URL : HTTP://homeassistant.local:8123
the observer URL :  HTTP://homeassistant.local:4357

from the ha > root, how do I get to see the configuration.yaml and check it (or send it to you) for verification?
I tried "stop", but no help.
i don't know how to get to the location "/config/configuration.yaml"
If there is no error in the boot, doesn't it suggest that the configuration is OK?

should I follow the following?

_**ENABLE I2C WITH AN SD CARD READER
Access the boot partition
You will need:

SD card reader
SD card with Home Assistant Operating System flashed on it
Shutdown/turn-off your Home Assistant installation and unplug the SD card. Plug the SD card into an SD card reader and find a drive/file system named hassos-boot. The file system might be shown/mounted automatically. If not, use your operating systems disk management utility to find the SD card reader and make sure the first partition is available.

Add files to enable I2C
In the root of the hassos-boot partition, add a new folder called CONFIG.
In the CONFIG folder, add another new folder called modules.
Inside the modules folder add a text file called rpi-i2c.conf with the following content:
i2c-dev
Txt
In the root of the hassos-boot partition, edit the file called config.txt add two lines to it:
dtparam=i2c_vc=on
dtparam=i2c_arm=on
Txt
Start with the new OS configuration
Insert the SD card back into your Raspberry Pi.
On startup, the hassos-config.service will automatically pickup the new rpi-i2c.conf configuration.
Another reboot might be necessary to make sure the just imported rpi-i2c.conf is present at boot time.**_

**Comment by Doommius** [comment]
the pictures of your config isn't included here.

Can you post them in a code block?

`   # Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24 # You may also provide the subnet mask

binary_sensor:
  - platform: ping
    host: 1.1.1.1
    name: "Cloudflare ping"
    count: 2
    scan_interval: 5


`

**Comment by schlumm** [comment]
Hi,
I really appreciate your help.
I’ve changed the configuration according to the ip that you have mentioned (also added the local host , so it looks like the following and will test whenever I’ll get home:



# Loads default set of integrations. Do not remove.
default_config:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24
    - 172.0.0.1
    - ::1
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
duckdns:
  domain: schlumm
  access_token: 437daa62-55a7-480a-b40e-c77c03110a44
google_assistant: !include google_assistant_integ.yaml



The questions are :

  1.  Is this location is the right path (/var/log/journal\supervisor\homeassistant\configuration.yaml)? Am I doing right for changing it?
  2.  Do you see another problem in the file? What about the spaces & tabs?
  3.  Should I add the homeassistant: external url … (see the beginning of the example in https://companion.home-assistant.io/docs/troubleshooting/networking/))


Regards,
Doron Schlumm

**Comment by Doommius** [comment]
1. /var/log/journal\supervisor\homeassistant\configuration.yaml no it should be at /config/configuration.yaml
2. Looking at the file there are a few lines that shouldn't be needed.
```
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24
    - 172.0.0.1 #not needed
    - ::1 #not needed
  ssl_certificate: /ssl/fullchain.pem #not needed
  ssl_key: /ssl/privkey.pem #not needed
```
I'll post my config of the addon-nginx-proxy-manager later as I don't have access to it remotely.
3.  no as that should be handled by addon-nginx-proxy-manager the docs there is for during it via a plugin. the add on does everything in a docker image.
4. shouldn't matter as the same issue might occur either way.

It appears that you're trying to implement two different ways of running a remote proxy

- Plugin in the supervisor itself [plugin](https://companion.home-assistant.io/docs/troubleshooting/networking/)
- add-on via a container that is somewhat independent of HA. this is the addon-nginx-proxy-manager

**Comment by frenck** [comment]
Closing this issue, as it is not an add-on issue.

../Frenck

**Comment by schlumm** [comment]
@frenck, don't you think it is related to the NGINX addon?
I really think that due to it, I cannot get into the HA anymore.
I'll appreciate your thoughts and proposed solution.
if it is related to something else, please point me to the relevant subject (or copy this to a new subject).

**Comment by frenck** [comment]
> don't you think it is related to the NGINX addon?

Many applications, just like Home Assistant, need additional configuration when using a reverse proxy. Please consult the documentation of the application you are reverse proxying for more information.
