### ISSUE TITLE
Using certificates generated by Proxy manager & letzencrypt?

### ISSUE THREAD

**Issue by Tom1803** [hassio-addons/addon-nginx-proxy-manager#37]
Just wanna say: Great addon. Really. Thx a lot.

# Problem/Motivation
I had a hart time enabling ssl in Hassio-addons cause i simply dont now how to integrate generated certificates from nginx proxy manager.
Every time a certificate is generated nginx log tolds me the path where the ceritifcate ist generated. So far, so good.
Everthing is fine, i can use the certificate, hassio over https works fine.
But i cant get it to work if i want to use those certificates for other addons.
You usually got a small json config for your addon, like for example so:
{
  "ssl": false,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem"
}
If i enable ssl and give it the path to the new generated certificate from nginx proxy manager, i expect that this addon can be restarted using the generated letztencrypt certificate, with enabled ssl.
But actually none of my addons accepts the new cert location / can't find the certificat path, which i've read from the nginx-proxy-manager log.

So i have to start them without ssl. Hassio is encrypted but -
if i leave the addons with ssl disabled, some addons will be blocked from useragents like firefox while loading, because the server answer runs into the "mixed content" Policy of the useragent. 
Hassio parts https-encrypted, others, from the addon, not.

So the final question is: How can i bind the certificates of the nginx-proxy-manager into addons, to enable ssl all-through? How should the path look like in addon configs, which you have to 
specify? Could you give an example?

PS: Im not using services like duckdns - i've set up my very own DDNS separat from Hassio or other Providers, just for fun. I dont think that this is relevant to say at all, but here is no duckdns-Addon involved :) Just the proxy in front off Hassio. And that is working like it should. :-)

**Comment by tjorim** [comment]
I think you are missing the point of this add-on. It's a reverse proxy.
So you shouldn't enable ssl or set the certs in the other add-ons.

Anyway, what path to the certs are you using?
Might actually be more of a problem with the other add-ons.

**Comment by Tom1803** [comment]
After a while thinking about my "issue" you might be right.
looked carefully whats going on this morning and noticed that i run into this mixed-content-thing only with manual iframe config with addons which does not support ingress.
Next Solution was to me: get those iframes/addons on ssl, too.
But now i think there must be a way to integrate the iframe/addon in hassio better.
Instead of giving a simple ink to the iframe i will need something similar like this to get this work:
panel_custom:
  - name: hassio-main
    sidebar_title: Configurator
    sidebar_icon: hass:settings
    js_url: /api/hassio/app/entrypoint.js
    url_path: configurator
    embed_iframe: true
    require_admin: true
    config:
      ingress: core_configurator

I wll try moving in this direction, see what will happen.
Thanks for your advice.

**Comment by tjorim** [comment]
That configuration will only work with ingress-enabled add-ons.

**Comment by Tom1803** [comment]
Ok, then a last question:
If you like to integrate the nginx proxy manager WebUi into your Homeassistant sidebar using Hass.io as base image while using ddns with ssl over port 443. How would you do that task? 
Any tipp would be welcome. A (reverse) proxy rule maybe?

![hassio_sidebar_Integration_Nginx_manager_addon_with_ssl](https://user-images.githubusercontent.com/27722100/64364189-a81d6c00-d012-11e9-8878-6bd9f4e1c8f0.png)
