### ISSUE TITLE
SSH

### ISSUE THREAD

**Issue by acesyde** [hassio-addons/addon-nginx-proxy-manager#372]
# Problem/Motivation

After installing of this addon I want to use it for stream my SSH to my gitea server hosted on an other server (nas), but I can't because the option "Stream" is not available, after investigation #340 I checked the limitations, but IMO we have to have the choice to use this functionality or not, why truncate this product feature ? 

I agree with the current limitations, if the option is disabled by default no worries, but leave the choice to be able to re-enable it

## Expected behavior

* Disable / Enable the stream feature
* Open more ports

## Actual behavior

We have not the choice

**Comment by sinclairpaul** [comment]
It is listed in the limitations <https://github.com/hassio-addons/addon-nginx-proxy-manager/blob/main/proxy-manager/DOCS.md#known-issues-and-limitations>

Primarily it was removed so the addon doesn't require to be run on the Host network.
