### ISSUE TITLE
Support SQLite

### ISSUE THREAD

**Issue by iBobik** [hassio-addons/addon-nginx-proxy-manager#386]
# Problem/Motivation

MariaDB is overkill for most of the home use-cases and [Nginx Proxy Manager](https://nginxproxymanager.com/) supports SQLite by default, just do not give it DB_MYSQL env variables.

## Expected behavior

Allow to use SQLite

## Actual behavior

MariaDB is required

## Proposed changes

Make MariaDB optional. If not configured, configure Nginx Proxy Manager to save SQLite db to the proper storage.

Users currently use MariaDB should work the same.

**Comment by iBobik** [comment]
Already been proposed at #368

**Comment by iBobik** [comment]
Not fixed yet.

**Comment by ftrueck** [comment]
Same for me: not fixed. Reqires mariaDB core...

**Comment by iBobik** [comment]
I see no change

**Comment by frenck** [comment]
Closing the issue, as it is not an issue but a feature request.

../Frenck
