### ISSUE TITLE
nginx reverse proxy not usable.

### ISSUE THREAD

**Issue by james28909** [hassio-addons/addon-nginx-proxy-manager#387]
# Problem/Motivation

the web ui is not usable at all, clicking anything does not do anything at all unless i click "proxy hosts" or "ssl certificates", and when i click those i get the default button that says "add host" or "add ssl certificate" but clicking them doesnt do anything. clicking any links in the webui changes the address in the address bar but nothing happens in the webui itself. and also host (HA) is unreachable outside my local network.

the login works as intended with default credentials, originally i thought it was my instance of nginx but i nuked that installation and reset and reinstalled and that didnt fix it... so i nuked my mariadb installation and rebooted and reinstalled mariadb, now i am not getting any errors

## Expected behavior

i expect the web ui to work and let me add hosts and ssl certs and edit users and etc.
## Actual behavior

the web ui is not usable. 

## Steps to reproduce

have latest nginx reverse proxy manager installed.

i am on the latest core and HAOS and have the latest nginx reverse proxy manager installed and this is the log output from nginx reverse proxy manager:

```s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/00-banner.sh
-----------------------------------------------------------
 Add-on: Nginx Proxy Manager
 Manage Nginx proxy hosts with a simple, powerful interface
-----------------------------------------------------------
 Add-on version: 0.12.3
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.3  (amd64 / qemux86-64)
 Home Assistant Core: 2022.11.5
 Home Assistant Supervisor: 2022.11.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
cont-init: info: running /etc/cont-init.d/mysql.sh
cont-init: info: /etc/cont-init.d/mysql.sh exited 0
cont-init: info: running /etc/cont-init.d/nginx.sh
cont-init: info: /etc/cont-init.d/nginx.sh exited 0
cont-init: info: running /etc/cont-init.d/npm.sh
cont-init: info: /etc/cont-init.d/npm.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun manager (no readiness notification)
services-up: info: copying legacy longrun nginx (no readiness notification)
s6-rc: info: service legacy-services successfully started
[09:20:53] INFO: Starting NGinx...
[09:20:53] INFO: Starting the Manager...
2022/12/04 09:20:54 [error] 297#297: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.254.26, server: nginxproxymanager, request: "GET /api/ HTTP/1.1", upstream: "http://127.0.0.1:3000/", host: "192.168.254.42:81", referrer: "http://192.168.254.42:81/nginx/proxy"
[12/4/2022] [9:20:54 AM] [Global   ] › ℹ  info      Manual db configuration already exists, skipping config creation from environment variables
[12/4/2022] [9:20:56 AM] [Migrate  ] › ℹ  info      Current database version: 20211108145214
[12/4/2022] [9:20:56 AM] [Setup    ] › ℹ  info      Logrotate Timer initialized
[12/4/2022] [9:20:56 AM] [Setup    ] › ℹ  info      Logrotate completed.
[12/4/2022] [9:20:56 AM] [IP Ranges] › ℹ  info      Fetching IP Ranges from online services...
[12/4/2022] [9:20:56 AM] [IP Ranges] › ℹ  info      Fetching https://ip-ranges.amazonaws.com/ip-ranges.json
[12/4/2022] [9:20:57 AM] [IP Ranges] › ℹ  info      Fetching https://www.cloudflare.com/ips-v4
[12/4/2022] [9:20:57 AM] [IP Ranges] › ℹ  info      Fetching https://www.cloudflare.com/ips-v6
[12/4/2022] [9:20:58 AM] [SSL      ] › ℹ  info      Let's Encrypt Renewal Timer initialized
[12/4/2022] [9:20:58 AM] [SSL      ] › ℹ  info      Renewing SSL certs close to expiry...
[12/4/2022] [9:20:58 AM] [IP Ranges] › ℹ  info      IP Ranges Renewal Timer initialized
[12/4/2022] [9:20:58 AM] [Global   ] › ℹ  info      Backend PID 267 listening on port 3000 ...
[12/4/2022] [9:21:00 AM] [Nginx    ] › ℹ  info      Reloading Nginx
[12/4/2022] [9:21:00 AM] [SSL      ] › ℹ  info      Renew Complete
`QueryBuilder#allowEager` method is deprecated. You should use `allowGraph` instead. `allowEager` method will be removed in 3.0
`QueryBuilder#eager` method is deprecated. You should use the `withGraphFetched` method instead. `eager` method will be removed in 3.0
QueryBuilder#omit is deprecated. This method will be removed in version 3.0
Model#$omit is deprected and will be removed in 3.0.```

**Comment by james28909** [comment]
ok now i just seen this for the first time 

```2022/12/04 09:20:54 [error] 297#297: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.254.26, server: nginxproxymanager, request: "GET /api/ HTTP/1.1", upstream: "http://127.0.0.1:3000/", host: "192.168.254.42:81", referrer: "http://192.168.254.42:81/nginx/proxy"```

but i am unsure how to mitigate this issue since there is no reasonable way to configurethe backend in this regard (that i know of)
please advise

**Comment by pinkkoff** [comment]
+1. I have the same problem

**Comment by pinkkoff** [comment]
@james28909 i have tried to clean cache and reload the page, all buttons in web ui started to work properly

**Comment by james28909** [comment]
i was able to get it back working. i had to uninstall nginx then reboot then uninstall mariadb then reboot, then install mariadb then reboot then install nginx and reboot. everything worked fine after that. but when i test server reachability i get "Communication with the API failed, is NPM running correctly?"

even though the above error, i am able to access my ha server and all smart things just fine outside my home network now.
