### ISSUE TITLE
Loglevel ignored

### ISSUE THREAD

**Issue by dMopp** [hassio-addons/addon-nginx-proxy-manager#392]
# Problem/Motivation

A lot of log entries with severiry "info" is logged, even when i changed to loglevel to warn

## Expected behavior

Loglevel settings hould be respected

## Actual behavior

loglevel seems to ahve no effect

## Steps to reproduce

Change the loglevel and watch syslog

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

There are the entries i see:
`
Jan  9 08:36:57 ulli01 addon_a0d7b954_nginxproxymanager[668]: [09/Jan/2023:08:36:57 +0100] - 200 200 - POST https grafana.lan.dmopp.de "/api/hassio_ingress/<snip>/api/datasources/proxy/3/query?db=homeassistant&epoch=ms" [Client 192.168.3.188] [Length 10768] [Gzip -] [Sent-to 192.168.1.55] "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15" "https://grafana.lan.dmopp.de/api/hassio_ingress/<snip>/d/CzJvlN7Vz/gerateverbrauch?kiosk=tv&autofitpanels&orgId=1&refresh=5s"
Jan  9 08:36:57 ulli01 addon_a0d7b954_nginxproxymanager[668]: [09/Jan/2023:08:36:57 +0100] - 200 200 - POST https grafana.lan.dmopp.de "/api/hassio_ingress/<snip>/api/datasources/proxy/3/query?db=homeassistant&epoch=ms" [Client 192.168.3.188] [Length 10247] [Gzip -] [Sent-to 192.168.1.55] "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15" "https://grafana.lan.dmopp.de/api/hassio_ingress/<snip>/d/CzJvlN7Vz/gerateverbrauch?kiosk=tv&autofitpanels&orgId=1&refresh=5s"
Jan  9 08:36:57 ulli01 addon_a0d7b954_nginxproxymanager[668]: [09/Jan/2023:08:36:57 +0100] - 200 200 - POST https grafana.lan.dmopp.de "/api/hassio_ingress/<snip>/api/datasources/proxy/3/query?db=homeassistant&epoch=ms" [Client 192.168.3.188] [Length 10310] [Gzip -] [Sent-to 192.168.1.55] "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15" "https://grafana.lan.dmopp.de/api/hassio_ingress/<snip>/d/CzJvlN7Vz/gerateverbrauch?kiosk=tv&autofitpanels&orgId=1&refresh=5s"
Jan  9 08:36:57 ulli01 addon_a0d7b954_nginxproxymanager[668]: [09/Jan/2023:08:36:57 +0100] - 200 200 - POST https grafana.lan.dmopp.de "/api/hassio_ingress/<snip>/api/datasources/proxy/3/query?db=homeassistant&epoch=ms" [Client 192.168.3.188] [Length 10415] [Gzip -] [Sent-to 192.168.1.55] "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15" "https://grafana.lan.dmopp.de/api/hassio_ingress/<snip>/d/CzJvlN7Vz/gerateverbrauch?kiosk=tv&autofitpanels&orgId=1&refresh=5s"
Jan  9 08:36:57 ulli01 addon_a0d7b954_nginxproxymanager[668]: [09/Jan/2023:08:36:57 +0100] - 200 200 - POST https grafana.lan.dmopp.de "/api/hassio_ingress/<snip>/api/datasources/proxy/3/query?db=homeassistant&epoch=ms" [Client 192.168.3.188] [Length 10325] [Gzip -] [Sent-to 192.168.1.55] "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15" "https://grafana.lan.dmopp.de/api/hassio_ingress/<snip>/d/CzJvlN7Vz/gerateverbrauch?kiosk=tv&autofitpanels&orgId=1&refresh=5s"
Jan  9 08:36:57 ulli01 addon_a0d7b954_nginxproxymanager[668]: [09/Jan/2023:08:36:57 +0100] - 200 200 - POST https grafana.lan.dmopp.de "/api/hassio_ingress/<snip>/api/datasources/proxy/3/query?db=homeassistant&epoch=ms" [Client 192.168.3.188] [Length 10363] [Gzip -] [Sent-to 192.168.1.55] "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15" "https://grafana.lan.dmopp.de/api/hassio_ingress/<snip>/d/CzJvlN7Vz/gerateverbrauch?kiosk=tv&autofitpanels&orgId=1&refresh=5s"
Jan  9 08:36:57 ulli01 addon_a0d7b954_nginxproxymanager[668]: [09/Jan/2023:08:36:57 +0100] - 200 200 - POST https grafana.lan.dmopp.de "/api/hassio_ingress/<snip>/api/ds/query" [Client 192.168.3.188] [Length 40272] [Gzip -] [Sent-to 192.168.1.55] "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15" "https://grafana.lan.dmopp.de/api/hassio_ingress/<snip>/d/CzJvlN7Vz/gerateverbrauch?kiosk=tv&autofitpanels&orgId=1&refresh=5s"`

Notes: Everything is up2date, from addons, over hypervisor package down down every single integration.

**Comment by frenck** [comment]
> A lot of log entries with severiry "info" is logged, even when i changed to loglevel to warn

The log level controls is for the add-on log itself, not for NGINX proxy manager. The provided bug report is therefore expected and not a bug.

../Frenck
