### ISSUE TITLE
HASS uses incorrect URL to launch web UI when secured by SSL

### ISSUE THREAD

**Issue by stmccartney** [hassio-addons/addon-nginx-proxy-manager#394]
# Problem/Motivation

I want to be able to launch the web UI for the nginx proxy manager by using the "Open Web UI" button under the Info tab for the addon within HASS

## Expected behavior

I have HASS secured behind an SSL proxy host in proxy manager (https://myhass.example.com), and when I click on the Open Web UI button I expect HASS to launch the UI using a non-SSL URL as the UI doesn't support SSL - (http://myhass.example.com:81)

## Actual behavior

The URL is launched with https at the front (https://myhass.example.com:81), which results in the browser throwing an SSL protocol error

## Steps to reproduce

I have a Home Assistant OS installation running on a Raspberry Pi 3
Follow the default example in Nginx Proxy Manager to configure an SSL proxy for homeassistant with a custom domain.
In HASS under Settings -> System -> Network -> Home Assistant URL, enter the details for the custom domain
Go to Settings -> Add-ons -> Nginx Proxy Manager and click Open Web UI

## Proposed changes

I think this would be best solved by making two changes:

1. Always ensure that the Web UI button launches an http (not https) URL by default
2. Add a configuration option to the add-on that allows setting a custom admin URL - this would then allow the creation of an SSL proxy within proxy manager that could be used to access the admin page via SSL

**Comment by michaelblight** [comment]
Came here for a different issue, but I'm not seeing the same on version 0.12.3. I too have the add-on securing HA, but when I click on "Open Web UI" it goes to http, not https. If I hover over the button it shows the URL without protocol, which I assume is http because other links in HA show https on hover.

**Comment by stmccartney** [comment]
> Came here for a different issue, but I'm not seeing the same on version 0.12.3. I too have the add-on securing HA, but when I click on "Open Web UI" it goes to http, not https. If I hover over the button it shows the URL without protocol, which I assume is http because other links in HA show https on hover.

That's interesting, do you also have your custom domain configured with https under Settings -> System -> Network -> Home Assistant URL, or not?

**Comment by michaelblight** [comment]
I do - Home Assistant URL is set to https://my-name.duckdns.org. However, I'm accessing it using SSL inside my network with this URL as I have the domain set up as local DNS in pihole, pointing to HA. Not sure if that makes a difference. I haven't tried outside my network, but if it still tries with http I have a redirect to https.

**Comment by frenck** [comment]
This is, unfortunately, not fixable by the add-on. The interface you're looking at is the Home Assistant Supervisor, not this add-on.

../Frenck
