### ISSUE TITLE
Manifest for homeassistant/amd64-addon-nginx_proxy:2.1 not found

### ISSUE THREAD

**Issue by Vout** [hassio-addons/addon-nginx-proxy-manager#4]
I see there's an update for the NginX proxy manager however when trying to update i see this error in the log,

```[hassio.docker.interface] Can't install homeassistant/amd64-addon-nginx_proxy:2.1 -> 404 Client Error: Not Found ("manifest for homeassistant/amd64-addon-nginx_proxy:2.1 not found").```

Something temporary and the solution is just to wait some time and try again?

**Comment by coolbombom** [comment]
Hi i have a raspberry pi 3 running latest version of hass.io. I also received an error trying to update, i therefore desided to uninstall the nginx addon and reinstall it. but im still receiving following error:

`19-03-10 20:42:40 INFO (SyncWorker_0) [hassio.docker.interface] Pull image homeassistant/armv7-addon-nginx_proxy tag 2.1.
19-03-10 20:42:42 ERROR (SyncWorker_0) [hassio.docker.interface] Can't install homeassistant/armv7-addon-nginx_proxy:2.1 -> 404 Client Error: Not Found ("pull access denied for homeassistant/armv7-addon-nginx_proxy, repository does not exist or may require 'docker login'").`

kind regards
c_bb

**Comment by artomka** [comment]
I have the same error. HA 0.89.1

**Comment by dankanesnc** [comment]
Same here after upgrading to hassio 0.89.1, running in Docker on a Linux machine.

**Comment by frenck** [comment]
This is the NGinx Proxy Manager add-on, not the NGinx proxy add-on (which is a core add-on).
Please file the bug in the correct location: https://github.com/home-assistant/hassio-addons.

Thanks.
