### ISSUE TITLE
Allow a mapped directory like /config/nginxproxymanager for persisting custom "snippets"

### ISSUE THREAD

**Issue by mitchins** [hassio-addons/addon-nginx-proxy-manager#402]
# Problem/Motivation

Although nginx proxy manager is supposed to simplify things, certain times we will want to reference common includes that mask some complex behaviour or settings.

Suggest we map a volume for snippets so that it can persist outside of the container's instance.
Authelia for example uses a few different snippets that are included in the advanced config (and quite long).

![image](https://user-images.githubusercontent.com/1016050/221326445-45f98076-03ec-4213-b16c-87a7faf96cc9.png)

As per the image above, I suppose it works creating a directory inside /ssl/nginxproxymanager called snippets however its a bit unorthodox...

## Expected behavior

Have a persistent location under /config to save custom snippets and includes for nginx proxy manager, so we can edit it with visual studio code. 

## Actual behavior

There's not a suitable location under /config exposed.

## Steps to reproduce

Occurs by design, currently.

## Proposed changes

Creating a mapping for `/config/nginxproxymanager` so we can store our custom .confs.

**Comment by sinclairpaul** [comment]
Doesn't <https://github.com/home-assistant/addons/tree/master/nginx_proxy> meet that criteria?

**Comment by mitchins** [comment]
> Doesn't <https://github.com/home-assistant/addons/tree/master/nginx_proxy> meet that criteria?

But if we want the UI of proxy manager, but just persist some include files.. shouldn't it be possible?

The proxy manager is nice and accessible, but surely some include files is a reasonable use case?

**Comment by frenck** [comment]
> Creating a mapping for /config/nginxproxymanager so we can store our custom .confs.

The config folder shouldn't be used by other add-ons. It is dedicated to Home Assistant.

If you need this level of customization, this add-on is not for you.

Closing it, as there is no acceptable path forward.

../Frenck
