### ISSUE TITLE
Docs (and tutorial gif) missing mandatory steps to set up reverse proxies in HA

### ISSUE THREAD

**Issue by Chaoscontrol** [hassio-addons/addon-nginx-proxy-manager#404]
# Problem/Motivation
Already described here and resuscitating it: #109 

The docs tutorial (which is great with that gif btw) doesn't mention anything about http configuration for reverse proxies. After setting up NPM, I deleted my old http config (which I had from NGINX Proxy SSL), and after a while I found out I couldn't connect remotely. After debugging, it was indeed I was missing those lines of yaml. After I added them back, everything worked. 

I went and checked the docs for NPM and this is never mentioned or hinted, so new users will struggle with this. 

## Expected behavior

I followed the tutorial in the docs step by step. 

## Actual behavior

HAOS refused connections. 

## Steps to reproduce

Set up NPM without allowing http reverse proxies options. 

## Proposed changes

I think just adding the extra tutorial step in the docs to add these lines to configuration.yaml will do. 

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24

**Comment by frenck** [comment]
This is an add-on, not Home Assistant.

Please consult the documentation of the application you are reverse proxying for information on configuring that specific application (in your case: Home Assistant -> Home Assistant documentation).

../Frenck

**Comment by Chaoscontrol** [comment]
The docs include installation instructions on Home Assistant, as well as mandatory requirements, like needing the MariaDB, even when it's "just" an add-on. The same way it instructs to forward your router ports. I honestly think it's low effort and would help.

**Comment by frenck** [comment]
Oh ok, sorry. Don't share that feeling.

I have no intention to provide tutorials on configuring reverse proxies for applications. Applications themselves do a much better job at that.

../Frenck
