### ISSUE TITLE
Depends on MariaDB for no reason

### ISSUE THREAD

**Issue by jokke-ilujo** [hassio-addons/addon-nginx-proxy-manager#405]
# Problem/Motivation

Running the addon does not utilize MariaDB by default and works just fine without (after the startup dependency check). MariaDB addon should not be mandatory dependency.

## Expected behavior

The addon to start without MariaDB addon being installed.

## Actual behavior

The addon fails to install (and consequently start if MariaDB addon was removed after install).

## Steps to reproduce

Try to install the addon, error will be logged that MariaDB is dependency.
Install MariaDB addon and install the nginx pm addon.
Look at the logs on startup and the addon clearly logs that it does not have MariaDB connection and proceeds the startup without, utilizing sqlite.
Remove the MariaDB addon and the nginx pm keeps running no problem.
Restart the nginx pm addon, the restart fails due to the missing dependency of MariaDB that has not been used at any point.

## Proposed changes

Remove the dependency to MariaDB addon and document the need if the nginx pm is actually configured to use it (or how to configure the addon to utilize external MariaDB instance which would be even better option if HA is running on RPi or similar).

**Comment by ovizii** [comment]
That sounds weird, I also just wanted to install this addon but was  stopped by it depending on mariadb. I really don't think I need to make my little RPI run a full-blown mariadb for reverse-proxying 1 domain. 

Curious to see what comments will be on this issue.

**Comment by frenck** [comment]
> Depends on MariaDB for no reason

You assume there is no reason.

../Frenck
