### ISSUE TITLE
Access List won't authenticate - 401

### ISSUE THREAD

**Issue by iamandymcinnes** [hassio-addons/addon-nginx-proxy-manager#41]
# Problem/Motivation

When you create an access list and add a username and password, then assign it to a host it will constantly fail the challenge with the username and password you added to the access list resulting in a 401.

## Expected behavior

Once challenged you enter the username and password configured on the access list, authentication will pass and the site will be displayed.

## Actual behavior

Once challenged you enter the username and password configured on the access list, it fails to authenticate and displays the challenge over and over.

## Steps to reproduce

Create an access list
Add a username and password
Assign the access list to a host 
Navigate to the host url
Enter username and password in the challenge
Challenge will continually be displayed

## Proposed changes

Not sure on change required, maybe the challenge is not getting through to the credential check endpoint.

**Comment by frenck** [comment]
I’m guessing you try to add it in front of Home Assistant?

**Comment by iamandymcinnes** [comment]
No I just tried to add it in front of the simple sonoff server addon's web page. 
https://github.com/gerswin/ihomeaddons/tree/master/sonoff_server

**Comment by frenck** [comment]
I’m not familiar with that application, I do know that some applications don’t like to be reversed provide. Especially auth can be an issue some times, when the application behind the auth plays with the authentication headers as well. This is not a bug, but merely how the HTTP protocol works and how the provide application handles it.

**Comment by iamandymcinnes** [comment]
Are there any recommendations how to support the reverse proxy from app development perspective, or anythings to avoid if that is an easier way to look at it?

**Comment by iamandymcinnes** [comment]
@frenck I'm not sure how the authentication bit affects things, but just to clarify the web app I'm working with does work with the reverse proxy. I.e. I can bind https://sonoff.domain.com >>> http://192.168.1.1:1080 and am able to use it without the access list assigned. 

You mentioned authentication headers, in what format does proxy manager apply these, so I can check they aren't getting messed up?

Many thanks

Andy

**Comment by iamandymcinnes** [comment]
Figured it out... it seems passwords containing things like £ or $ don't work
