### ISSUE TITLE
Improvement: Let's have an entity that shows renewed/expired certs

### ISSUE THREAD

**Issue by jusicgn** [hassio-addons/addon-nginx-proxy-manager#437]
# Problem/Motivation

Idea for improvement:
Would be rally nice to have an entity that shows certs that are about to expire/expired/recently renewed.
So we could build a nice dashboard with our certs... ;)
Also some automation/notification could be based on that.

## Expected behavior

Show status of certs in an entity.

## Actual behavior

--

## Steps to reproduce

--

## Proposed changes

--

**Comment by tjorim** [comment]
You can always contribute to this integration 😉 https://github.com/InTheDaylight14/nginx-proxy-manager-switches
