### ISSUE TITLE
Update Nginx Proxy Manager Version

### ISSUE THREAD

**Issue by HydrelioxGitHub** [hassio-addons/addon-nginx-proxy-manager#446]
# Problem/Motivation

> NPM has added Google Domains DNS provider in the version 2.9.20 ( https://github.com/NginxProxyManager/nginx-proxy-manager/releases/tag/v2.9.20 ) . The actual version used by the addon is 2.9.19.

## Expected behavior

> Use at least the 2.9.20 version. But the latest version is the 2.10.2 ( https://github.com/NginxProxyManager/nginx-proxy-manager/releases/tag/v2.10.2 )

## Actual behavior

> version 2.9.19 is used

## Steps to reproduce

> Non relevant

## Proposed changes

> Update Nginx Proxy Manager version

**Comment by frenck** [comment]
Codebase is currently at: v2.10.2

https://github.com/hassio-addons/addon-nginx-proxy-manager/blob/dab35df9a3b6f2df832d89d0548243b67a95c748/proxy-manager/Dockerfile#L15

Also, this isn't an bug report.

../Frenck

**Comment by HydrelioxGitHub** [comment]
![image](https://github.com/hassio-addons/addon-nginx-proxy-manager/assets/15862735/09048bad-2f58-49d9-ab89-9c6c91f9d887)

Sorry for my misunderstood. I've based my issue on the log of the Addon.

**Comment by HydrelioxGitHub** [comment]
And this is curious because your last release of the addon was in last november. And the release of the 2.10.2 Nginx Proxy Manager was on last march ....

**Comment by frenck** [comment]
How is that curious?

**Comment by frenck** [comment]
Because I haven't released one. That simple.
