### ISSUE TITLE
Login fails with internal error

### ISSUE THREAD

**Issue by iamandymcinnes** [hassio-addons/addon-nginx-proxy-manager#45]
# Problem/Motivation

This had been working perfectly, and is in terms of existing proxies I have configured, however whenever I try to login now I get the following error:

{"error":{"message":"Internal Error"}}

## Expected behavior

I can see the dashboard after logging in

## Actual behavior

I get an error "internal error" message

## Steps to reproduce

Have everything configured as normal, try to login, get the error displayed on the login page. You can see the error is returned when the login posts off to the token endpoint.

## Proposed changes

Not sure

**Comment by sinclairpaul** [comment]
Would be good to see the addon logs please?

**Comment by iamandymcinnes** [comment]
hmm very strange, just put the logs to debug, restarted and its working now.... go figure :) thanks any way.
