### ISSUE TITLE
NGINXProxy Manager crashing

### ISSUE THREAD

**Issue by stevewaha** [hassio-addons/addon-nginx-proxy-manager#450]
# Problem/Motivation

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by stevewaha** [comment]
nginx: [emerg] directive "root" is not terminated by ";" in /data/nginx/proxy_host/1.conf:39
[10:05:14] WARNING: NGINX Proxy Manager crashed, halting add-on

How do I edit the file if the proxy manager won't start?

**Comment by tjorim** [comment]
Remove and install the add-on again.
Please fill out the issue template provided.
