### ISSUE TITLE
Nginx proxy manager addon version of home assistant has no 'Streams' button

### ISSUE THREAD

**Issue by user514** [hassio-addons/addon-nginx-proxy-manager#457]
# Problem/Motivation

   Nginx proxy manager version of home assistant is very limited with no 'Streams' button.

## Expected behavior

  I have seen more issues posts about it, (now that I have found that has no 'streams' option), all closed. I would like to give my impression that streams are necessary for a reverse proxy for accesing our home machines from the outside. For accessing HA from the outside, there is already an addon only for that 'NGINX Home Assistant SSL proxy', which is only for that, correct me if I'm wrong.

  I spent one day configuring the addon, first to access my http pages of my home computers, and when I was going to start with streams (what you use to access non http or https services), like ssh, or vnc, etc. I see that it is removed from this version. Now I have read on addon docs this phrase:

"Known issues and limitations: The original NGinx Proxy Manager has support for forwarding TCP/UDP streams, which is removed from this add-on. It makes no sense from a Home Assistant / Home perspective and, by removing it, it also removed the need for this add-on to run on the Docker host network"

  I TOTALLY DISAGREE WITH THAT. If it is a problem to not have the docker part for compatibility with hassos, etc, it's really sad to hear. But I do not agree that this feature is not vital for nginx (and home users).

  As soon as I saw the 'streams' button removed form the addon, I uninstalled, and install nginx proxy manager docker version on a different computer to do the work I needed. Worked great. It will be much more interesting for me to have the addon do that job with the HA machine.

  Just my impression. Thanks for hearing.

## Actual behavior

  Not able to forward and access my home computers with non http services to access ssh, vnc, etc from the outside world.

## Proposed changes

Add the blue 'Streams' button, next to the green 'Proxy Hosts' button to the nginx proxy manager addon.

**Comment by sinclairpaul** [comment]
Not an issue here, closing.

It's documented, glad you found an alternate method for your requirement.
