### ISSUE TITLE
Internal Error

### ISSUE THREAD

**Issue by cjeffcoat80** [hassio-addons/addon-nginx-proxy-manager#46]
I am new to coding and home assistant as well. I do not know a lot about computers but am learning. I have the Nginx Proxy Manager on ha. It use to work fine. Until I changed my ha from my raspberry pi 2 to my server using a virtual machine and am using docker and have also installed Portainer. That being said my ip address for ha has changed as well. I have set  port forward rules for port 80 and port 443 in my Untangle as well. I am getting an error message when I go to the bottom of the addon page. When I go to Nginx Proxy Manager to set it up, I save it and it says "internal error". I was hoping you could shine some light on the problem. Please help me...... I am lost and dont know what to do. Also here is the error message that I am getting........

[18:22:06] INFO: Starting NGinx...
nginx: [emerg] open() "/proc/1/fd/1" failed (13: Permission denied)

Thank you for your help!

**Comment by frenck** [comment]
Can you provide me system information?

Run the `hassio info` command in one of the SSH add-ons.

**Comment by cjeffcoat80** [comment]
I do not have any ssh addons configured. Is that what I need to do?

**Comment by cjeffcoat80** [comment]
I dont know how. But it is up and running. Thank you for your help. I can not tell you what I did. I just went in to Nginx and started the process over again. But either way, thank you for your response and I am most appreciative for your willingness to help me out.
