### ISSUE TITLE
Addon does not have the same default upload limit as HA Core

### ISSUE THREAD

**Issue by marvin-w** [hassio-addons/addon-nginx-proxy-manager#461]
# Problem/Motivation

> (Why the issue was filed)

Since the release of https://github.com/home-assistant/core/pull/77117 we support a total max upload size of 100 MB.

Recently, there were a lot of user requests that had issues uploading their KNX project in our custom panel due to them using either a custom reverse proxy or this addon. See https://github.com/XKNX/xknxproject/issues/258

The default upload limit does not accompany for this upload limit increase hence the upload of files larger then the current limit but lower than 100 MB (in this case 5.2 MB) fails.

## Expected behavior

> (What you expected to happen)

This addon has the same upload limit restrictions as HA Core and users will be able to upload files as high as 100 MB.

## Actual behavior

> (What actually happened)

The upload fails and (non powerusers) have no idea what to do and how to resolve this.

## Steps to reproduce

> (How can someone else make/see it happen)

1. Install HA
2. Install this addon with all required addons
3. Enable/Install the KNX integration
4. Go to the panel
5. Upload any file larger than 5 MB - does not neccessarily have to be an ETS project file since the upload will fail anyway

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

This addon should add the 

```nginx
client_max_body_size 100M;
```

directive directly in the server block to accompany the HA Core upload limit.

I guess we can do this via https://nginxproxymanager.com/advanced-config/#custom-nginx-configurations

**Comment by sinclairpaul** [comment]
I believe the default for nginx is 2MB, as you have stated it can be adjusted by specifying the config, not sure why we would look to hardcode this, as the proxy can be used for other things rather than HA.

**Comment by sinclairpaul** [comment]
I'll close this out, any change in uploads should be a user discission so people are aware of what they are allowing.

**Comment by marvin-w** [comment]
Hm this is really sad. I personally don't use this addon but I doubt that less than 95% of all the people installing it will use it for something else than HA.

I understand that you have to maintain flexibility and user control, but we must also balance this with the user experience.

From a user perspective, it's ideal if they don't have to delve into complex technical details or make decisions that could potentially impact the security or functionality of their systems. Ideally, such elements would be taken care of by the system itself, behind the scenes, or at least offer sensible default settings.
