### ISSUE TITLE
[Feature Request] Make mysql database connection parameters customizable

### ISSUE THREAD

**Issue by kcpants** [hassio-addons/addon-nginx-proxy-manager#465]
Making the database connection parameters used by this addon customizable would allow users to run the database on another machine. This helps limit writes to the data disk which extends the lifetime of the storage. This is especially useful/important when running hassOS off of an SD card (e.g. on a Raspberry Pi without an SSD).

https://github.com/hassio-addons/addon-nginx-proxy-manager/blob/dab35df9a3b6f2df832d89d0548243b67a95c748/proxy-manager/rootfs/etc/cont-init.d/npm.sh#L130-L134

**Comment by frenck** [comment]
That is not what issue trackers are for. Please use the discussions instead.

../Frenck
