### ISSUE TITLE
Unable to access via panel_iframe because x-frame-options=deny

### ISSUE THREAD

**Issue by ThePicklenat0r** [hassio-addons/addon-nginx-proxy-manager#47]
# Problem/Motivation

I'm unable to display the proxy manager portal as a panel in the Home Assistant UI

## Expected behavior

To be able to use a panel_iframe to access the web interface to manage Nginx

## Actual behavior

I get a ```proxy-admin.example.com refused to connect.``` error when loading the panel. If I inspect the page I get this error: ```Refused to display 'https://proxy-admin.example.com' in a frame because it set 'X-Frame-Options' to 'deny'.```

## Steps to reproduce

Setup Nginx-Proxy-Manager and verify you can access the web portal directly. Setup a proxy to the admin portal, and add it to a panel_iframe in configuration.yaml and try to access it. 

I've also verified that this does not work if I go directly to the ip:81 while on my local network.

## Proposed changes

I think this issue can be fixed by adding an ENV variable to the dockerfile like this: ```ENV X_FRAME_OPTIONS=sameorigin``` (reference: https://github.com/jc21/nginx-proxy-manager/issues/88). Possibly allow this to be optional through an option in the addon.

If I've missed something else here, please let me know. Thank you!

**Comment by strikeir13** [comment]
I have a nginx entry in my side panel using an iframe and entering this code in the Advanced section of the proxy host details:
`proxy_hide_header X-Frame-Options;`

**Comment by ThePicklenat0r** [comment]
@strikeir13 I just added that in on my config and it fixed my issue, thank you very much!
