### ISSUE TITLE
Unable to get NPM to redirect for local traffic. 

### ISSUE THREAD

**Issue by Dark1886** [hassio-addons/addon-nginx-proxy-manager#471]
# Problem/Motivation

> I'm using this for a local domains only to redirect a something like *.localdomain.lan to 192.168.1.X:Y so I don't need to remember all the ports/IPs for different services. 

## Expected behavior

> When I type in Localdomain.Lan i would expect to see the same webpage if I went to Http://192.168.1.10:8123.

## Actual behavior

> I get a "DNS_PROBE_FINISHED_NXDOMAIN" error on the webpage. 

## Steps to reproduce
> 1. Change DNS server on PC to point to device that is running NPM.
> 2. Using HASSio I installed the marioDB and the addon NPM
> 3. Create a Proxy Host 
![image](https://github.com/hassio-addons/addon-nginx-proxy-manager/assets/64846241/ef5cce02-34ba-42d7-ab58-8a7315ba2988)
> 4. Navigate to the website "localdomain.lan"

**Comment by sinclairpaul** [comment]
I believe you likely need to specify a host which can be resolved, i.e. x.domain.com, or alternatively have the correct A record at the root.  Either way I would suggest validating using nslookup or other tools.

**Comment by Dark1886** [comment]
I updated my proxy domain name to HA.localdomain.lan and I've also added the following to my configuration.yaml as I believe it is needed, but still without any change. 

> http:
     use_x_forwarded_for: true
        trusted_proxies:
           - 192.168.1.0/24 # Add the IP address of the proxy server
           - 172.30.32.0/24

**Comment by Dark1886** [comment]
@sinclairpaul 

I updated my proxy domain name to HA.localdomain.lan and I've also added the following to my configuration.yaml as I believe it is needed, but still without any change.

http:
use_x_forwarded_for: true
trusted_proxies:
- 192.168.1.0/24 # Add the IP address of the proxy server
- 172.30.32.0/24

**Comment by sinclairpaul** [comment]
This is a Proxy not a DNS server, you will need to configure your name resolution elsewhere
