### ISSUE TITLE
Can i redirect the port to a different IP without the host? I need to access IP:PORT.

### ISSUE THREAD

**Issue by FullSilence** [hassio-addons/addon-nginx-proxy-manager#476]
# Problem/Motivation

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Nope.
