### ISSUE TITLE
addon-nginx-proxy-manager

### ISSUE THREAD

**Issue by Ajaxhanna** [hassio-addons/addon-nginx-proxy-manager#48]
# my addon-nginx-proxy-manager in hassio cannot start at all.
Here is my config:
{
  "domain": "sample.duckdns.org:8123",
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "hsts": "max-age=31536000; includeSubDomains",
  "cloudflare": false,
  "customize": {
    "active": false,
    "default": "nginx_proxy_default*.conf",
    "servers": "nginx_proxy/*.conf"
  }
}
Please assist.

**Comment by sinclairpaul** [comment]
This is not valid configuration for the nginx-proxy-manager addon, it appears that it is for the main nginx addon.   Please view the relevant docs.
