### ISSUE TITLE
the configuration is not restored after restoring the addon from the backup

### ISSUE THREAD

**Issue by milleraa** [hassio-addons/addon-nginx-proxy-manager#487]
after restoring from the backup using homeassistant, we get a clean configuration

**Comment by frenck** [comment]
The data is stored in the MariaDB add-on, make sure you retire that one and make sure it is correctly restored as well.

**Comment by smugleafdev** [comment]
I believe I have this issue as well, but it's confusing. I recently replaced the storage HA was running on and I restored from backup. Everything seemed to be working. I don't really log into the Nginx addon for fun very often.

When I logged in for the first time since restoring from backup, it treated me as if I had never logged in before. Default user/pass, no items. Yet they're all still working, and if I stop the addon they also stop.

**Comment by stevenboyd78** [comment]
I am having the same issue as @smugleafdev, except I didn't do any restores. I tried to login to add a new host and everything was a clean slate, but the redirects are still working.

**Comment by smugleafdev** [comment]
As a note I do not have confirmation that it was the restore that made it disappear. It's possible and likely I think, but it also could have happened before or after I did the restore. Next time I do such a thing, I'll check I can load all my addons' web UIs.

The big question here is how these redirects are still active if they aren't visible. If I'm not running nginx anywhere else, where are they? If they're hidden in nginx, how can we access them again? If we cannot, what is the best thing to do? Uninstall it complete, reinstall, and do our best to set them up as they were? In a few months I'll know if the SSLs are being auto-renewed.

**Comment by sinclairpaul** [comment]
> The big question here is how these redirects are still active if they aren't visible

The application stores the configuration in the database, and exports them to Nginx Config files.  As you have restored just this addon (likely not the database), the config files exist, but the application cannot view the config.

**Comment by smugleafdev** [comment]
> The application stores the configuration in the database, and exports them to Nginx Config files. As you have restored just this addon (likely not the database), the config files exist, but the application cannot view the config.

Given this scenario is what is happening to me, and I still have the old eMMC that has a working Nginx config, do you think I can pop it back in and create a new backup? Would it be a partial backup with both MariaDB and Nginx or only one of them? Might I have trouble restoring that backup on my new eMMC (DB collisions?)?

**Comment by sinclairpaul** [comment]
Try it and see would be my suggestion, just take backups on your current system beforehand, you should only need MariaDB and NPM.  Obviously if you use MariaDB for anything else it may be problematic, but you could always use the phpMyAdmin tool to perform manual database dumps.

**Comment by smugleafdev** [comment]
> Try it and see would be my suggestion, just take backups on your current system beforehand, you should only need MariaDB and NPM. Obviously if you use MariaDB for anything else it may be problematic, but you could always use the phpMyAdmin tool to perform manual database dumps.

This worked! I was able to just pop the old eMMC in, make a partial backup of just MariaDB and NginxPM, download that to my computer, put the new eMMC back in, upload and restore that backup, and everything is all good now. Not seeing any DB issues, and all six of my proxies are showing up.

**Comment by frenck** [comment]
Closing this issue. It has been fixing in the current development branch. Backups will contain the full package/dataset of the add-on, including all user-data.

../Frenck
