### ISSUE TITLE
Dns resolver issue?

### ISSUE THREAD

**Issue by firestrife23** [hassio-addons/addon-nginx-proxy-manager#49]
# Problem/Motivation

I'm running hass.io on NUC with standalone portainer which is working great and allowed me to add any containers of my choice. However I ran into issue with your NGINX Reverse Proxy Manager when I tried to add custom location to point at another container's hostname it just doesn't work then I ran a nslookup command on hass.io and it failed too...

I made sure the container is in same network as hassio, so what else I might be missing?

## Expected behavior

nslookup hostname should return an ip address.

**Comment by sinclairpaul** [comment]
Just to confirm, you are pulling a container via Portainer, and trying to access it via the docker container name from the NPM addon?

**Comment by firestrife23** [comment]
Yes, and I can access the container directly with local IP and port ex. 192.168.10.10:8181 but I'm trying to setup custom location with NGINX reverse proxy Manager to access the container at https://domain.tld:8181 but it's not working because it cannot find container's hostname within local network such as plex.local.hass.io or just "plex".

hope this make sense

**Comment by sinclairpaul** [comment]
The hassio containers use the DNS server provided by the hassio dns container.  I do not believe that other non hassio docker containers will be resolved via this (@frenck correct me if I am wrong here).  It isn't an issue with this addon, so will close this out.  You can always log an issue with hassio itself.

**Comment by firestrife23** [comment]
Ok, but I'm pretty sure they will say it's the add-on because I was trying to setup custom location. I want to figure out a way to configure my containers to work with hassio dns. So far I set the container to use same network as homeassistant container is on, and set domain to local.hass.io but it still not picking it up so far.

Thank for clarification, I will try my luck at the forum.
