### ISSUE TITLE
Using Sqlite: /config/database.sqlite Uncaught SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by propi62** [hassio-addons/addon-nginx-proxy-manager#509]
# Problem/Motivation
after update to version 1.0.0 proxy manager not working
i use the mariaDB for my homeassistant database.
> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
#507
