### ISSUE TITLE
Add Custom Certificate error

### ISSUE THREAD

**Issue by amamenu** [hassio-addons/addon-nginx-proxy-manager#51]
When I use the "Add Custom Certificate" to upload *.pem&*.key, it promted:

Upload failed: 400

**Comment by sinclairpaul** [comment]
Please follow the issue template and provide logs and further details.

**Comment by frenck** [comment]
Anything in the logs?

**Comment by sinclairpaul** [comment]
No logs so its hard to help, will assume resolved, closing for now.
