### ISSUE TITLE
Login not working after update to 1.0

### ISSUE THREAD

**Issue by silas229** [hassio-addons/addon-nginx-proxy-manager#511]
I updated the addon to v1.0, but I got a 400 error (already using the new default credentials).

<details><summary>Logs</summary>

FROM
internalCompileFunction (node:internal/vm:73:18)wrapSafe (node:internal/modules/cjs/loader:1274:20)Module._compile (node:internal/modules/cjs/loader:1320:27)Module._extensions..js (node:internal/modules/cjs/loader:1414:10)Module.load (node:internal/modules/cjs/loader:1197:32)Module._load (node:internal/modules/cjs/loader:1013:12)Module.require (node:internal/modules/cjs/loader:1225:19)require (node:internal/modules/helpers:177:18)appStart (/opt/nginx-proxy-manager/index.js:7:30)Object.<anonymous> (/opt/nginx-proxy-manager/index.js:43:2)Module._compile (node:internal/modules/cjs/loader:1356:14)Module._extensions..js (node:internal/modules/cjs/loader:1414:10)Module.load (node:internal/modules/cjs/loader:1197:32)Module._load (node:internal/modules/cjs/loader:1013:12)Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)node:internal/main/run_main_module:28:49[15:40:58] INFO: Service Nginx Proxy Manager exited with code 256 (by signal 5)
[15:40:59] INFO: Starting the Manager...
[1/13/2024] [3:41:01 PM] [Global   ] › ℹ  info      Using Sqlite: /config/database.sqlite
Uncaught SyntaxError: Invalid or unexpected token

FROM
internalCompileFunction (node:internal/vm:73:18)wrapSafe (node:internal/modules/cjs/loader:1274:20)Module._compile (node:internal/modules/cjs/loader:1320:27)Module._extensions..js (node:internal/modules/cjs/loader:1414:10)Module.load (node:internal/modules/cjs/loader:1197:32)Module._load (node:internal/modules/cjs/loader:1013:12)Module.require (node:internal/modules/cjs/loader:1225:19)require (node:internal/modules/helpers:177:18)appStart (/opt/nginx-proxy-manager/index.js:7:30)Object.<anonymous> (/opt/nginx-proxy-manager/index.js:43:2)Module._compile (node:internal/modules/cjs/loader:1356:14)Module._extensions..js (node:internal/modules/cjs/loader:1414:10)Module.load (node:internal/modules/cjs/loader:1197:32)Module._load (node:internal/modules/cjs/loader:1013:12)Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)node:internal/main/run_main_module:28:49[15:41:05] INFO: Service Nginx Proxy Manager exited with code 256 (by signal 5)
[15:41:06] INFO: Starting the Manager...
[1/13/2024] [3:41:08 PM] [Global   ] › ℹ  info      Using Sqlite: /config/database.sqlite
Uncaught SyntaxError: Invalid or unexpected token

FROM
internalCompileFunction (node:internal/vm:73:18)wrapSafe (node:internal/modules/cjs/loader:1274:20)Module._compile (node:internal/modules/cjs/loader:1320:27)Module._extensions..js (node:internal/modules/cjs/loader:1414:10)Module.load (node:internal/modules/cjs/loader:1197:32)Module._load (node:internal/modules/cjs/loader:1013:12)Module.require (node:internal/modules/cjs/loader:1225:19)require (node:internal/modules/helpers:177:18)appStart (/opt/nginx-proxy-manager/index.js:7:30)Object.<anonymous> (/opt/nginx-proxy-manager/index.js:43:2)Module._compile (node:internal/modules/cjs/loader:1356:14)Module._extensions..js (node:internal/modules/cjs/loader:1414:10)Module.load (node:internal/modules/cjs/loader:1197:32)Module._load (node:internal/modules/cjs/loader:1013:12)Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)node:internal/main/run_main_module:28:49[15:41:16] INFO: Service Nginx Proxy Manager exited with code 256 (by signal 5)
2024/01/13 15:41:16 [error] 206#206: *11 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.32.1, server: nginxproxymanager, request: "POST /api/tokens HTTP/1.1", upstream: "http://127.0.0.1:3000/tokens", host: "homeassistant.local:81", referrer: "http://homeassistant.local:81/login"
[15:41:17] INFO: Starting the Manager...
[1/13/2024] [3:41:18 PM] [Global   ] › ℹ  info      Using Sqlite: /config/database.sqlite
Uncaught SyntaxError: Invalid or unexpected token

FROM
internalCompileFunction (node:internal/vm:73:18)wrapSafe (node:internal/modules/cjs/loader:1274:20)Module._compile (node:internal/modules/cjs/loader:1320:27)Module._extensions..js (node:internal/modules/cjs/loader:1414:10)Module.load (node:internal/modules/cjs/loader:1197:32)Module._load (node:internal/modules/cjs/loader:1013:12)Module.require (node:internal/modules/cjs/loader:1225:19)require (node:internal/modules/helpers:177:18)appStart (/opt/nginx-proxy-manager/index.js:7:30)Object.<anonymous> (/opt/nginx-proxy-manager/index.js:43:2)Module._compile (node:internal/modules/cjs/loader:1356:14)Module._extensions..js (node:internal/modules/cjs/loader:1414:10)Module.load (node:internal/modules/cjs/loader:1197:32)Module._load (node:internal/modules/cjs/loader:1013:12)Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)node:internal/main/run_main_module:28:49[15:41:23] INFO: Service Nginx Proxy Manager exited with code 256 (by signal 5)

</details>

**Comment by frenck** [comment]
Fixed in v1.0.1, please update.

../Frenck

**Comment by silas229** [comment]
It now works, thank you.

**Comment by frenck** [comment]
No problem! 👍 

../Frenck
