### ISSUE TITLE
Certificates not reacheable / available for AdGuard addon

### ISSUE THREAD

**Issue by deam0n** [hassio-addons/addon-nginx-proxy-manager#518]
# Problem/Motivation

> Adguard needs access to the certificate in order to have SSL implemented.

## Expected behavior

> Configure adguard to fetch fullchain.pem and privkey.pem from /addon_configs/a0d7b954_nginxproxymanager/letsencrypt/live/npm-1/ and be able to retrieve the certificates

## Actual behavior

> adguard cannot retrieve the certificates and displays the error: reading cert file: open /addon_configs/a0d7b954_nginxproxymanager/letsencrypt/live/npm-1/fullchain.pem: no such file or directory

## Steps to reproduce

>  Create a npm with ssl certificates, configure adguard to use it.

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by deam0n** [comment]
Since no solution seems to be found, I'll revert back to last version of the add-on where this was working as expected..

**Comment by renaiku** [comment]
@deam0n the solution has been provided here https://github.com/hassio-addons/addon-bitwarden/issues/294

Don't use nginx as a cert provider, you should use let's encrypt addon for that.

**Comment by deam0n** [comment]
> @deam0n the solution has been provided here [hassio-addons/addon-bitwarden#294](https://github.com/hassio-addons/addon-bitwarden/issues/294)
> 
> Don't use nginx as a cert provider, you should use let's encrypt addon for that.

I'm not using this addon uniquely as a cert provider.

I'm using this addon to create a SSL NPM. Meaning that I create a host and let the addon create the certificate for it as well. This is purely a FS permission issue I guess...

Furthermore, this addon requires the port 443 to be redirected to it, and let's encrypt addon as well so I cannot use both addons.

**Comment by blair287** [comment]
> > @deam0n the solution has been provided here [hassio-addons/addon-bitwarden#294](https://github.com/hassio-addons/addon-bitwarden/issues/294)
> > Don't use nginx as a cert provider, you should use let's encrypt addon for that.
> 
> I'm not using this addon uniquely as a cert provider.
> 
> I'm using this addon to create a SSL NPM. Meaning that I create a host and let the addon create the certificate for it as well. This is purely a FS permission issue I guess...
> 
> Furthermore, this addon requires the port 443 to be redirected to it, and let's encrypt addon as well so I cannot use both addons.

Did you find any solution I found the ssl certs in addon_configs folder but adguard won't accept that file path. Seems no one is interested in hearing our issue I'm using npm to handle the the dns.

Letsencrypt addon won't work as npm is already using the ports so I have no idea how to solve this issue now other than copy and paste them every 3 months

**Comment by deam0n** [comment]
> > > @deam0n the solution has been provided here [hassio-addons/addon-bitwarden#294](https://github.com/hassio-addons/addon-bitwarden/issues/294)
> > > Don't use nginx as a cert provider, you should use let's encrypt addon for that.
> > 
> > 
> > I'm not using this addon uniquely as a cert provider.
> > I'm using this addon to create a SSL NPM. Meaning that I create a host and let the addon create the certificate for it as well. This is purely a FS permission issue I guess...
> > Furthermore, this addon requires the port 443 to be redirected to it, and let's encrypt addon as well so I cannot use both addons.
> 
> Did you find any solution I found the ssl certs in addon_configs folder but adguard won't accept that file path. Seems no one is interested in hearing our issue I'm using npm to handle the the dns.
> 
> Letsencrypt addon won't work as npm is already using the ports so I have no idea how to solve this issue now other than copy and paste them every 3 months

nop.. I just reverted back to the previous version of the addon. #sad
