### ISSUE TITLE
Proxy host to local network router not working anymore

### ISSUE THREAD

**Issue by werfpsa** [hassio-addons/addon-nginx-proxy-manager#525]
# Problem/Motivation

> I have a subdomain with the intention to connect to het local network router (192.168.1.1 with port 80). This was always working, but with the new version I get the 502 Bad Gateway message. The router (Tp-Link ER605) has port forwarding (80 and 443) to the raspberry on which the addon is running. I've tried to play with all proxy host parameter but in all cases the 502 message is displayed.

## Expected behavior

> The domain request to be forwarded to the destination

## Actual behavior

> 502 message

## Steps to reproduce

> Setup the router port forwarding and the proxy host back to the router

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by 3pacdk** [comment]
Plus one,
Or have you solved the problem
