### ISSUE TITLE
can't update custom location

### ISSUE THREAD

**Issue by Morriz** [hassio-addons/addon-nginx-proxy-manager#529]
# Problem/Motivation

It is impossible to update a custom location

## Expected behavior

No errors

## Actual behavior

Errors:
```
Duplicate relation "access_list" in a relation expression. You should use "a.[b, c]" instead of "[a.b, a.c]". This will cause an error in objection 2.0
[1/27/2024] [12:51:44 AM] [Nginx    ] › ⬤  debug     Deleting file: /config/nginx/proxy_host/1.conf
[1/27/2024] [12:51:44 AM] [Nginx    ] › ⬤  debug     Could not delete file: {
  "errno": -2,
  "syscall": "unlink",
  "code": "ENOENT",
  "path": "/config/nginx/proxy_host/1.conf"
}
```

## Steps to reproduce

1. create a custom location
2. check url+path works
3. update custom location path
4. click settings next to it
5. see the custom snippet still reflects old path
6. check logs

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by geezer78** [comment]
same here, 
seems to be related to an upstream issue: [https://github.com/NginxProxyManager/nginx-proxy-manager/issues/3534](url)
it seems a possible workaround is mentioned in issue 3512: [https://github.com/NginxProxyManager/nginx-proxy-manager/issues/3512#issuecomment-1940868886](url)

**Comment by geezer78** [comment]
I guess I was wrong it is actually working!
... noob error:  I forgot the insert the / before the path.
