### ISSUE TITLE
If you have trouble using Studio Code Server via Nginx Proxy Manager and HTTPS, do this.

### ISSUE THREAD

**Issue by avwuff** [hassio-addons/addon-nginx-proxy-manager#530]
Just putting this here in case others have this issue.

In your Proxy Host, go to Custom Locations and put this in:
Location: `/api/hassio_ingress/`
Scheme: `http`
Forwarding location: `homeassistant/api/hassio_ingress/`
Port: 8123

Click the Cog and in the Advanced type:
```
proxy_set_header Host $http_host;
proxy_set_header Origin "";
```

![image](https://github.com/hassio-addons/addon-nginx-proxy-manager/assets/2856227/d8e5bde7-508f-4638-92ac-45062657c7ed)

**Comment by frenck** [comment]
Closing this, as this is not an issue that needs to be resolved.

../Frenck

**Comment by avwuff** [comment]
No worries, I just spent hours trying to figure out the cause of this problem and wanted others to be able to find it.  Cheers!
