### ISSUE TITLE
certbot-dns-plugins.js gets overwritten at reboot

### ISSUE THREAD

**Issue by nevyen** [hassio-addons/addon-nginx-proxy-manager#531]
# Problem/Motivation
There is a new cerbot plugin version for a dns provider. 
I'd like to checked out if this version can solve my problems. 

## Expected behavior

After changing the version in the file /opt/nginx-proxy-manager/global/certbot-dns-plugins.js and rebooting the container the file remains changed.

## Actual behavior

Each time the file is resetted to the orignal "nginx-proxy-manager"-default

## Steps to reproduce

- Exec into the container
- open the file `/opt/nginx-proxy-manager/global/certbot-dns-plugins.js`
- Change a version of a dns plugin
- Save the file
- restart the container

**Comment by tjorim** [comment]
That's expected behaviour. If you want to test changes: fork it, make changes to the Dockerfile and try it out.
