### ISSUE TITLE
Crash after deleting certificate

### ISSUE THREAD

**Issue by Silther** [hassio-addons/addon-nginx-proxy-manager#536]
# Problem/Motivation

> Container is only crashing

## Expected behavior

> It shouldn't crash

## Actual behavior

> it crashes

## Steps to reproduce

> delete a SSL certificate

## Logs

> ```
> You are running the latest version of this add-on.
>  System: Home Assistant OS 11.5  (aarch64 / raspberrypi4-64)
>  Home Assistant Core: 2024.1.6
>  Home Assistant Supervisor: 2024.01.1
> -----------------------------------------------------------
>  Please, share the above information when looking for help
>  or support in, e.g., GitHub, forums or the Discord chat.
> -----------------------------------------------------------
> s6-rc: info: service base-addon-banner successfully started
> s6-rc: info: service fix-attrs: starting
> s6-rc: info: service base-addon-log-level: starting
> s6-rc: info: service fix-attrs successfully started
> s6-rc: info: service base-addon-log-level successfully started
> s6-rc: info: service legacy-cont-init: starting
> s6-rc: info: service legacy-cont-init successfully started
> s6-rc: info: service init-npm: starting
> s6-rc: info: service init-nginx: starting
> s6-rc: info: service init-npm successfully started
> s6-rc: info: service npm: starting
> s6-rc: info: service npm successfully started
> [23:35:54] INFO: Starting the Manager...
> s6-rc: info: service init-nginx successfully started
> s6-rc: info: service nginx: starting
> s6-rc: info: service nginx successfully started
> s6-rc: info: service legacy-services: starting
> [23:35:54] INFO: Starting NGinx...
> s6-rc: info: service legacy-services successfully started
> nginx: [warn] protocol options redefined for 0.0.0.0:443 in /config/nginx/proxy_host/10.conf:14
> nginx: [emerg] cannot load certificate "/etc/letsencrypt/live/npm-25/fullchain.pem": BIO_new_file() failed (SSL: error:80000002:system library::No such file or directory:calling fopen(/etc/letsencrypt/live/npm-25/fullchain.pem, r) error:10000080:BIO routines::no such file)
> [23:35:54] INFO: Service NGINX exited with code 1 (by signal 0)
> s6-rc: info: service legacy-services: stopping
> s6-rc: info: service legacy-services successfully stopped
> s6-rc: info: service nginx: stopping
> s6-rc: info: service nginx successfully stopped
> s6-rc: info: service init-nginx: stopping
> s6-rc: info: service npm: stopping
> s6-rc: info: service init-nginx successfully stopped
> [23:35:55] INFO: Service Nginx Proxy Manager exited with code 256 (by signal 15)
> s6-rc: info: service npm successfully stopped
> s6-rc: info: service init-npm: stopping
> s6-rc: info: service init-npm successfully stopped
> s6-rc: info: service legacy-cont-init: stopping
> s6-rc: info: service legacy-cont-init successfully stopped
> s6-rc: info: service fix-attrs: stopping
> s6-rc: info: service base-addon-log-level: stopping
> s6-rc: info: service fix-attrs successfully stopped
> s6-rc: info: service base-addon-log-level successfully stopped
> s6-rc: info: service base-addon-banner: stopping
> s6-rc: info: service base-addon-banner successfully stopped
> s6-rc: info: service s6rc-oneshot-runner: stopping
> s6-rc: info: service s6rc-oneshot-runner successfully stopped
> ```

**Comment by tjorim** [comment]
How did you delete the certificate? If you want to start clean, make sure to delete the add-on config folder.

**Comment by encryptix** [comment]
I have the same behaviour, I cleaned up some old certs using the npm UI delete functionality. A restart later now wont start because its missing a certificate.

```
nginx: [emerg] cannot load certificate "/etc/letsencrypt/live/npm-11/fullchain.pem": BIO_new_file() failed (SSL: error:80000002:system library::No such file or directory:calling fopen(/etc/letsencrypt/live/npm-11/fullchain.pem, r) error:10000080:BIO routines::no such file)
```

**Comment by bocklucas** [comment]
> How did you delete the certificate? If you want to start clean, make sure to delete the add-on config folder.

Starting clean helped me, i.e.

```
cd /addon_configs
ls -la
rm -r [hash]_nginxproxymanager
```

Kind of a bummer to start from scratch again but hoping someone figures out a better solution to this
