### ISSUE TITLE
Feature request: Quic support

### ISSUE THREAD

**Issue by WhippingBoy01** [hassio-addons/addon-nginx-proxy-manager#538]
# Problem/Motivation

Add support for the quic protocol

> (Why the issue was filed)

## Expected behavior
Be able to listen on 445/udp
And use quic/https/3
> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by WhippingBoy01** [comment]
Thx for a lot of great stuff in home assistant by the way.

**Comment by sinclairpaul** [comment]
The addon installs the upstream app from <https://github.com/NginxProxyManager/nginx-proxy-manager> the request would need to be implemented there.
