### ISSUE TITLE
Support internal link for UI

### ISSUE THREAD

**Issue by pdugas** [hassio-addons/addon-nginx-proxy-manager#541]
https://github.com/hassio-addons/addon-nginx-proxy-manager/blob/c0424487347e41f3f5328839a02193792505fc3f/proxy-manager/config.yaml#L8C1-L9C1

Not sure how common this is but I have HA behind NPM and when I click the link in this addon's UI, it leads to the internal port on the external host.  I wonder if HA's addon scheme supports using something other than `[HOST]` here.

**Comment by frenck** [comment]
Home Assistant doesn't support anything else.

As this is not an add-on issue or limitation, I'll go ahead and close this one up here.

../Frenck

**Comment by pdugas** [comment]
Wonder about using the ingress feature.
