### ISSUE TITLE
Feature Request: UI should reflect manual changes made in the config file upon reload / restart. 

### ISSUE THREAD

**Issue by Alphaemef** [hassio-addons/addon-nginx-proxy-manager#549]
## Problem/Motivation
_Would be great if manual edit of the config files would translate into the UI. Some changes are better suited in the config files, while some tweaks are easier / more suitable for the UI._ 

## Expected behavior
_When editing the config file, upon load / restart the UI should reflect the changes made in the config. And when updating the UI settings, this should update the config files and retain the manual edits as well._ 

## Actual behavior
_When the config file is edited, the behaviour of the add-on seems appropriate, but the changes are Not reflected in the UI. And any edit of the configuration in the UI will reset the config files and thus also the add-on behaviour._ 

## Steps to reproduce
See above. 

## Proposed changes
See above.

**Comment by frenck** [comment]
Hi there @Alphaemef 👋 

Thanks for your suggestion; however, your request is not something the add-on can achieve. Add-ons wrap existing software, in this case, the NGINX Proxy Manager. If you want changes in the piece of software, please request that feature upstream instead.

../Frenck
