### ISSUE TITLE
Access list not applied to custom locations

### ISSUE THREAD

**Issue by C4KEW4LK** [hassio-addons/addon-nginx-proxy-manager#55]
# Problem/Motivation

Proxy Host "Custom Locations" do not follow Access List restrictions

## Expected behavior

Custom Locations should share access list restrictions with main proxy host.

## Actual behavior

When Access List is applied to the main proxy host it is not carried over to custom locations

## Steps to reproduce

Apply access list to proxy host and add custom location. Access to custom location is unrestricted.

## Proposed changes

When Access List is applied to the main proxy host it is carried over to custom locations.

**Comment by sinclairpaul** [comment]
Please see the upstream issue https://github.com/jc21/nginx-proxy-manager/issues/148
