### ISSUE TITLE
Add extra network ports in add-on settings

### ISSUE THREAD

**Issue by ajarillo1981** [hassio-addons/addon-nginx-proxy-manager#553]
# Problem/Motivation

After configuring a Stream in Nginx Proxy Manager the traffic redirection is not working for that port. The cause is the port defined in the Stream is not configured in docker and there is not an option to configure it in add on settings. 
I have tested in a external virtual machine with docker and after including the port in docker-compose.yml, the redirection works. 

## Expected behavior

Include option to add extra ports in add-on settings.

## Actual behavior

Currently, it is no possible add more ports than http, https, and 81 for admin config

## Steps to reproduce

Tested in a virtual machine with docker installed to confirm the cause.

## Proposed changes

Include option to add extra ports in add-on settings.

**Comment by Nab0y** [comment]
I support the request, but due to the inability to forward additional ports, I cannot redirect requests to my mail server in the local network. https://github.com/NginxProxyManager/nginx-proxy-manager/issues/1110#issuecomment-1663807216

**Comment by frenck** [comment]
No planned. Use regular port forwarding in that case. There is nothing this add-on will offer additionally.
