### ISSUE TITLE
Some kind of container or database connection issue

### ISSUE THREAD

**Issue by theukedge** [hassio-addons/addon-nginx-proxy-manager#565]
# Problem/Motivation

I only started using NPM at v1.0.0, so this is not a 0.x→1.x upgrade issue. It seemed to happen after upgrading from 1.0.0 to 1.0.1, but I can't be certain. I store all of my passwords in a password manager, so I am certain that my username/password is correct. However, now, I can't log in to NPM, I can't downgrade, I can't even uninstall and reinstall the add-on. Several things make me think the add-on cannot properly connect to or use the database, or that there's something weird going on with the Docker container:

1. The version number on the login screen shows 0.0.0
2. When I uninstall the add-on and then re-install it, it continues to work as it previously did, i.e. all of the old data is still there, and it continues to use it
3. When I enter my login credentials, I get the error message `Invalid password`. If I intentionally enter an incorrect password, I get the same error message. If I change the email address of the login by dropping a letter, I get the error message `No relevant user found`.
4. The plugin continues to operate normally for now (even after deleting and reinstalling a fresh version), but I can't make any changes since I can't log in.

Running Home Assistant OS on [Home Assistant Green](https://www.home-assistant.io/green).

## Expected behavior

To be able to log in, or cleanly remove the add-on and be able to reinstall it fresh.

## Actual behavior

I am given an error when trying to log in (while being certain that the credentials are correct), and not fully deleting the add-on while trying to reinstall it.

## Steps to reproduce

Upgrade from 1.0.0 to 1.0.1 and try to access the add-on.

## Proposed changes

Unknown

## Screenshots

![Screenshot 2024-04-19 at 9 07 42 AM](https://github.com/hassio-addons/addon-nginx-proxy-manager/assets/3171242/a42eb0e7-d31e-4b9d-80e6-c58aef0ffa4c)
![Screenshot 2024-04-19 at 9 18 12 AM](https://github.com/hassio-addons/addon-nginx-proxy-manager/assets/3171242/6a3b5b29-b8fb-488f-8c8e-96e9b43d386b)
![Screenshot 2024-04-19 at 9 08 09 AM](https://github.com/hassio-addons/addon-nginx-proxy-manager/assets/3171242/18529e4d-33fd-40e2-862c-e44ad0a5f683)
![Screenshot 2024-04-19 at 9 08 35 AM](https://github.com/hassio-addons/addon-nginx-proxy-manager/assets/3171242/30f77117-6160-4a32-b232-f65ac5c69c7b)
![Screenshot 2024-04-19 at 9 09 37 AM](https://github.com/hassio-addons/addon-nginx-proxy-manager/assets/3171242/43296c5f-ec21-41bc-b94d-e17aeb6f1b85)
![Screenshot 2024-04-19 at 9 09 47 AM](https://github.com/hassio-addons/addon-nginx-proxy-manager/assets/3171242/7f0b8fb1-d71d-42a0-a5e2-8685302a63a3)

**Comment by corvy** [comment]
I would make a copy of all the configs in the addon_configs folder (/addon_configs/a0d7b954_nginxproxymanager) and reinstall and set everything up fresh. Alternatively try to reset the username/password in the sqlitedatabase directly.
