### ISSUE TITLE
how do I reset the addon as I cant remember the password or email used for user please 

### ISSUE THREAD

**Issue by vjmaz** [hassio-addons/addon-nginx-proxy-manager#566]
# Problem/Motivation

Just want to know why I cant reset the whole install easily please as when I changed my email and password after i just setup from 

default user: admin@example.com
default pass: changeme

I cant log on at all !!! 
 Please help

**Comment by corvy** [comment]
First backup :)

Delete the addon and reinstall. All the config is in this folder /addon_configs/a0d7b954_nginxproxymanager, not sure if it gets deleted but if reinstall does not clear it, then delete the folder before reinstall. 

If you are tech savvy you probably could open the database.sqlite in the aforementioned folder and edit it with DB Browser for SQLite. I see that there is an auth table with an encrypted password. Maybe that could be deleted or recreated. Not sure :) 

I would delete it all and start over.

**Comment by vjmaz** [comment]
Thank you Corvy , I`m not that tech savy , but I do understand what your asking ... The good news is I am doing a fresh install anyway.
