### ISSUE TITLE
Increase Forward hostname under the Custom Locations tab to above 50

### ISSUE THREAD

**Issue by potgieterdl** [hassio-addons/addon-nginx-proxy-manager#57]
# Problem/Motivation
I'm trying to create a forward to my camera internal to the network. I'm using a snapshot of the image to attach to a telegram message that i sent out when someone presses my front door bell.

Its rather lenght
http://x.x.x.x/cgi-bin/api.cgi?cmd=Snap&channel=0&rs=wuuPhkmUCeI9WG7C&user=xxx&password=xxx

Ie, Custom Locations doesnt allow a hostname longer than 50 characters.

## Expected behavior

increase to 100?

## Actual behavior

pop warning that max length is 50.

## Steps to reproduce

Create a proxy host, click settings, custom locations.
Then click add location and try to enter a ```"Forward Hostname / IP"``` longer than 50

## Proposed changes

increase it to a higher sensible limit

**Comment by sinclairpaul** [comment]
In the example you gave, x.x.x.x is the hostname

**Comment by sinclairpaul** [comment]
Just to add on this, in your example, you would likely do the following under Custom Locations to achieve what I believe you want.

![image](https://user-images.githubusercontent.com/24625998/70945410-21215c00-2023-11ea-9e37-d3eca5b8656d.png)
