### ISSUE TITLE
Upgrade NPM to version 2.11.2

### ISSUE THREAD

**Issue by corvy** [hassio-addons/addon-nginx-proxy-manager#570]
The new release includes new functionality like the ability to do geofencing based on IP. 
https://github.com/NginxProxyManager/docker-nginx-full/pull/28

More infomation here: https://github.com/NginxProxyManager/nginx-proxy-manager/issues/46#issuecomment-2084928620

Hope this could be considered :) 👍

**Comment by tjorim** [comment]
This is a feature request, not an issue. PR #526 is already created to upgrade the NPM version.
