### ISSUE TITLE
Streams on income port are not working as container doesn't use host network or expose custom ports 

### ISSUE THREAD

**Issue by grest** [hassio-addons/addon-nginx-proxy-manager#582]
# Problem/Motivation

I'd like to create the stream to be used by the cloudflare tunnel and redirect incoming port 2095 to 1883 port on ha instance, to ultimately expose mqtt outside of my network. Unfortunately it won't work as proxy manager docker exposes only 3 ports defined on current configuration page

## Expected behavior
Use host network or provide additional ports in configuration page and use it when starting docker container

## Actual behavior
Cloudflare tunnel with external service configuration on port 2095 doesn't work

**Comment by grest** [comment]
https://github.com/hassio-addons/addon-nginx-proxy-manager/issues/553 - I see it was proposed before. Why cannot you add this option?

**Comment by tjorim** [comment]
Duplicate, feel free to fork the project and make those changes yourself.
