### ISSUE TITLE
Feature Request - use wildcard certs from Duckdns addon as custom certs

### ISSUE THREAD

**Issue by Buckeyes02** [hassio-addons/addon-nginx-proxy-manager#59]
# Problem/Motivation

This addon does not support obtaining wildcard certs from Letsencrypt.  

## Proposed changes

It would be nice if there was an option to use the certs generated by the duckdns addon as custom certs in this addon similar to how other addons can use the certs (fullchain.pem and privkey.pem).

Thanks

**Comment by sinclairpaul** [comment]
You will need to open this upstream at https://github.com/jc21/nginx-proxy-manager

The addon is a wrapper for the software.

**Comment by Buckeyes02** [comment]
My proposed solution is hass.io specific.  The author for the nginx-proxy-manager project doesn't seem interested in supporting wildcard certs as it makes things less "simple" for the user.  I thought it might be easier that have the addon import the certs that are already in /ssl from the duckdns addon (which does support wildcard).

**Comment by sinclairpaul** [comment]
There is an import option in the UI, does that work for you?

**Comment by Buckeyes02** [comment]
That does work, however, it is not a simple procedure to pull the certs out of /ssl to then import them through the UI and the fact that they will not auto update when the duckdns addon renews the certs.  I understand if something like I am asking is too much work.  I am not very familiar with how easy or difficult it is for addons/containers to share files/interact with each other (trying to learn).  Just thought it might be a simple and user friendly solution.

**Comment by sinclairpaul** [comment]
The app also uses a database for its config, when a cert is uploaded a record is created (thats why you can give the cert a name and its referenced elsewhere in the app).  As there is no API to do that, unfortunately it would be challenging to do automatically.  

There is always the option of using the nginx addon, Nabu Casa or even a separate reverse proxy.

**Comment by Buckeyes02** [comment]
Ah, that makes sense.  I will look into my other options.  Thank you for your time and insight.
