### ISSUE TITLE
Fails to start after 3.10.0 update:  Missing option 'real_ip_from'

### ISSUE THREAD

**Issue by phipolis** [hassio-addons/addon-nginx-proxy-manager#594]
Updating from 3.9.0 -> 3.10.0 leaves nginx-proxy-manager addon unable to start.

Config screen and documentation give the impression this is optional. Error message is ` Missing option 'real_ip_from' in root in NGINX Home Assistant SSL proxy (core_nginx_proxy). `

Was able to work around by adding a "real IP from" config entry, saving, removing it, and saving again. Addon will now start successfully.

**Comment by sinclairpaul** [comment]
I believe you are referring to the Home Assistant nginx addon for which the repo is at <https://github.com/home-assistant/addons>
