### ISSUE TITLE
Stream TCP proxy does not work

### ISSUE THREAD

**Issue by PatrikTrestik** [hassio-addons/addon-nginx-proxy-manager#597]
# Problem/Motivation

> Stream host forward configuration which worked in v0.x does not work in v1.x. 

## Expected behavior

> TCP forwarding works as it does on standalone NPM.

## Actual behavior

> Port is not mapped to docker container. No option to add custom TCP port.

## Steps to reproduce

> Create stream host config for any service. For example FTP (TCP port 21).
> My requirement is MQTT TCP 1884 port forward.

## Proposed changes

> If addon runs in host network mode, all ports should propagate. "host_network: true"
> I tryied to test in forked repo but without success.

**Comment by sinclairpaul** [comment]
See #553

**Comment by PatrikTrestik** [comment]
I probably missing something.
 Is there a way to use tcp forward in addon? 

What does it mean "use regular port forwarding"?
How can I open another port in add on?
