### ISSUE TITLE
No Relevant User

### ISSUE THREAD

**Issue by floodwayprintco** [hassio-addons/addon-nginx-proxy-manager#603]
# Problem/Motivation

I cannot configure, because I cannot access the WebUI. Default login doesn't work.

## Expected behavior

admin@example.com and changeme should log me in.

## Actual behavior

No relevant user.

## Steps to reproduce

Install add-on, start it up, try to access web ui.

## Proposed changes

I have seen there is a way to edit the database? Perhaps a clear instruction on how to 'reset' this add-on would help.

**Comment by justintrann** [comment]
Here is what I did to log in for the first time with admin@example.com and changeme credential.
1. Exec to nginxproxymanager container, ex: `docker exec -it addon_a0d7b954_nginxproxymanager bash`
2. Remove SQLite Database: `rm /opt/nginx-proxy-manager/config/database.sqlite`
3. Escape from the exec session then restart the container, ex: `docker restart addon_a0d7b954_nginxproxymanager`

**Comment by floodwayprintco** [comment]
Thank you all. For me at least, the issue is resolved because I ditched it all and went with Tailscale. I thought VPN would be the complex option based on threads I've seen in the past. 

Looking at this NGINX stuff though it seems this admin issue is pretty common headache people have so I still appreciate you helping out and I hope this thread helps someone in the future or gets the issue resolved in the UI.
