### ISSUE TITLE
Unable to use Lets Encrypt. Test server connection doesnt work.

### ISSUE THREAD

**Issue by akballow** [hassio-addons/addon-nginx-proxy-manager#604]
# Problem/Motivation

I noticed my certs have expired and when i visited the ngnix management ui i see that the renew and test server fail with errors.

## Expected behavior

I expect that if port 443 and 80 are open to my HA IP that the Lets Encrypt certs will automatically renew and the test buttons will work.
## Actual behavior

Certs to not renew and the test button does not work

## Steps to reproduce

Click Lets encrypt cert and select renew or test server connection. Internal error or "Communication with the API failed, is NPM running correctly?" display

Currently running ngnix proxy manager Current version: 1.0.1 on HA 2024.10.1

The logs show

`[09/Oct/2024:16:48:57 -0700] - 200 200 - GET https XXXX.XXXXXXX.com "/api/hassio/addons/a0d7b954_nginxproxymanager/logs" [Client 165.225.242.177] [Length 4431] [Gzip -] [Sent-to 192.168.1.188] "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36" "https://XXXXXXX.XXXXXXXX.com/hassio/addon/a0d7b954_nginxproxymanager/logs"
[10/9/2024] [4:49:21 PM] [SSL      ] › ℹ  info      Testing http challenge for XXXXXXX.XXXXXXXXXX.com
Uncaught SyntaxError: Unexpected end of JSON input

FROM
2024/10/09 16:49:22 [error] 575#575: *1174 upstream prematurely closed connection while reading response header from upstream, client: 192.168.1.65, server: nginxproxymanager, request: "GET /api/nginx/certificates/test-http?domains=%5B%22akballow.asuscomm.com%22%5D HTTP/1.1", upstream: "http://127.0.0.1:3000/nginx/certificates/test-http?domains=%5B%XXXXXXXX.XXXXXXXXX.com%22%5D", host: "192.168.1.188:81", referrer: "http://192.168.1.188:81/nginx/certificates"
JSON.parse (<anonymous>)IncomingMessage.<anonymous> (/opt/nginx-proxy-manager/internal/certificate.js:1178:31)IncomingMessage.emit (node:events:529:35)endReadableNT (node:internal/streams/readable:1400:12)process.processTicksAndRejections (node:internal/process/task_queues:82:21)`

**Comment by robbionline** [comment]
Is this maybe connected to the issue that ipv6 is not working? Do you have a DS-lite connection via your ISP?
