### ISSUE TITLE
Addon State Binary Sensor Missing

### ISSUE THREAD

**Issue by M0uC0** [hassio-addons/addon-nginx-proxy-manager#605]
# Problem/Motivation

> I have a group helper with all the mandatory addons "*_running" entities so that when this group changes to "off" i get a notification that something is not ok with Home Assistant.
Nginx Proxy Manager is on my "Mandatory" category... but it doesn't have this kind of binary_sensor.

## Expected behavior

> Example of other addons with binary_sensor available:

binary_sensor.mosquitto_broker_running
binary_sensor.adguard_home_running
binary_sensor.duck_dns_running
binary_sensor.mariadb_running

## Actual behavior

> Nginx only has available - "update.nginx_proxy_manager_update"

## Steps to reproduce

> Search at Developer Tools - States with "nginx" (only showing _update) or "running" (showing all the other addons that have it available).

## Proposed changes

> Is it possible to be implemented?

**Comment by frenck** [comment]
> Addon State Binary Sensor Missing

That is not an add-on issue. Add-ons do not provide entities; Home Assistant does.
You are mixing up terminology. Please report this issue with the Home Assistant project instead.

../Frenck

**Comment by M0uC0** [comment]
Sorry.. my bad.
Thought it was addon related.
