### ISSUE TITLE
Let's Encrypt

### ISSUE THREAD

**Issue by firestrife23** [hassio-addons/addon-nginx-proxy-manager#61]
# Problem/Motivation

Unable to validation due to ISP blocking port 80

## Expected behavior

Let’s Encrypt offers three validation methods. One of them requires inbound TCP port 443, while another requires inbound TCP port 80. You cannot choose another port and you cannot use UDP instead of TCP.

The third method requires the ability to create requested records in your DNS zone in order to prove that you have control over the DNS records for your domain name. Can you add support for third method?

**Comment by frenck** [comment]
That is not a feature the add-on can provide.
Add-ons wrap existing applications, feel free to submit a feature request to the Nginx Proxy Manager repository.
