### ISSUE TITLE
No name server

### ISSUE THREAD

**Issue by roblandry** [hassio-addons/addon-nginx-proxy-manager#64]
arch | x86_64
-- | --
dev | false
docker | true
hassio | true
os_name | Linux
python_version | 3.7.5
timezone | America/New_York
version | 0.103.5
virtualenv | false

latest version of plugin

# Problem/Motivation

After running for some time i lose access to domain names. 

## Expected behavior

Not to lose access. Honestly i am not sure if the issue lies with this plugin, or rather hassio.

## Actual behavior

I am not sure what causes it to happen. The only initital errors in the logs is unable to connect to any of the hosts defined in nginx. Naturally I restart the plugin to attempt to correct the problem.

Restarting the plugin then causes this error in the logs (repeats indefinately).
```
[17:29:59] INFO: Starting NGinx...
nginx: [emerg] no name servers defined in /etc/nginx/conf.d/include/resolvers.conf:2
```

Logging into the docker and viewing resolvers.conf:
```
# Hass.io Resolver
resolver  ipv6=off;
```

Finding the hassio_dns docker container dns ip address:
```
docker inspect --format='{{.Name}} {{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(docker ps -q)
...
/hassio_dns 172.30.32.3
...
```

And then manually adding it back:
```
# Hass.io Resolver
resolver 172.30.32.3 ipv6=off;
```

Resolves the issue.

However, this is only a bandaid to the actual issue. I am not sure where the dns address is getting lost causing the plugin to no longer function correctly. I am sure the issue is not limited to this plugin, but i am not sure where to begin tracing the root issue.

There are no errors in hassio_supervisor logs.
There are no errors in hassio_dns logs.

This is the 2nd time ive run into this issue. Yesterday i resolved by restarting my linux computer as i was unable to correct via docker restarts.

I will update if any additional information can be collected next time the problem arises.

## Steps to reproduce

Im not sure.

**Comment by sinclairpaul** [comment]
What OS do you run on?, the resolver is added on startup via a call ti the supervisor.  Any firewall involved?

**Comment by roblandry** [comment]
No firewall.
Ubuntu 19.04 currently.

I actually had to restart the server as it was slightly functioning.
Login was hit or miss.
Some domains were working, some were not.

**Comment by sinclairpaul** [comment]
It looks like there are a couple of issues:

The hassio dns fails to respond at a certain point, although its a bit confusing as to why some entries responded (is it specific to docker dns names?)

The call to get the dns fails, @frenck should bashio fail if the return is null, if not is it worth adding this?

**Comment by roblandry** [comment]
It was running. I pulled logs to make sure and everything looked fine. Next time it has an issue I will try restarting DNS and see what happens overall. And I agree that the functional domains could very well be cached.

**Comment by frenck** [comment]
The DNS server is provided by the Hass.io API. It has a DNS server running, without it, You would have tons of more issue.
If the DNS server call fails, it should be visible in the add-on logs.

I don't see how this call could fail or result in an empty result set. Please check your logs again for hints.

**Comment by roblandry** [comment]
So I think my issue goes deeper intothe host os. I am not sure where the issue comes from, or what is causing it, but have at least tracked it away from this plugin.

As you can see, something is very wrong...
```
$ ping -c2 github.com
ping: github.com: Temporary failure in name resolution
```

Today i restarted Network Manager and it appeared to resolve the issue. It appears in the logs that network manager stops working for some reason...

```
Jan 16 10:58:13 ZEUS dhclient[8729]: receive_packet failed on veth1409c7e: Network is down
Jan 16 10:58:14 ZEUS NetworkManager[1724]: <info>  [1579190294.0029] device (veth1409c7e): state change: ip-config -> unmanaged (reason 'unmanaged', sys-iface-state: 'removed')
Jan 16 10:58:14 ZEUS NetworkManager[1724]: <info>  [1579190294.0430] dhcp4 (veth1409c7e): canceled DHCP transaction, DHCP client pid 8729
Jan 16 10:58:14 ZEUS NetworkManager[1724]: <info>  [1579190294.0434] dhcp4 (veth1409c7e): state changed unknown -> done
Jan 16 15:00:42 ZEUS systemd[1]: Stopping Network Manager...
Jan 16 15:00:42 ZEUS NetworkManager[1724]: <info>  [1579204842.1454] caught SIGTERM, shutting down normally.
...
Jan 16 15:00:52 ZEUS systemd[1]: NetworkManager.service: Succeeded.
Jan 16 15:00:52 ZEUS systemd[1]: Stopped Network Manager.
Jan 16 15:00:52 ZEUS systemd[1]: Starting Network Manager...
Jan 16 15:00:52 ZEUS NetworkManager[27958]: <info>  [1579204852.7022] NetworkManager (version 1.16.0) is starting... (after a restart)
Jan 16 15:00:52 ZEUS NetworkManager[27958]: <info>  [1579204852.7024] Read config: /etc/NetworkManager/NetworkManager.conf (lib: 10-dns-resolved.conf, 20-connectivity-ubuntu.conf, no-mac-addr-change.conf)
Jan 16 15:00:52 ZEUS NetworkManager[27958]: <warn>  [1579204852.7024] config: unknown key 'wifi.cloned-mac-address' in section [device-mac-addr-change-wifi] of file '/usr/lib/NetworkManager/conf.d/no-mac-
Jan 16 15:00:52 ZEUS NetworkManager[27958]: <warn>  [1579204852.7024] config: unknown key 'ethernet.cloned-mac-address' in section [device-mac-addr-change-wifi] of file '/usr/lib/NetworkManager/conf.d/no-
Jan 16 15:00:52 ZEUS systemd[1]: Started Network Manager.
```

**Comment by sinclairpaul** [comment]
Will close this out, as there really isn't anything we can do from the add on perspective.  From a troubleshooting point of view the only thing I can suggest is try a static address if you are using DHCP.
