### ISSUE TITLE
I cant Install AMD

### ISSUE THREAD

**Issue by d4icon** [hassio-addons/addon-nginx-proxy-manager#68]
# Problem/Motivation

I cant install:

20-01-31 23:38:01 INFO (SyncWorker_2) [hassio.docker.interface] Pull image hassioaddons/nginxproxymanager-amd64 tag 0.4.0.
20-01-31 23:38:19 ERROR (SyncWorker_2) [hassio.docker.interface] Can't install hassioaddons/nginxproxymanager-amd64:0.4.0 -> 404 Client Error: Not Found ("no such image: hassioaddons/nginxproxymanager-amd64:0.4.0: No such image: hassioaddons/nginxproxymanager-amd64:0.4.0").

**Comment by sinclairpaul** [comment]
Docker throwing a 404 is generally, name resolution (i.e. it cannot locate the image to download) or disk space (in that it doesn't have enough room to download and launch).

Please validate both of these, it's not an issue with the addon itself.
