### ISSUE TITLE
When I add the SSL certificate a "Internal error" occurs.

### ISSUE THREAD

**Issue by swaftrade** [hassio-addons/addon-nginx-proxy-manager#69]
# Problem/Motivation
Hello.
I am new to programming and a home assistant.
When you add an SSL certificate, an "Internal error" occurs.
I did everything according to the instructions.
Ports 80 and 431 are forwarded to the local IP address on port 8123.
Please help me with this problem.
Sorry for my english, i use google translator.

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by crdsilva17** [comment]
I got the same error when trying to generate a certificate. I realized that even with the error it shows as if the certificate had been generated, however when adding the "newly generated" certificate it starts to indicate offiline system.

**Comment by Valen13776** [comment]
I got the same error.

**Comment by Sholofly** [comment]
Same here @ startup:

```
[4/11/2020] [12:18:25 AM] [Migrate  ] › ℹ  info      Current database version: 20190227065017
[4/11/2020] [12:18:25 AM] [Setup    ] › ℹ  info      Creating a new JWT key pair...
[4/11/2020] [12:18:34 AM] [Setup    ] › ℹ  info      Wrote JWT key pair to config file: /opt/nginx-proxy-manager/config/production.json
[4/11/2020] [12:18:34 AM] [Setup    ] › ⚠  warning   Restarting interface to apply new configuration
[00:18:34] INFO: Starting the Manager...
[4/11/2020] [12:18:36 AM] [Migrate  ] › ℹ  info      Current database version: 20190227065017
[4/11/2020] [12:18:36 AM] [IP Ranges] › ℹ  info      Fetching IP Ranges from online services...
[4/11/2020] [12:18:36 AM] [IP Ranges] › ℹ  info      Fetching https://ip-ranges.amazonaws.com/ip-ranges.json
[4/11/2020] [12:18:36 AM] [IP Ranges] › ℹ  info      Fetching https://www.cloudflare.com/ips-v4
[4/11/2020] [12:18:36 AM] [IP Ranges] › ℹ  info      Fetching https://www.cloudflare.com/ips-v6
[4/11/2020] [12:18:36 AM] [SSL      ] › ℹ  info      Let's Encrypt Renewal Timer initialized
[4/11/2020] [12:18:36 AM] [SSL      ] › ℹ  info      Renewing SSL certs close to expiry...
[4/11/2020] [12:18:36 AM] [IP Ranges] › ℹ  info      IP Ranges Renewal Timer initialized
[4/11/2020] [12:18:36 AM] [Global   ] › ℹ  info      Backend PID 588 listening on port 3000 ...
[4/11/2020] [12:18:37 AM] [Nginx    ] › ℹ  info      Reloading Nginx
[4/11/2020] [12:18:37 AM] [SSL      ] › ℹ  info      Renew Complete
[4/11/2020] [12:18:37 AM] [SSL      ] › ✖  error     Certificate is not valid (Command failed: openssl x509 -in /etc/letsencrypt/live/npm-6/fullchain.pem -subject -noout
Can't open /etc/letsencrypt/live/npm-6/fullchain.pem for reading, No such file or directory
140643184139592:error:02001002:system library:fopen:No such file or directory:crypto/bio/bss_file.c:69:fopen('/etc/letsencrypt/live/npm-6/fullchain.pem','r')
140643184139592:error:2006D080:BIO routines:BIO_new_file:no such file:crypto/bio/bss_file.c:76:
unable to load certificate
```

**Comment by hav10** [comment]
I found my internal error when regenerating a new cert was router firewall related.

**Comment by island-automator** [comment]
> # Problem/Motivation
> Ports 80 and 431 are forwarded to the local IP address on port 8123.

The problem is that you are redirecting the external traffic to the port of your home assistant.

Make sure you route the traffic from port 80 and 443 to your IP of home assistant and to the ports 80 and 443. The Nginx proxy manager add-on will be running on port 443 and 80. 

In the Nginx proxy manager, you are able to set up a redirect to your home assistant IP with the port 8123.

**Comment by kamontat** [comment]
I have the same error. 

I add port forwarding from external to my HA instances at `xxx.yyy.zzz.100` and open both 80/443
![Shot-2563-05-02_23 21 21](https://user-images.githubusercontent.com/14089557/80869623-b750d880-8ccb-11ea-949c-5a5604049194.png)

But I still get same error in addon logs

```
[5/2/2020] [11:18:10 PM] [SSL      ] › ✖  error     Certificate is not valid (Command failed: openssl x509 -in /etc/letsencrypt/live/npm-6/fullchain.pem -subject -noout
Can't open /etc/letsencrypt/live/npm-6/fullchain.pem for reading, No such file or directory
547973594680:error:02001002:system library:fopen:No such file or directory:crypto/bio/bss_file.c:69:fopen('/etc/letsencrypt/live/npm-6/fullchain.pem','r')
547973594680:error:2006D080:BIO routines:BIO_new_file:no such file:crypto/bio/bss_file.c:76:
unable to load certificate
)
```

**Comment by island-automator** [comment]
> I add port forwarding from external to my HA instances at `xxx.yyy.zzz.100` and open both 80/443
Your port forwarding settings look correct, even though I cannot check the IP Adress of your home assistant but I assume that it correct ;) 

@kamontat just to be sure is your add-on HTTPS/HTTP/SSL Entrance set to 443 and 80 in the Network section?

Also, do you have the Letsencrypt add-on installed? just to be sure can you uninstall it and try configuring the Nginx proxy manager again?

**Comment by kamontat** [comment]
I already have a workaround. I think it because the DNS didn't update the record immediately. I create a new A record on my DNS provider and wait a couple of hours. It works.

**Comment by island-automator** [comment]
Yes, that usually takes sometime before it gets picked up.

**Comment by kamontat** [comment]
Yesterday, after I tried couple way, I thinks create ssl certificates first and proxy later is better. ;)

**Comment by flipepiloto** [comment]
I had the same issue

1 - Create on my router a port targeting the 80 external to 80 internal and 443 external to 443 internal.
2 - Install the Nginx Proxy Manager Addon and start
3 - Create a host as it says in the manual and I created a creation then SSL, for example, an internal error and the log below

[5/6/2020] [2:50:27 PM] [Nginx    ] › ℹ  info      Reloading Nginx
[5/6/2020] [2:50:27 PM] [SSL      ] › ℹ  info      Requesting Let'sEncrypt certificates for Cert #10: xyz.duckdns.org
[5/6/2020] [2:50:50 PM] [Nginx    ] › ℹ  info      Reloading Nginx
[5/6/2020] [2:50:50 PM] [Express  ] › ⚠  warning   Command failed: /usr/bin/certbot certonly --non-interactive --config "/etc/letsencrypt.ini" --cert-name "npm-10" --agree-tos --email "xyz@gmail.com" --preferred-challenges "dns,http" --webroot --domains "xyz.duckdns.org" 
Saving debug log to /data/logs/letsencrypt/letsencrypt.log
Plugins selected: Authenticator webroot, Installer None
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for xyz.duckdns.org
Using the webroot path /data/letsencrypt-acme-challenge for all unmatched domains.
Waiting for verification...
Challenge failed for domain xyz.duckdns.org
http-01 challenge for xyz.duckdns.org
Cleaning up challenges
Some challenges have failed.

There is any solution ?

**Comment by kamontat** [comment]
My suggestion is 

1. delete all proxy first.
2. update dns point to your HA instance `A abc.xyz.duckdns.org 111.111.123.123`
3. wait for couple hours (1-2 hours should be enough)
4. create new SSL certificate FIRST with the domain that you create on step 2
5. after SSL create complete, add new proxy setting with existed SSL.

**Comment by frenck** [comment]
## ⚠️ This is always either of the following:

- You haven't correctly set up port forwarding from your router on port 80 & 443. Your SSL cert creation will fail if you didn't do that right.
- Your provider doesn't allow for opening up port 443 or 80. This means this add-on is not for you.
- You are behind a GCNAT, sorry to hear that. This add-on is not for you.

**Comment by IanAdd** [comment]
My ssl certificate shows an expiry date time that is in the past. If I hit renew it report 'internal error'. Where to go next to sort this out??

**Comment by SPEC1AL1ST** [comment]
502 Bad Gateway

to reproduce:

https://dummylabs.com/ru/post/2020-01-27-the-easiest-way-to-https-home-assistant/

**Comment by weirders** [comment]
Hmm, possibly interesting observation from my end. I'm running into the same issues.

Since my provider's router doesnt properly do hairpinning/NAT loopback, I've got DNSmasq entries internally on 2 domains, duckdns domain (my.duckdns.org) & my private domain (Example.com).  example.com is DNS CNAMED to my.duckdns.org.

I cannot get a working SSL-certificate for x.example.com, however, I can get a working SSL-certificate to x.my.duckdns.org. This indicates to me its definitely not a port forwarding/blocking issue. 

Anyone know what's going on? Is letsencrypt failing due to the CNAME forward? Anything I can do to fix?

**Comment by hoeiendag** [comment]
I got the same problem. Cert for duckdns.org works instantly, not for hoeiendag.nl or www.hoeiendag.nl. Port forwardings are ok. 
I deleted the add on, did a reset_database: true. No luck

**Comment by hoeiendag** [comment]
Well, I found the culprit. Turns out that I had my public ipv 4 address correctly set but my dns provider also provides an ipv6 address which resolved to the hosting provider since I do not have a ipv6 address at my home. I deleted all ipv6 addresses and suddenly it worked!
