### ISSUE TITLE
Feature request: Add forgot password flow

### ISSUE THREAD

**Issue by asmaps** [hassio-addons/addon-nginx-proxy-manager#72]
# Problem/Motivation

My password manager didn't save the password I set correctly and so I don't know it

## Expected behavior

Have a possibility to reset the password somehow

## Actual behavior

No possibility to reset (at least not documented)

## Steps to reproduce

Forget your password :smile: 

## Proposed changes

Give some flow to reset a password (via config, webinterface etc)
For example add a password forgotten button which sets a new password and prints it to the logs or similar.

**Comment by sinclairpaul** [comment]
The add on wraps the existing application, I would suggest you post your suggestion at https://github.com/jc21/nginx-proxy-manager
