### ISSUE TITLE
Feature request: Custom ACME URL

### ISSUE THREAD

**Issue by asmaps** [hassio-addons/addon-nginx-proxy-manager#73]
# Problem/Motivation

My home assistant installation is not exposed to the public, so the "classic" let's encrypt does not work. I have a step ca running in my internal network to create self-signed certificates. Step CA now also supports ACME (`certbot --server https://ca.internal/acme/acme/directory`). It would be awesome to make nginx-proxy-manager use my own CA.

## Expected behavior

Sign certificates via ACME from my own internal ACME server.

## Actual behavior

It's only possible to use Let's Encrypt, which needs a publicly exposed host/domain.

## Steps to reproduce

Well...

## Proposed changes

Add a config/settings (e.g. per host, per cert or global?) to make certbot use a custom acme server (`--server` parameter)

**Comment by frenck** [comment]
Add-on wrap existing applications, please make the request upstream at the original NGINX Proxy Manager. Thanks 👍

**Comment by asmaps** [comment]
Oh sorry. Where do I find the original project?
