### ISSUE TITLE
Unable to start after update to 0.5.0

### ISSUE THREAD

**Issue by Carstijn** [hassio-addons/addon-nginx-proxy-manager#78]
# Problem/Motivation

Unable to start after update to 0.5.0, system running on fedora 30 (x86_64)

## Expected behavior
Everything starts as normal

## Actual behavior

s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] permissions: applying... 
[fix-attrs.d] permissions: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Nginx Proxy Manager
 Manage Nginx proxy hosts with a simple, powerful interface
-----------------------------------------------------------
 Add-on version: 0.5.0
 You are running the latest version of this add-on.
 System: Fedora 30 (Workstation Edition)  (amd64 / qemux86-64)
 Home Assistant Core: 0.106.2
 Home Assistant Supervisor: 206
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] mysql.sh: executing... 
[21:48:38] ERROR: This add-on now requires the MariaDB core add-on 2.0 or newer!
[21:48:38] FATAL: Make sure the MariaDB add-on is installed and running
[cont-init.d] mysql.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

## Steps to reproduce

Run it after update

**Comment by frenck** [comment]
The log shows in quite a red color at the end almost impossible to ignore.

> Be sure to check the log above, line by line, for hints.

Which shows:

[21:48:38] ERROR: This add-on now requires the MariaDB core add-on 2.0 or newer!
[21:48:38] FATAL: Make sure the MariaDB add-on is installed and running

Also see the release notes: https://github.com/hassio-addons/addon-nginx-proxy-manager/releases/tag/v0.5.0

So... there you have it.

**Comment by Carstijn** [comment]
A I see, tnx for the quick response!

**Comment by lvlie** [comment]
Unfortunately I have the same issue, but not able to resolve it yet. 
Previously I had the older mariadb installed and ran into this issue today. After upgrading mariadb to 2.0 the recorder component in core failed because of a different password (euhhh, dont know why, it worked before; fixed now via secrets.yaml), but the nginx proxy manager container still fails with the above message. In the mariadb log I see the following:

```
2020-03-02 19:53:28 14024 [Warning] Access denied for user 'root'@'localhost' (using password: NO)
2020-03-02 19:53:29 14025 [Warning] Access denied for user 'root'@'localhost' (using password: NO)
2020-03-02 19:53:30 14026 [Warning] Access denied for user 'root'@'localhost' (using password: NO)
2020-03-02 19:53:31 14027 [Warning] Access denied for user 'root'@'localhost' (using password: NO)
```

Any idea?

**Comment by lvlie** [comment]
Okay, something went wrong with the mariadb upgrade I guess... Reinstalled that one (lost state for the last 30 days, but thats okay since its also in influx for grafana) and the migration of the nginx proxy manager db to mariadb works like a charm
