### ISSUE TITLE
Error starting

### ISSUE THREAD

**Issue by aequ-maker** [hassio-addons/addon-nginx-proxy-manager#79]
# Problem/Motivation
When I start the add-on after migrating to version 5.0 it does'n start and the following error appear in the log:

nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
2020/03/01 22:56:47 [emerg] 15878#15878: socket() [::]:80 failed (97: Address family not supported by protocol)
[22:56:48] INFO: Starting NGinx...

**Comment by sinclairpaul** [comment]
Please post the full addon log, and the supervisor log

**Comment by aequ-maker** [comment]
Log
nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
[00:05:40] INFO: Starting NGinx...
2020/03/02 00:05:40 [emerg] 27666#27666: socket() [::]:80 failed (97: Address family not supported by protocol)
nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
[00:05:41] INFO: Starting NGinx...
2020/03/02 00:05:41 [emerg] 27675#27675: socket() [::]:80 failed (97: Address family not supported by protocol)
nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
[00:05:42] INFO: Starting NGinx...
nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
2020/03/02 00:05:42 [emerg] 27684#27684: socket() [::]:80 failed (97: Address family not supported by protocol)
[00:05:43] INFO: Starting NGinx...
nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
2020/03/02 00:05:43 [emerg] 27693#27693: socket() [::]:80 failed (97: Address family not supported by protocol)
[00:05:44] INFO: Starting NGinx...
2020/03/02 00:05:44 [emerg] 27702#27702: socket() [::]:80 failed (97: Address family not supported by protocol)
nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
[00:05:45] INFO: Starting NGinx...
nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
2020/03/02 00:05:45 [emerg] 27711#27711: socket() [::]:80 failed (97: Address family not supported by protocol)
[00:05:46] INFO: Starting NGinx...
nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
2020/03/02 00:05:46 [emerg] 27720#27720: socket() [::]:80 failed (97: Address family not supported by protocol)
[00:05:47] INFO: Starting NGinx...
nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
2020/03/02 00:05:47 [emerg] 27729#27729: socket() [::]:80 failed (97: Address family not supported by protocol)
[00:05:48] INFO: Starting NGinx...
nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
2020/03/02 00:05:48 [emerg] 27738#27738: socket() [::]:80 failed (97: Address family not supported by protocol)
[00:05:49] INFO: Starting NGinx...
2020/03/02 00:05:49 [emerg] 27747#27747: socket() [::]:80 failed (97: Address family not supported by protocol)
nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
[00:05:50] INFO: Starting NGinx...
2020/03/02 00:05:50 [emerg] 27756#27756: socket() [::]:80 failed (97: Address family not supported by protocol)
nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
[00:05:51] INFO: Starting NGinx...
nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
2020/03/02 00:05:51 [emerg] 27765#27765: socket() [::]:80 failed (97: Address family not supported by protocol)
[00:05:53] INFO: Starting NGinx...
nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
2020/03/02 00:05:53 [emerg] 27774#27774: socket() [::]:80 failed (97: Address family not supported by protocol)
[00:05:54] INFO: Starting NGinx...
nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
2020/03/02 00:05:54 [emerg] 27783#27783: socket() [::]:80 failed (97: Address family not supported by protocol)
[00:05:55] INFO: Starting NGinx...
nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
2020/03/02 00:05:55 [emerg] 27792#27792: socket() [::]:80 failed (97: Address family not supported by protocol)
[00:05:58] INFO: Starting NGinx...
2020/03/02 00:05:58 [emerg] 27801#27801: socket() [::]:80 failed (97: Address family not supported by protocol)
nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
[00:05:59] INFO: Starting NGinx...
2020/03/02 00:05:59 [emerg] 27810#27810: socket() [::]:80 failed (97: Address family not supported by protocol)
nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
[00:06:00] INFO: Starting NGinx...
2020/03/02 00:06:00 [emerg] 27819#27819: socket() [::]:80 failed (97: Address family not supported by protocol)
nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
[00:06:01] INFO: Starting NGinx...
nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
2020/03/02 00:06:01 [emerg] 27828#27828: socket() [::]:80 failed (97: Address family not supported by protocol)
[00:06:02] INFO: Starting NGinx...
2020/03/02 00:06:02 [emerg] 27837#27837: socket() [::]:80 failed (97: Address family not supported by protocol)
nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
[00:06:03] INFO: Starting NGinx...
2020/03/02 00:06:03 [emerg] 27846#27846: socket() [::]:80 failed (97: Address family not supported by protocol)
nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
[00:06:05] INFO: Starting NGinx...
2020/03/02 00:06:05 [emerg] 27855#27855: socket() [::]:80 failed (97: Address family not supported by protocol)
nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
[00:06:06] INFO: Starting NGinx...
2020/03/02 00:06:06 [emerg] 27864#27864: socket() [::]:80 failed (97: Address family not supported by protocol)
nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
[00:06:07] INFO: Starting NGinx...
nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
2020/03/02 00:06:07 [emerg] 27873#27873: socket() [::]:80 failed (97: Address family not supported by protocol)
[00:06:08] INFO: Starting NGinx...
2020/03/02 00:06:08 [emerg] 27882#27882: socket() [::]:80 failed (97: Address family not supported by protocol)
nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
[00:06:09] INFO: Starting NGinx...
2020/03/02 00:06:09 [emerg] 27891#27891: socket() [::]:80 failed (97: Address family not supported by protocol)
nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
[00:06:10] INFO: Starting NGinx...
2020/03/02 00:06:10 [emerg] 27900#27900: socket() [::]:80 failed (97: Address family not supported by protocol)
nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
[00:06:11] INFO: Starting NGinx...
2020/03/02 00:06:11 [emerg] 27909#27909: socket() [::]:80 failed (97: Address family not supported by protocol)
nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
[00:06:12] INFO: Starting NGinx...
2020/03/02 00:06:12 [emerg] 27918#27918: socket() [::]:80 failed (97: Address family not supported by protocol)
nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
[00:06:13] INFO: Starting NGinx...
2020/03/02 00:06:13 [emerg] 27927#27927: socket() [::]:80 failed (97: Address family not supported by protocol)
nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
[00:06:14] INFO: Starting NGinx...
2020/03/02 00:06:14 [emerg] 27936#27936: socket() [::]:80 failed (97: Address family not supported by protocol)
nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
[00:06:15] INFO: Starting NGinx...
nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
2020/03/02 00:06:15 [emerg] 27945#27945: socket() [::]:80 failed (97: Address family not supported by protocol)
[00:06:17] INFO: Starting NGinx...
2020/03/02 00:06:17 [emerg] 27954#27954: socket() [::]:80 failed (97: Address family not supported by protocol)
nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)

--------
20-03-01 22:39:51 INFO (MainThread) [hassio.utils.gdbus] Connect to dbus: org.freedesktop.NetworkManager - /org/freedesktop/NetworkManager/DnsManager
20-03-01 22:39:51 INFO (MainThread) [hassio.host.info] Update local host information
20-03-01 22:39:51 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
20-03-01 22:39:51 INFO (MainThread) [hassio.host.services] Update service information
20-03-01 22:39:51 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
20-03-01 22:39:51 INFO (MainThread) [hassio.host.network] Update local network DNS information
20-03-01 22:39:51 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/NetworkManager/DnsManager
20-03-01 22:39:51 INFO (MainThread) [hassio.host.apparmor] Load AppArmor Profiles: {'hassio-supervisor'}
20-03-01 22:39:51 INFO (MainThread) [hassio.host.services] Reload local service hassio-apparmor.service
20-03-01 22:39:51 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.systemd1.Manager.ReloadOrRestartUnit on /org/freedesktop/systemd1
20-03-01 22:39:51 INFO (SyncWorker_1) [hassio.docker.interface] Attach to homeassistant/armv7-hassio-dns with version 1
20-03-01 22:39:51 INFO (MainThread) [hassio.misc.forwarder] Start DNS port forwarding to 172.30.32.3
20-03-01 22:39:51 INFO (MainThread) [hassio.dns] Start CoreDNS plugin
20-03-01 22:39:51 INFO (SyncWorker_1) [hassio.docker.interface] Clean hassio_dns application
20-03-01 22:40:12 INFO (SyncWorker_1) [hassio.docker.dns] Start DNS homeassistant/armv7-hassio-dns with version 1 - 172.30.32.3
20-03-01 22:40:12 INFO (SyncWorker_3) [hassio.docker.interface] Attach to homeassistant/raspberrypi2-homeassistant with version 0.106.2
20-03-01 22:40:14 INFO (MainThread) [hassio.store.git] Load add-on /data/addons/core repository
20-03-01 22:40:14 INFO (MainThread) [hassio.store.git] Load add-on /data/addons/git/a0d7b954 repository
20-03-01 22:40:15 INFO (MainThread) [hassio.store] Load add-ons from store: 63 all - 63 new - 0 remove
20-03-01 22:40:15 INFO (MainThread) [hassio.addons] Found 7 installed add-ons
20-03-01 22:40:15 INFO (SyncWorker_3) [hassio.docker.interface] Attach to hassioaddons/pi-hole-armv7 with version 4.1.0
20-03-01 22:40:15 INFO (SyncWorker_8) [hassio.docker.interface] Attach to hassioaddons/bitwarden-armv7 with version v0.6.0
20-03-01 22:40:15 INFO (SyncWorker_6) [hassio.docker.interface] Attach to hassioaddons/nginxproxymanager-armv7 with version 0.5.0
20-03-01 22:40:15 INFO (SyncWorker_5) [hassio.docker.interface] Attach to homeassistant/armv7-addon-duckdns with version 1.10
20-03-01 22:40:15 INFO (SyncWorker_0) [hassio.docker.interface] Attach to homeassistant/armv7-addon-configurator with version 4.7
20-03-01 22:40:15 INFO (SyncWorker_1) [hassio.docker.interface] Attach to hassioaddons/portainer-armv7 with version 1.0.0
20-03-01 22:40:15 INFO (SyncWorker_12) [hassio.docker.interface] Attach to hassioaddons/sqlite-web-armv7 with version 2.1.0
20-03-01 22:40:15 INFO (MainThread) [hassio.updater] Fetch update data from https://version.home-assistant.io/stable.json
20-03-01 22:40:16 INFO (MainThread) [hassio.snapshots] Found 6 snapshot files
20-03-01 22:40:16 INFO (MainThread) [hassio.discovery] Load 0 messages
20-03-01 22:40:16 INFO (MainThread) [hassio.ingress] Load 4 ingress session
20-03-01 22:40:16 INFO (MainThread) [hassio.secrets] Load Home Assistant secrets: 1
20-03-01 22:40:16 INFO (MainThread) [__main__] Run Hass.io
20-03-01 22:40:16 INFO (MainThread) [hassio.api] Start API on 172.30.32.2
20-03-01 22:40:16 INFO (MainThread) [hassio.addons] Phase 'initialize' start 0 add-ons
20-03-01 22:40:16 INFO (MainThread) [hassio.addons] Phase 'system' start 1 add-ons
20-03-01 22:40:16 WARNING (MainThread) [hassio.addons.validate] Unknown options virtual_host
20-03-01 22:40:16 INFO (SyncWorker_19) [hassio.docker.interface] Clean addon_a0d7b954_pi-hole application
20-03-01 22:40:33 INFO (SyncWorker_19) [hassio.docker.addon] Start Docker add-on hassioaddons/pi-hole-armv7 with version 4.1.0
20-03-01 22:40:38 INFO (MainThread) [hassio.addons] Phase 'services' start 2 add-ons
20-03-01 22:40:38 INFO (SyncWorker_10) [hassio.docker.interface] Clean addon_core_duckdns application
20-03-01 22:40:39 INFO (SyncWorker_2) [hassio.docker.interface] Clean addon_a0d7b954_bitwarden application
20-03-01 22:40:39 INFO (MainThread) [hassio.api.security] /host/info access from a0d7b954_pi-hole
20-03-01 22:40:58 INFO (MainThread) [hassio.api.security] /dns/info access from a0d7b954_pi-hole
20-03-01 22:40:59 INFO (SyncWorker_10) [hassio.docker.addon] Start Docker add-on homeassistant/armv7-addon-duckdns with version 1.10
20-03-01 22:41:02 INFO (SyncWorker_2) [hassio.docker.addon] Start Docker add-on hassioaddons/bitwarden-armv7 with version v0.6.0
20-03-01 22:41:06 INFO (MainThread) [hassio.api.security] /host/info access from a0d7b954_bitwarden
20-03-01 22:41:07 INFO (SyncWorker_13) [hassio.docker.interface] Start homeassistant/raspberrypi2-homeassistant
20-03-01 22:42:35 INFO (MainThread) [hassio.homeassistant] Detect a running Home Assistant instance
20-03-01 22:42:35 INFO (MainThread) [hassio.addons] Phase 'application' start 1 add-ons
20-03-01 22:42:35 INFO (SyncWorker_12) [hassio.docker.interface] Clean addon_a0d7b954_nginxproxymanager application
20-03-01 22:43:03 INFO (SyncWorker_12) [hassio.docker.addon] Start Docker add-on hassioaddons/nginxproxymanager-armv7 with version 0.5.0
20-03-01 22:43:08 INFO (MainThread) [hassio.tasks] All core tasks are scheduled
20-03-01 22:43:08 INFO (MainThread) [hassio.core] Hass.io is up and running
20-03-01 22:43:15 INFO (MainThread) [hassio.api.security] /host/info access from a0d7b954_nginxproxymanager
20-03-01 22:46:25 INFO (MainThread) [hassio.addons] Create Home Assistant add-on data folder /data/addons/data/core_mariadb
20-03-01 22:46:25 INFO (SyncWorker_19) [hassio.docker.interface] Pull image homeassistant/armv7-addon-mariadb tag 2.0.
20-03-01 22:46:37 ERROR (SyncWorker_19) [hassio.docker.interface] Can't install homeassistant/armv7-addon-mariadb:2.0 -> 500 Server Error: Internal Server Error ("Get https://registry-1.docker.io/v2/: net/http: TLS handshake timeout").
20-03-01 22:47:05 INFO (SyncWorker_10) [hassio.docker.interface] Pull image homeassistant/armv7-addon-mariadb tag 2.0.
20-03-01 22:49:56 INFO (MainThread) [hassio.addons] Add-on 'core_mariadb' successfully installed
20-03-01 22:50:21 ERROR (MainThread) [hassio.addons.addon] Add-on core_mariadb have wrong options: Missing required option 'password'. Got {'databases': ['homeassistant'], 'logins': [{'username': 'homeassistant', 'password': None}], 'rights': [{'username': 'homeassistant', 'database': 'homeassistant'}]}
20-03-01 22:53:47 INFO (SyncWorker_18) [hassio.docker.interface] Clean addon_a0d7b954_nginxproxymanager application
20-03-01 22:54:04 INFO (SyncWorker_18) [hassio.docker.addon] Start Docker add-on hassioaddons/nginxproxymanager-armv7 with version 0.5.0
20-03-01 22:54:15 INFO (MainThread) [hassio.api.security] /host/info access from a0d7b954_nginxproxymanager
20-03-01 23:43:07 INFO (SyncWorker_0) [hassio.docker.addon] Start Docker add-on homeassistant/armv7-addon-mariadb with version 2.0
20-03-01 23:43:53 INFO (SyncWorker_2) [hassio.docker.interface] Clean addon_a0d7b954_nginxproxymanager application
20-03-01 23:44:31 INFO (SyncWorker_2) [hassio.docker.addon] Start Docker add-on hassioaddons/nginxproxymanager-armv7 with version 0.5.0
20-03-01 23:44:41 INFO (MainThread) [hassio.api.security] /host/info access from a0d7b954_nginxproxymanager
20-03-01 23:45:15 INFO (MainThread) [hassio.services.modules.mysql] Set core_mariadb as service provider for MySQL
20-03-02 00:08:20 INFO (SyncWorker_16) [hassio.docker.interface] Clean addon_a0d7b954_nginxproxymanager application
20-03-02 00:08:40 INFO (SyncWorker_16) [hassio.docker.addon] Start Docker add-on hassioaddons/nginxproxymanager-armv7 with version 0.5.0
20-03-02 00:08:49 INFO (MainThread) [hassio.api.security] /host/info access from a0d7b954_nginxproxymanager
20-03-02 00:10:37 INFO (MainThread) [hassio.api.security] /dns/info access from a0d7b954_nginxproxymanager
20-03-02 00:13:35 INFO (SyncWorker_17) [hassio.docker.interface] Stop addon_a0d7b954_nginxproxymanager application
20-03-02 00:13:49 INFO (SyncWorker_17) [hassio.docker.interface] Clean addon_a0d7b954_nginxproxymanager application
20-03-02 00:14:51 INFO (SyncWorker_4) [hassio.docker.addon] Start Docker add-on hassioaddons/nginxproxymanager-armv7 with version 0.5.0
20-03-02 00:14:57 INFO (MainThread) [hassio.api.security] /host/info access from a0d7b954_nginxproxymanager
20-03-02 00:15:06 INFO (MainThread) [hassio.api.security] /dns/info access from a0d7b954_nginxproxymanager
20-03-02 00:43:08 INFO (MainThread) [hassio.updater] Fetch update data from https://version.home-assistant.io/stable.json
20-03-02 00:49:48 INFO (MainThread) [hassio.host.info] Update local host information
20-03-02 00:49:48 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
20-03-02 00:49:48 INFO (MainThread) [hassio.host.services] Update service information
20-03-02 00:49:48 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
20-03-02 00:49:49 INFO (MainThread) [hassio.host.network] Update local network DNS information
20-03-02 00:49:49 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/NetworkManager/DnsManager
20-03-02 01:43:08 INFO (MainThread) [hassio.store.git] Update add-on https://github.com/home-assistant/hassio-addons repository
20-03-02 01:43:09 INFO (MainThread) [hassio.store.git] Update add-on https://github.com/hassio-addons/repository repository
20-03-02 01:43:24 INFO (MainThread) [hassio.store] Load add-ons from store: 64 all - 1 new - 0 remove
20-03-02 02:00:32 INFO (SyncWorker_2) [hassio.docker.interface] Stop addon_a0d7b954_nginxproxymanager application
20-03-02 02:00:45 INFO (SyncWorker_2) [hassio.docker.interface] Clean addon_a0d7b954_nginxproxymanager application
20-03-02 02:08:01 INFO (SyncWorker_0) [hassio.docker.addon] Start Docker add-on hassioaddons/nginxproxymanager-armv7 with version 0.5.0
20-03-02 02:08:09 INFO (MainThread) [hassio.api.security] /host/info access from a0d7b954_nginxproxymanager
20-03-02 02:08:17 INFO (MainThread) [hassio.api.security] /dns/info access from a0d7b954_nginxproxymanager
20-03-02 02:43:08 INFO (MainThread) [hassio.updater] Fetch update data from https://version.home-assistant.io/stable.json
20-03-02 02:56:28 INFO (MainThread) [hassio.host.info] Update local host information
20-03-02 02:56:28 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
20-03-02 02:56:30 INFO (MainThread) [hassio.host.services] Update service information
20-03-02 02:56:30 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
20-03-02 02:56:31 INFO (MainThread) [hassio.host.network] Update local network DNS information
20-03-02 02:56:31 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/NetworkManager/DnsManager

**Comment by aequ-maker** [comment]
I've just restarted the addon since I'd realize that the log was uncomplete (I'm sorry) so I'm posting the new log:

Log
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] permissions: applying... 
[fix-attrs.d] permissions: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 

-----------------------------------------------------------
 Add-on: Nginx Proxy Manager
 Manage Nginx proxy hosts with a simple, powerful interface
-----------------------------------------------------------
 Add-on version: 0.5.0
 You are running the latest version of this add-on.
 System: Raspbian GNU/Linux 9 (stretch)  (armv7 / raspberrypi2)
 Home Assistant Core: 0.106.2
 Home Assistant Supervisor: 206
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] mysql.sh: executing... 
[cont-init.d] mysql.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] npm.sh: executing... 
[cont-init.d] npm.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[00:15:30] INFO: Starting the Manager...
[00:15:30] INFO: Starting NGinx...
2020/03/02 00:15:30 [emerg] 532#532: socket() [::]:80 failed (97: Address family not supported by protocol)
nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
[00:15:31] INFO: Starting NGinx...
nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
2020/03/02 00:15:31 [emerg] 567#567: socket() [::]:80 failed (97: Address family not supported by protocol)
[00:15:32] INFO: Starting NGinx...
2020/03/02 00:15:32 [emerg] 576#576: socket() [::]:80 failed (97: Address family not supported by protocol)
nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
[00:15:33] INFO: Starting NGinx...
2020/03/02 00:15:33 [emerg] 585#585: socket() [::]:80 failed (97: Address family not supported by protocol)
nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
[00:15:34] INFO: Starting NGinx...
nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
2020/03/02 00:15:34 [emerg] 594#594: socket() [::]:80 failed (97: Address family not supported by protocol)
[00:15:35] INFO: Starting NGinx...
nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
2020/03/02 00:15:35 [emerg] 603#603: socket() [::]:80 failed (97: Address family not supported by protocol)
[00:15:36] INFO: Starting NGinx...
2020/03/02 00:15:36 [emerg] 612#612: socket() [::]:80 failed (97: Address family not supported by protocol)
nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
[00:15:38] INFO: Starting NGinx...
2020/03/02 00:15:38 [emerg] 623#623: socket() [::]:80 failed (97: Address family not supported by protocol)
nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
[00:15:39] INFO: Starting NGinx...
nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
2020/03/02 00:15:39 [emerg] 632#632: socket() [::]:80 failed (97: Address family not supported by protocol)

**Comment by frenck** [comment]
This is an upstream issue, out of our control:

<https://github.com/jc21/nginx-proxy-manager/issues/312>

**Comment by aequ-maker** [comment]
Thanks for your answer, I've been able to re-enable ipv6 in the host, as mentioned in the issue you pointed me out, and npm is working again :-)

**Comment by frenck** [comment]
fixed in the current development version. Will be part of the next release.
