### ISSUE TITLE
[Feature request] Ability to manually configure Mysql server

### ISSUE THREAD

**Issue by ejalal** [hassio-addons/addon-nginx-proxy-manager#80]
# Problem/Motivation

> I setup an external Mysql server to be used with Hassio, in order to free some resources on the Hassio Raspberry Pi, I would like to use that server with Nginx Proxy Manager instead if setting up the Mysql Addon

## Expected behavior

> Be able to setup mysql dsn in the Addon configuration

## Actual behavior

> Not able to manually configure mysql

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Currently, there are no plans to support this.

**Comment by ejalal** [comment]
😢

**Comment by LaBoss** [comment]
+☝️i have to install maria addon only for this i have another server for mysql

**Comment by frenck** [comment]
@LaBoss While that sounds like good reasoning, previously the add-on ran its own MySQL server. So nothing changed.

**Comment by ejalal** [comment]
Yeah I know, that's a good move, but a more clever one is to be able to manually set the mysql config, like when we move hassio from sqlite to mysql. It could be the mysql addon or any other mysql server.

**Comment by frenck** [comment]
I gave this a thought, and I'm not implementing this.

The add-on requires this, from the UI there will be changes that ensure the user meets the requirements. Adding this option, will remove that requirement and thus make is less apparent and less easier for users.

**Comment by jendib** [comment]
That would have been really useful. My machine running HA already have a MariaDB database running for other apps...

**Comment by frenck** [comment]
Thanks, reasoning above given, not being implemented.
