### ISSUE TITLE
Fresh install, certificate error, unable to login to Nginx Proxy Manager w/ factory creds

### ISSUE THREAD

**Issue by PieBru** [hassio-addons/addon-nginx-proxy-manager#81]
# Problem/Motivation

Hi all, I just installed MariaDB and Nginx P.M. 0.5.0, which reports certificate errors in the log.

## Expected behavior

Login into HassIO N.P.M. addon.

## Actual behavior

I'm not able to login to N.P.M. with the factory initial credentials.

## Steps to reproduce

1. Fresh install of MariaDB HassIO addon.
2. Fresh install of Nginx Proxy Manager HassIO addon.
3. Comment-out the `http:` section in `configuration.yaml`
4. Restart HASS, MariaDB starts automatically.
5. Start Nginx Proxy Manager HassIO addon.
6. Access to the N.P.M web UI so it shows the login form.
7. Unable to login with the factory initial default creds (admin@...)
8. Checked the logs, see below the certificate errors reported.

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

Here is the log, any hint?
Thanks,
Piero

```txt
-----------------------------------------------------------
 Add-on: Nginx Proxy Manager
 Manage Nginx proxy hosts with a simple, powerful interface
-----------------------------------------------------------
 Add-on version: 0.5.0
 You are running the latest version of this add-on.
 System: EndeavourOS  (amd64 / qemux86-64)
 Home Assistant Core: 0.106.4
 Home Assistant Supervisor: 206
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] mysql.sh: executing... 
[cont-init.d] mysql.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] npm.sh: executing... 
[cont-init.d] npm.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[11:06:24] INFO: Starting NGinx...
[11:06:24] INFO: Starting the Manager...
[3/3/2020] [11:06:28 AM] [Migrate  ] › ℹ  info      Current database version: 20190227065017
[3/3/2020] [11:06:28 AM] [IP Ranges] › ℹ  info      Fetching IP Ranges from online services...
[3/3/2020] [11:06:28 AM] [IP Ranges] › ℹ  info      Fetching https://ip-ranges.amazonaws.com/ip-ranges.json
[3/3/2020] [11:06:30 AM] [IP Ranges] › ℹ  info      Fetching https://www.cloudflare.com/ips-v4
[3/3/2020] [11:06:31 AM] [IP Ranges] › ℹ  info      Fetching https://www.cloudflare.com/ips-v6
[3/3/2020] [11:06:31 AM] [SSL      ] › ℹ  info      Let's Encrypt Renewal Timer initialized
[3/3/2020] [11:06:31 AM] [SSL      ] › ℹ  info      Renewing SSL certs close to expiry...
[3/3/2020] [11:06:31 AM] [IP Ranges] › ℹ  info      IP Ranges Renewal Timer initialized
[3/3/2020] [11:06:31 AM] [Global   ] › ℹ  info      Backend PID 534 listening on port 3000 ...
[3/3/2020] [11:07:00 AM] [Nginx    ] › ℹ  info      Reloading Nginx
[3/3/2020] [11:07:00 AM] [SSL      ] › ℹ  info      Renew Complete
[3/3/2020] [11:07:00 AM] [SSL      ] › ✖  error     Certificate is not valid (Command failed: openssl x509 -in /etc/letsencrypt/live/npm-4/fullchain.pem -subject -noout
Can't open /etc/letsencrypt/live/npm-4/fullchain.pem for reading, No such file or directory
140093499018568:error:02001002:system library:fopen:No such file or directory:crypto/bio/bss_file.c:69:fopen('/etc/letsencrypt/live/npm-4/fullchain.pem','r')
140093499018568:error:2006D080:BIO routines:BIO_new_file:no such file:crypto/bio/bss_file.c:76:
unable to load certificate
)
[3/3/2020] [11:07:00 AM] [SSL      ] › ✖  error     Certificate is not valid (Command failed: openssl x509 -in /etc/letsencrypt/live/npm-1/fullchain.pem -subject -noout
Can't open /etc/letsencrypt/live/npm-1/fullchain.pem for reading, No such file or directory
140316434771272:error:02001002:system library:fopen:No such file or directory:crypto/bio/bss_file.c:69:fopen('/etc/letsencrypt/live/npm-1/fullchain.pem','r')
140316434771272:error:2006D080:BIO routines:BIO_new_file:no such file:crypto/bio/bss_file.c:76:
unable to load certificate
)
[3/3/2020] [11:07:00 AM] [SSL      ] › ✖  error     Certificate is not valid (Command failed: openssl x509 -in /etc/letsencrypt/live/npm-5/fullchain.pem -subject -noout
Can't open /etc/letsencrypt/live/npm-5/fullchain.pem for reading, No such file or directory
139650364681544:error:02001002:system library:fopen:No such file or directory:crypto/bio/bss_file.c:69:fopen('/etc/letsencrypt/live/npm-5/fullchain.pem','r')
139650364681544:error:2006D080:BIO routines:BIO_new_file:no such file:crypto/bio/bss_file.c:76:
unable to load certificate
)
[3/3/2020] [11:07:00 AM] [SSL      ] › ✖  error     Certificate is not valid (Command failed: openssl x509 -in /etc/letsencrypt/live/npm-7/fullchain.pem -subject -noout
Can't open /etc/letsencrypt/live/npm-7/fullchain.pem for reading, No such file or directory
140708107967816:error:02001002:system library:fopen:No such file or directory:crypto/bio/bss_file.c:69:fopen('/etc/letsencrypt/live/npm-7/fullchain.pem','r')
140708107967816:error:2006D080:BIO routines:BIO_new_file:no such file:crypto/bio/bss_file.c:76:
unable to load certificate
)
```

**Comment by Fruityski** [comment]
I am having the same problem 

![image](https://user-images.githubusercontent.com/41670430/76154783-4f589880-6147-11ea-9d1f-71638c52ee17.png)

**Comment by frenck** [comment]
@Fruityski So I fail to see how that is the same problem, the report is: Cannot login.

You post: Screenshot that shows something after you have logged in.

How can that be even remotely close be the same issue?

**Comment by PieBru** [comment]
I didn't sort it out jet, but I fresh-installed Arch+HassIO on a new Z8350 box and fresh-installed Nginx Proxy Manager HassIO addon, so I have a few more details.

1. The certificate errors are logged *before* the first login attempt.

2. This is the login form reply after trying with the default factory creds:
![Screenshot from 2020-03-09 19-20-41](https://user-images.githubusercontent.com/6537434/76245225-cbcca380-623b-11ea-85a6-362f78800197.png)

Thanks,
Piero

**Comment by frenck** [comment]
@PieBru Could you please install the phpMyAdmin add-on and check the user table of the nginxproxymanager database to make sure?

**Comment by PieBru** [comment]
@frenck I'm happy to help.

Here is my latest install (Z8350 box) nginxproxymanager tables DB screenshot:
![Screenshot from 2020-03-10 11-36-44](https://user-images.githubusercontent.com/6537434/76304376-92d81180-62c3-11ea-80fa-588653c009d8.png)

What can I do?

**Comment by frenck** [comment]
The fact that the database shows 5 records on the `proxy_host` table, tells me this is not a fresh installation.
Check the `user` table for hints on the login, maybe that brings up memories.

**Comment by PieBru** [comment]
Thank you @frenck , my login problem is solved: as you pointed out the userid was an old temporary test account.

I though this has been the sequence generating this issue:
1. Back in time I tried Nginx Proxy Manager, when it didn't yet migrate to MariaDB, then for some reason I uninstalled it, but its data remained in the DB and propagated until nowadays through the nightly snapshots.
2. Recently, when I installed the new HassIO server, to save time I restored a snapshot, thus unconsciously inheriting the old unused `nginxproxymanager` DB.
3. Then I "fresh" installed the Nginx Proxy Manager addon on the new server and I wasn't able to login with the factory creds because of the old inherited creds.

So the login issue is solved, as well as the certificate errors logged, after I did:
A. Uninstall the N.P.M. addon
B. Drop the `nginxproxymanager` DB from MariaDB.
C. Reinstall ans starting the N.P.M. addon.

Before dropping, I did a temporary `nginxproxymanager` DB export for you, just in case you are interested in understanding the certificate errors, which indeed disappeared after the DB drop.

IMO to save future similar hassles it may be useful if your addon could log a warning when it finds a populated DB on the first run after installing the addon.

Thanks,
Piero

**Comment by sinclairpaul** [comment]
The cert errors would be generated as there would be the configuration in the database, for which the files no longer exist.

I doubt we can do anything about an existing DB message, as it would be difficult to tell if it is the active one or not.  I believe this can be closed now?

**Comment by PieBru** [comment]
Closed.
Thank you.
