### ISSUE TITLE
Redirects to different add-ons / ports

### ISSUE THREAD

**Issue by stijn-dhondt** [hassio-addons/addon-nginx-proxy-manager#82]
# Problem/Motivation

When using appdeamon 4 redirect is done to https://fqdn:5050 wich is not handeled by nginx  

## Expected behavior

Redirection to multiple ports being available (if it's even possible).

## Actual behavior

The site can't be reached as only 443 is handled or 80 redirected to 443.

## Steps to reproduce

Setup a nginx proxy with cert on it pointing to HA instance you are running on.

## Proposed changes

See expected behavior.

**Comment by frenck** [comment]
The goal of a reverse proxy is to pipe all traffic through a single set of ports...

Having more ports, would defeat the need for a reverse proxy... 🤷‍♂
