### ISSUE TITLE
Reset admin password

### ISSUE THREAD

**Issue by hav10** [hassio-addons/addon-nginx-proxy-manager#86]
Hello,

I need to reset the default admin password.

I see this is possible with the source nginx proxy manager. Can a reset script be added to this add-on?

Thanks.

**Comment by frenck** [comment]
Unfortunately, that is not possible with this add-on.
You can execute parts of the script provided by the Nginx proxy manager project (the bcrypt-tool) to generate a new hash.

Using the phpMyAdmin add-on, you should be able to edit the new has for your user account.
