### ISSUE TITLE
When Trying To Add Your Own Cert

### ISSUE THREAD

**Issue by MapGuy11** [hassio-addons/addon-nginx-proxy-manager#87]
# Problem/Motivation

> (Why the issue was filed)
When You Try To insert your own cert since Lets Encrypt way wont work since my ISP block 80 and 443
## Expected behavior
Certs insert in field
> (What you expected to happen)

## Actual behavior

> (What actually happened)
It doesn't do anything just sits there
## Steps to reproduce
Add a custom cert and import it
> (How can someone else make/see it happen)

## Proposed changes
Also, Custom Cert should be easier said maybe also an option for DNS challenge for people who have 80 and 443 blocked a lot of us in the northeast US
> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Custom certs can be uploaded via the SSL certificates menu.

About your request for DNS challenges: Add-ons wrap existing software, in this case: The NGINX Proxy Manager. Please request your future request with them.

Thanks 👍

**Comment by MapGuy11** [comment]
Still when you upload a cert it doesn't do anything. You didn't read it
