### ISSUE TITLE
Can You Add Cert In Config?

### ISSUE THREAD

**Issue by MapGuy11** [hassio-addons/addon-nginx-proxy-manager#88]
# Problem/Motivation
Certs won't add whatever I do and I can get DNS Challenge through the web interface so I create them on my own I was wondering If I can add them via SSL folder and what file type it should be for normal Lets Encrypt certs?
> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by sinclairpaul** [comment]
It looks to me there may be a GUI issue in the paths being updated in the UI when selected.  Have you actually tried to upload the certificate, and receive an error?

I perform this process on my Dev box (and have just retested), by manually uploading certificates.

**Comment by MapGuy11** [comment]
Yes, It just doesn't do anything I click on it my file manager opens On Pop OS! then I click import and doesn't do anything on the other side. I was wondering if I can just import it to the SSL folder in HA

**Comment by sinclairpaul** [comment]
You can't as it also perform Database operations, I would check your browser console for errors.

**Comment by MapGuy11** [comment]
I tried Chrome and Firefox it's the same thing it's weird

**Comment by MapGuy11** [comment]
Also what exactly goes into the Certificate KEy and Certificate its fullchain.pem for Cert and privkey.pem for Key correct?

**Comment by MapGuy11** [comment]
It Justed Work Nevermind its the WEB UI just doesn't say anything when you import a file! THANK YOU FOR YOUR HARD WORK!
