### ISSUE TITLE
Generate LE certs without 80 port

### ISSUE THREAD

**Issue by andriej** [hassio-addons/addon-nginx-proxy-manager#89]
# Problem/Motivation

Allow even more secure (especially behind cloudlfare) generate local LE certs

## Expected behavior

Use i.e. DNS validation or current HTTPS channel to create new cert

## Actual behavior

Without port 80 no chance go issue new cert, have to turn it on on router every time.

## Steps to reproduce

Just try to generate cert without 80 port.

## Proposed changes

As above.

**Comment by bieniu** [comment]
My ISP blocks port 80 so for me a DNS challenge is the only way to generate a cert.

**Comment by frenck** [comment]
Add-ons wrap existing applications. Unfortunately, this application does not support that.

Please file an issue/feature request upstream. Until then, this add-on might not be the right choice for you.
