### ISSUE TITLE
Feature request: Allow custom SSL certificate to be loaded via add-on config file

### ISSUE THREAD

**Issue by bmcclure** [hassio-addons/addon-nginx-proxy-manager#92]
Home Assistant's LetsEncrypt add-on has some advantages in the SSL cert generation arena over this add-on. It supports DNS validation and automatically creates the appropriate DNS records at common DNS providers to allow for automatic registration and renewals without user intervention.

This plugin, on the other hand, only supports HTML validation. This means it can't be used to generate a certificate for a hostname that points to a local IP address, because LetsEncrypt won't be able to access the validation file on that hostname.

Since that existing LetsEncrypt add-on already works great, it would be ideal if you could pass in the certificate generated by that add-on to be the certificate used in Nginx Proxy Manager.

I realize I could use a Custom SSL cert in Nginx Proxy Manager, but then I need to re-copy the certificate manually into the UI every time it renews. If it could simply access the certificate that the LetsEncrypt add-on makes available in Home Assistant's files, then this would all simply work automatically.

**Comment by bmcclure** [comment]
Actually, I see that the "ssl" directory should already be mapped in the container, so any SSL certificate generated by other add-ons should already be available there. So an alternative to specifying the SSL certificate in the add-on config would be if we could just select a local SSL certificate and key file from within the Nginx Proxy Manager interface.

**Comment by frenck** [comment]
Add-ons wrap existing applications. In this case, the Nginx Proxy Manager.
In this case, that application does not support that, hence it cannot be added.

**Comment by bmcclure** [comment]
Understood, thanks. I went ahead and opened a request in the app's repo since it would be a useful feature outside the context of Home Assistant as well to simply be able to specify a custom path with adding a certificate.
