### ISSUE TITLE
Make dependency on MariaDB addon configurable - use external database

### ISSUE THREAD

**Issue by timdj** [hassio-addons/addon-nginx-proxy-manager#93]
I have hassio running on raspberry PI and I am using an external instances running om my NAS for a MariaDB database and MQTT. I wish to use this addon but it looks like it depends on the actual mariadb add-on

**Comment by frenck** [comment]
That is not supported. If you are looking for running things that way, I'd recommend running the Home Assistant Core directly on Docker.
