### ISSUE TITLE
Error when installing in a Supervised Home Assistant environment

### ISSUE THREAD

**Issue by vgisbert** [hassio-addons/addon-nginx-proxy-manager#96]
In the current environment of a "SUPERVISED HOME ASSISTANT" when installing the ADD-ON nginx, fulfilling the prerequisites (duckdns and mariadb), there is a communication error with MariaDB that prevents the normal operation of WebUi.

MariaDB log >>>>>>>>>>>>
[Warning] Aborted connection 25 to db: 'nginxproxymanager' user: 'service' host: '172.30.33.5' (Got an error reading communication packets)
[Warning] Aborted connection 26 to db: 'nginxproxymanager' user: 'service' host: '172.30.33.5' (Got an error reading communication packets)
>>>>>>>>>>>

## Steps to reproduce
MACHINE: Intel NUC with ubuntu OS 18.04.4 LTS
(I guess it will happen on other machines too)
DOCKER: Home Assistant 0.110.6 (supervised)
ADD-ONs:
- Duck DNS, version: 1.12.0
- MariaDB, version: 2.1.2
- Nginx Proxy Manager, version: 0.6.0

The my add-on settings:
![Portapapeles-2](https://user-images.githubusercontent.com/36932535/84169034-6aa1af80-aa78-11ea-9c61-54909bb5bd04.jpg)
![Portapapeles-3](https://user-images.githubusercontent.com/36932535/84169044-6ffefa00-aa78-11ea-9166-250e105724f1.jpg)

According to the image the database has been created:
![Portapapeles-1](https://user-images.githubusercontent.com/36932535/84168481-be5fc900-aa77-11ea-8311-61437ba5fd9d.jpg)

In the Log of nginx proxy manager >>>>>>>>>>>>>
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] permissions: applying... 
[fix-attrs.d] permissions: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Nginx Proxy Manager
 Manage Nginx proxy hosts with a simple, powerful interface
-----------------------------------------------------------
 Add-on version: 0.6.0
 You are running the latest version of this add-on.
 System: Ubuntu 18.04.4 LTS  (amd64 / intel-nuc)
 Home Assistant Core: 0.110.6
 Home Assistant Supervisor: 227
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] mysql.sh: executing... 
[cont-init.d] mysql.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] npm.sh: executing... 
[cont-init.d] npm.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[17:35:07] INFO: Starting NGinx...
[17:35:07] INFO: Starting the Manager...
info      Current database version: 20200410143840
info      Fetching IP Ranges from online services...
info      Fetching https://ip-ranges.amazonaws.com/ip-ranges.json
info      Fetching https://www.cloudflare.com/ips-v4
info      Fetching https://www.cloudflare.com/ips-v6
info      Let's Encrypt Renewal Timer initialized
info      Renewing SSL certs close to expiry...
info      IP Ranges Renewal Timer initialized
info      Backend PID 535 listening on port 3000 ...
info      Reloading Nginx
info      Renew Complete
>>>>>>>>>>>>

In these conditions it allows "OPEN WEB UI" button and login using: admin@example.com / changeme, but it does not allow to do any other action.

Following the steps of others users, I have uninstalled nginx proxy manager, removed nginxproxymanager database from MariaDB, and reinstalled nginx proxy manager. With the same result.

Any ideas?

<blockquote></blockquote>
<blockquote></blockquote>
<blockquote></blockquote>

**Comment by frenck** [comment]
I don't understand your issue? What is not working exactly?

Everything you've posted seems ok.

**Comment by vgisbert** [comment]
> It will be listed under Home Assistant Community Add-ons in the add on store.

Hello again. First of all, thank you for trying to help me ... thank you very much.
I'm very clumsy, and I'm still where I started.
All the documentation refers to the fact that the add-on must be installed through the official repository https://addons.community, using the standard method. But it always takes me to the same place.
Looking at the container through Portainer, the addon_core_nginx_proxy has the name homeassistant / amd64-addon-nginx_proxy: 3.0.1, and has only port 443 published.
And sure enough, the io.hass.url variable points to https://github.com/home-assistant/hassio-addons/tree/master/nginx_proxy
Again my question:
Until the add-on link of the official repository is reached,
Is there any unofficial repository where i can load addon-nginx_proxy 0.6.0? ,
if not,
Is there any linux instruction to load it via docker?
Thank you very much again.

**Comment by sinclairpaul** [comment]
Scroll the addon store page down and install the addon that looks like 
![image](https://user-images.githubusercontent.com/24625998/84383593-8ad98780-abba-11ea-8e97-473917be7057.png)

You must have done this previously for your original issue to be logged, and you have access to the Community store as you installed PHPMyAdmin.

I would suggest how to's and usage are better discussed on the Community Forums or Discord, rather than GitHub issues.

**Comment by vgisbert** [comment]
Hello again.
I'm very sorry for my clumsiness.
I have already realized my mistake.
I have also understood that github is not the correct way. Understand that this is the first time I write in asking for help. Thank you very much for your help.
I close the thread.
