### ISSUE TITLE
Nginx not starting due to unexpected ";"

### ISSUE THREAD

**Issue by samuelsson86** [hassio-addons/addon-nginx-proxy-manager#97]
# Problem/Motivation

> After an internal error when trying to create a new proxy host with a SSL certificate, I restarted the addon. The addon now doesn't start anymore.

## Expected behavior

> Addon to start normally.

## Actual behavior

> The addon does not start and this error is displayed:

```
[11:16:48] INFO: Starting NGinx...
nginx: [emerg] unexpected ";" in /data/nginx/proxy_host/34.conf:41
```

## Steps to reproduce

> Not sure. It's probably connected to a restart after the internal error. I think the proxy host was created but status was unknown.

## Proposed changes

Don't know.

**Comment by robinhur** [comment]
i think i'm also having same issue like this
i just installed and clcked "start" button, and this error just came out

`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] permissions: applying... 
[fix-attrs.d] permissions: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
parse error: Expected string key before ':' at line 1, column 4
[17:06:17] ERROR: Unknown HTTP error occured
 Add-on: 
 
-----------------------------------------------------------
 Add-on version: 
 You are running the latest version of this add-on.
parse error: Expected string key before ':' at line 1, column 4
[17:06:18] ERROR: Unknown HTTP error occured
parse error: Expected string key before ':' at line 1, column 4
[17:06:18] ERROR: Unknown HTTP error occured
 System:   ( / )
 Home Assistant Core: 
 Home Assistant Supervisor: 
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] mysql.sh: executing... 
[17:06:19] ERROR: This add-on now requires the MariaDB core add-on 2.0 or newer!
[17:06:19] FATAL: Make sure the MariaDB add-on is installed and running
[cont-init.d] mysql.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.`
