### ISSUE TITLE
Block Headers

### ISSUE THREAD

**Issue by lrlf** [hassio-addons/addon-nginx-proxy-manager#98]
I'm running NPM on home assistant and I'm trying to get NPM to block  Headers, on security headers site after scan i get  a D report, is there a way to block this Headers, Content-Security-Policy, X-Frame-Options, Referrer-Policy, Feature-Policy, also is there a way to hide the real ip, here are the result of the scan, thank you for you great work

<img width="701" alt="Screen Shot 2020-06-28 at 1 34 49 AM" src="https://user-images.githubusercontent.com/36574565/85958189-98846080-b961-11ea-8ced-20fa232c4640.png">

**Comment by frenck** [comment]
You can define custom NGINX rules on a host, that should allow for blocking these I guess. If not, this would be a feature request for the NGINX Proxy Manager (which this add-on wraps). Such a feature request needs to be requested at the project upstream. Add-ons merely wrap existing applications.
